Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2020-09, with the labels that each got.

#263 rework e2e test organization
  tests-e2e/cypress/integration/backstage/backstage_spec.js
  tests-e2e/cypress/integration/backstage/incident_details_spec.js
  tests-e2e/cypress/integration/backstage/incident_list_spec.js
  tests-e2e/cypress/integration/backstage/playbook_details_spec.js
  tests-e2e/cypress/integration/backstage/playbook_list_spec.js
  tests-e2e/cypress/integration/frontstage/incident_creation_spec.js
  tests-e2e/cypress/integration/frontstage/incident_dialog_spec.js
  tests-e2e/cypress/integration/frontstage/incident_icon_spec.js
  tests-e2e/cypress/integration/incident_backstage/incident_backstage_spec.js
  tests-e2e/cypress/integration/incident_backstage/incident_details_spec.js
  tests-e2e/cypress/integration/incident_creation_spec.js
  tests-e2e/cypress/integration/incident_dialog_spec.js
  tests-e2e/cypress/integration/incident_icon_spec.js
  tests-e2e/cypress/integration/playbook_backstage/playbook_backstage_spec.js
  tests-e2e/cypress/plugins/index.js
  tests-e2e/cypress/support/index.js
  tests-e2e/cypress/support/plugin_api_commands.js
  tests-e2e/cypress/support/plugin_ui_commands.js
  tests-e2e/cypress/support/ui_commands.js
Labels: 4: Reviews Complete

#264 MM-26611: use compass icons
  webapp/src/components/assets/icons/dot_menu_icon.tsx
  webapp/src/components/assets/icons/file_icon.tsx
Labels: 1: UX Review, 2: Dev Review

#269 prompt for incident name and description
  server/api/incidents.go
  server/api/incidents_test.go
  server/incident/incident.go
  server/incident/service.go
  tests-e2e/cypress/integration/frontstage/incident_creation_spec.js
  tests-e2e/cypress/integration/frontstage/incident_dialog_spec.js
  tests-e2e/cypress/support/plugin_api_commands.js
  tests-e2e/cypress/support/plugin_ui_commands.js
Labels: 2: Dev Review

#266 MM-28280: add playbook descriptions
  server/playbook/playbook.go
  webapp/src/components/backstage/editable_text.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/types/playbook.ts
Labels: 2: Dev Review

#268 MM-27005 - Unit Test SQL Incident Store
  .circleci/config.yml
  build/custom.mk
  go.sum
  server/api/incidents.go
  server/incident/filter_options.go
  server/incident/incident.go
  server/playbook/playbook.go
  server/plugin.go
  server/pluginkvstore/incident_store.go
  server/pluginkvstore/incident_store_test.go
  server/pluginkvstore/pluginapi_client.go
  server/sqlstore/data_migration.go
  server/sqlstore/incident.go
  server/sqlstore/incident_test.go
  server/sqlstore/migrate.go
  server/sqlstore/migrations.go
  server/sqlstore/mocks/mock_configurationapi.go
  server/sqlstore/mocks/mock_kvapi.go
  server/sqlstore/mocks/mock_storeapi.go
  server/sqlstore/pluginapi_client.go
  server/sqlstore/store.go
  server/sqlstore/system.go
Labels: 2: Dev Review

#272 Update plugin-api dependency
  go.mod
  go.sum
  server/license.go
  server/license_test.go
  server/plugin.go
  server/pluginkvstore/mocks/serverpluginapi/mock_plugin.go
Labels: 2: Dev Review

#270 MM-27006 - Unit test the playbook store
  .circleci/config.yml
  server/incident/incident.go
  server/playbook/filter_options.go
  server/playbook/playbook.go
  server/playbook/service.go
  server/sqlstore/data_migration.go
  server/sqlstore/incident.go
  server/sqlstore/incident_test.go
  server/sqlstore/migrate.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_test.go
  server/sqlstore/store.go
  server/sqlstore/support_for_test.go
Labels: 2: Dev Review

#273 MM-28448 - Fix cypress test
  tests-e2e/cypress/integration/backstage/incident_list_spec.js
  tests-e2e/package-lock.json
  tests-e2e/package.json
  webapp/src/components/backstage/incidents/incident_details/incident_details.tsx
Labels: 4: Reviews Complete

#276 Playbook edit polish
  webapp/src/components/backstage/editable_text.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/profile_autocomplete.tsx
  webapp/src/components/backstage/share_playbook.tsx
  webapp/src/components/backstage/stage_edit.tsx
  webapp/src/components/backstage/stages_and_steps_edit.tsx
  webapp/src/components/backstage/step_edit.tsx
Labels: 2: Dev Review

#279 MM-28701: Fix timestamp handling
  server/sqlstore/data_migration.go
  webapp/src/components/rhs/duration.tsx
Labels: 4: Reviews Complete

#277 MM-28008 - Permissions checking in SQL; use subqueries
  server/api/api.go
  server/api/incidents.go
  server/api/incidents_test.go
  server/api/playbooks.go
  server/api/playbooks_test.go
  server/command/command.go
  server/incident/filter_options.go
  server/incident/incident.go
  server/incident/mocks/mock_service.go
  server/incident/mocks/mock_store.go
  server/incident/service.go
  server/permissions/permissions.go
  server/playbook/filter_options.go
  server/playbook/playbook.go
  server/playbook/service.go
  server/pluginkvstore/incident_store.go
  server/pluginkvstore/incident_store_test.go
  server/pluginkvstore/playbook_store.go
  server/sqlstore/data_migration.go
  server/sqlstore/incident.go
  server/sqlstore/incident_test.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_test.go
  server/sqlstore/support_for_test.go
  tests-e2e/cypress/integration/backstage/incident_list_spec.js
  tests-e2e/cypress/integration/frontstage/incident_creation_spec.js
  tests-e2e/cypress/integration/frontstage/incident_dialog_spec.js
  tests-e2e/cypress/support/index.js
  tests-e2e/cypress/support/plugin_api_commands.js
  tests-e2e/package-lock.json
  tests-e2e/package.json
  webapp/src/components/backstage/incidents/incident_details/incident_details.tsx
Labels: 2: Dev Review

#278 MM-28678 Cypress tests on CircleCI
  .circleci/config.yml
  server/plugin.go
  server/sqlstore/data_migration.go
  tests-e2e/cypress/support/plugin_ui_commands.js
  tests-e2e/db-setup/test_data.sql
Labels: 4: Reviews Complete

#281 MM-28683: Make the SQL store the default, remove all usage of incident/playbook KV stores
  build/custom.mk
  server/api/incidents_test.go
  server/api/playbooks_test.go
  server/api/subscriptions_test.go
  server/playbook/mocks/mock_service.go
  server/playbook/mocks/mock_store.go
  server/plugin.go
Labels: 2: Dev Review

#275 MM-27983: use defaultChecked when no onChange
  webapp/src/components/checklist_item.tsx
Labels: 2: Dev Review

#283 MM-28816: Remove incident and playbook KV store code
  build/custom.mk
  server/api/incidents.go
  server/api/playbooks.go
  server/incident/filter_options.go
  server/playbook/filter_options.go
  server/pluginkvstore/incident_store.go
  server/pluginkvstore/incident_store_test.go
  server/pluginkvstore/mocks/mock_storeapi.go
  server/pluginkvstore/mocks/mock_userapi.go
  server/pluginkvstore/playbook_store.go
  server/pluginkvstore/playbook_store_test.go
Labels: 4: Reviews Complete

#284 MM-28332: Add a fallback for when unaccent is not available (now ready to merge)
  server/sqlstore/incident.go
  server/sqlstore/migrate.go
  server/sqlstore/migrations.go
  server/sqlstore/store.go
  server/sqlstore/store_test.go
  server/sqlstore/support_for_test.go
  server/sqlstore/system.go
Labels: 4: Reviews Complete

#287 MM-28038: reset pagination on filtering
  tests-e2e/cypress/integration/backstage/incident_list_spec.js
  webapp/src/components/backstage/incidents/incident_list/incident_list.tsx
Labels: 2: Dev Review

#289 MM-28621 - "Incident" & "Playbook Not Found" image in backstage don't render properly
  webapp/src/components/assets/icons/warning_icon.tsx
Labels: 4: Reviews Complete

#285 allow changing stages after incident is ended
  server/incident/service.go
  server/incident/service_test.go
Labels: 4: Reviews Complete

#288 MM-28174 - Wrap task labels
  webapp/src/components/checklist.scss
Labels: 4: Reviews Complete

#292 MM-28797 - Fix permissions in incidents and playbook
  server/api/incidents.go
  server/api/incidents_test.go
  server/api/playbooks.go
  server/api/playbooks_test.go
  server/command/command.go
  server/incident/incident.go
  server/permissions/permissions.go
  server/playbook/playbook.go
  server/sqlstore/incident.go
  server/sqlstore/incident_test.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_test.go
Labels: 2: Dev Review

#295 MM-29002: Remove unaccent extension
  go.mod
  server/sqlstore/incident.go
  server/sqlstore/incident_test.go
  server/sqlstore/migrations.go
  server/sqlstore/store_test.go
  server/sqlstore/system.go
Labels: Setup Cloud Test Server

#296 MM-28949 - Fix the GetPlaybooksForTeam when used for starting an incident
  server/command/command.go
  server/incident/service.go
  server/playbook/playbook.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_test.go
Labels: 2: Dev Review

#298 MM-29021: Fix timestamp bug in data migration
  server/sqlstore/data_migration.go
  server/sqlstore/data_migration_test.go
Labels: 3: QA Review

#299 More closely match server golangci configuration, removing some flaky linters.
  .golangci.yml
Labels: 2: Dev Review

#297 MM-29009 - Allow playbooks and incident stages with no checklists
  server/api/incidents_test.go
  server/api/playbooks_test.go
  server/incident/incident.go
  server/incident/incident_test.go
  server/playbook/playbook.go
  server/playbook/playbook_test.go
  server/sqlstore/incident.go
  server/sqlstore/incident_test.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_test.go
  webapp/src/components/backstage/incidents/incident_details/checklist_timeline.tsx
  webapp/src/websocket_events.ts
Labels: 4: Reviews Complete

#304 MM-28931: show incident status in RHS
  tests-e2e/cypress/integration/frontstage/incident_rhs_spec.js
  webapp/src/components/backstage/incidents/status_badge.tsx
  webapp/src/components/rhs/rhs_title.scss
  webapp/src/components/rhs/rhs_title.tsx
Labels: 4: Reviews Complete

#302 MM-28932: Reduce duration granularity to 1m.
  webapp/src/components/backstage/incidents/incident_details/incident_details.tsx
  webapp/src/components/backstage/incidents/status_badge.tsx
  webapp/src/components/duration.test.tsx
  webapp/src/components/duration.tsx
  webapp/src/components/rhs/incident_details.tsx
Labels: 4: Reviews Complete

#291 MM-28285: /incident list
  server/api/incidents.go
  server/api/incidents_test.go
  server/bot/bot.go
  server/bot/mocks/mock_poster.go
  server/bot/poster.go
  server/command/command.go
  server/command/command_test.go
  server/incident/filter_options.go
  server/incident/incident.go
  server/incident/service.go
  server/incident/service_test.go
  server/sqlstore/incident.go
  server/sqlstore/incident_test.go
  server/sqlstore/migrate.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook_test.go
  server/sqlstore/support_for_test.go
Labels: 4: Reviews Complete

#293 /incident commander
  go.mod
  go.sum
  server/command/command.go
  server/incident/incident_test.go
  tests-e2e/cypress/fixtures/theme.json
  tests-e2e/cypress/integration/frontstage/slash_command_spec.js
  tests-e2e/cypress/support/api/preference.js
  tests-e2e/cypress/support/index.js
  tests-e2e/cypress/support/plugin_api_commands.js
  tests-e2e/cypress/support/plugin_ui_commands.js
  tests-e2e/cypress/support/ui_commands.js
Labels: 4: Reviews Complete
