Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2020-11, with the labels that each got.

#373 MM-30189 - Fix: Incident creation lacks checks for playbook permissions
  server/api/incidents.go
  server/api/incidents_test.go
Labels: 2: Dev Review

#372 MM-30166 - Rename playbook to incident management
  .circleci/config.yml
  tests-e2e/cypress/integration/backstage/playbook_creation_spec.js
  webapp/src/components/backstage/template_selector.tsx
  webapp/src/components/rhs/rhs_welcome_view.tsx
Labels: 2: Dev Review

#360 Update telemetry.md
  docs/telemetry.md
Labels: 1. Editor Review

#369 bump to v1.1.0
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 4: Reviews Complete

#375 MM-30207 - include playbook id in telemetry; bump to v1.1.1
  plugin.json
  server/manifest.go
  server/telemetry/rudder.go
  server/telemetry/rudder_test.go
  webapp/src/manifest.js
Labels: 4: Reviews Complete

#376 [MM-15772] Showing more user details in the share playbook auto-complete
  tests-e2e/cypress/support/plugin_ui_commands.js
  webapp/src/components/backstage/profile_autocomplete.tsx
Labels: 4: Reviews Complete

#356 MM-29663 - Summary and Tasks tabs for RHS Details View
  tests-e2e/cypress/integration/frontstage/incident_rhs_checklist_spec.js
  tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/footer_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/stages_spec.js
  tests-e2e/cypress/integration/frontstage/slash_command/stage_spec.js
  webapp/src/actions.ts
  webapp/src/components/checklist.scss
  webapp/src/components/rhs/incident_details.scss
  webapp/src/components/rhs/incident_details.tsx
  webapp/src/components/rhs/rhs_details_view.tsx
  webapp/src/components/rhs/rhs_footer_tasks.tsx
  webapp/src/components/rhs/rhs_incident_summary.tsx
  webapp/src/components/rhs/rhs_incident_tasks.tsx
  webapp/src/components/rhs/rhs_list_view.tsx
  webapp/src/components/rhs/rhs_shared.tsx
  webapp/src/components/rhs/rhs_tab_view.tsx
  webapp/src/components/rhs/stage.tsx
  webapp/src/reducer.ts
  webapp/src/selectors.ts
  webapp/src/types/actions.ts
  webapp/src/types/rhs.ts
Labels: 4: Reviews Complete

#374 MM-29706 - update status dialog; recent update post
  server/api/incidents.go
  server/api/incidents_test.go
  server/command/command.go
  server/incident/incident.go
  server/incident/incident_test.go
  server/incident/mocks/mock_service.go
  server/incident/service.go
  server/sqlstore/incident.go
  server/sqlstore/incident_test.go
  server/sqlstore/migrations.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
  webapp/src/actions.ts
  webapp/src/components/rhs/rhs_footer_summary.tsx
  webapp/src/components/rhs/rhs_footer_tasks.tsx
  webapp/src/components/rhs/rhs_incident_summary.tsx
  webapp/src/components/rhs/rhs_shared.tsx
  webapp/src/types/incident.ts
Labels: 4: Reviews Complete

#378 MM-30249: Avoid sending internal errors to the client
  client/client.go
  server/api/api.go
  server/api/incidents_test.go
  server/api/playbooks.go
  server/api/playbooks_test.go
Labels: 4: Reviews Complete

#380 MM-29712 - "Last updated" time in RHS Incident list view
  webapp/src/components/duration.tsx
  webapp/src/components/rhs/rhs_incident_summary.tsx
  webapp/src/components/rhs/rhs_list_view.tsx
Labels: 4: Reviews Complete

#382 Delete telemetry.md
  docs/SUMMARY.md
  docs/telemetry.md
Labels: 2: Dev Review

#383 MM-30191: handle leaving channel without teamId
  webapp/src/actions.ts
  webapp/src/reducer.test.ts
  webapp/src/reducer.ts
  webapp/src/types/actions.ts
  webapp/src/websocket_events.ts
Labels: 4: Reviews Complete

#358 MM-29867: Commands to generate test data
  .circleci/config.yml
  .golangci.yml
  server/api/playbooks.go
  server/command/command.go
  server/incident/incident.go
  server/incident/mocks/mock_service.go
  server/incident/mocks/mock_store.go
  server/incident/service.go
  server/plugin.go
  server/sqlstore/incident.go
  server/sqlstore/incident_test.go
  tests-e2e/cypress/integration/frontstage/slash_command/test_spec.js
  tests-e2e/cypress/support/server_api_commands.js
  tests-e2e/package-lock.json
  tests-e2e/package.json
Labels: 4: Reviews Complete, Docs/Needed

#379 MM-29771 - Reminder for next update
  .golangci.yml
  go.mod
  go.sum
  server/api/api.yaml
  server/api/incidents.go
  server/api/incidents_test.go
  server/bot/bot.go
  server/bot/mocks/mock_poster.go
  server/bot/poster.go
  server/incident/incident.go
  server/incident/incident_test.go
  server/incident/mocks/mock_service.go
  server/incident/reminder.go
  server/incident/service.go
  server/incident/service_test.go
  server/plugin.go
  server/sqlstore/incident.go
  server/sqlstore/incident_test.go
  server/sqlstore/migrations.go
  server/sqlstore/stats_for_test.go
  server/sqlstore/support_for_test.go
  webapp/.eslintrc.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/client.ts
  webapp/src/components/__snapshots__/duration.test.tsx.snap
  webapp/src/components/checklist_item.tsx
  webapp/src/components/duration.test.tsx
  webapp/src/components/duration.tsx
  webapp/src/components/rhs/rhs_incident_summary.tsx
  webapp/src/components/rhs/rhs_list_incident.tsx
  webapp/src/components/rhs/rhs_list_view.tsx
  webapp/src/hooks.ts
  webapp/src/selectors.ts
  webapp/src/types/incident.ts
Labels: 4: Reviews Complete

#377 MM-29673: Recent Update view
  server/incident/mocks/mock_service.go
  tests-e2e/cypress/integration/frontstage/rhs/latest_update_spec.js
  tests-e2e/cypress/integration/frontstage/slash_command/test_spec.js
  tests-e2e/cypress/support/server_api_commands.js
  tests-e2e/cypress/support/ui_commands.js
  webapp/src/components/rhs/latest_update.tsx
  webapp/src/components/rhs/rhs_incident_summary.tsx
  webapp/src/components/rhs/show_more.tsx
  webapp/src/index.tsx
  webapp/src/selectors.ts
  webapp/src/websocket_events.ts
Labels: 4: Reviews Complete

#386 MM-30262 - Checking and unchecking the checklist items throws JS error
  server/api/incidents.go
  webapp/src/client.ts
Labels: 4: Reviews Complete

#387 update nuke-db
  server/incident/mocks/mock_store.go
  server/plugin.go
  server/sqlstore/incident.go
  server/sqlstore/migrate.go
Labels: 4: Reviews Complete

#381 MM-29713: Broadcast status update
  server/api/incidents.go
  server/command/command.go
  server/incident/incident.go
  server/incident/incident_test.go
  server/incident/service.go
  server/playbook/playbook.go
  server/playbook/playbook_test.go
  server/sqlstore/incident.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook.go
  server/timeutils/timeutils.go
  server/timeutils/timeutils_test.go
  tests-e2e/cypress/integration/backstage/playbook_creation_spec.js
  tests-e2e/cypress/integration/frontstage/incident_broadcast_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/latest_update_spec.js
  tests-e2e/cypress/support/plugin_api_commands.js
  tests-e2e/cypress/support/server_api_commands.js
  tests-e2e/cypress/utils/index.js
  webapp/src/components/backstage/channel_selector.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/types/incident.ts
  webapp/src/types/playbook.ts
Labels: 4: Reviews Complete

#385 MM-30206: Update incident dialog should pre-populate status with previous update text
  server/incident/service.go
  tests-e2e/cypress/integration/frontstage/rhs/latest_update_spec.js
  tests-e2e/cypress/support/ui_commands.js
Labels: 4: Reviews Complete

#389 MM-30517 - Update Tasks header to new design
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/stages_and_steps_edit.tsx
Labels: 4: Reviews Complete

#392 Playbook link is broken
  docs/README.md
Labels: 1. Editor Review
