Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2020-10, with the labels that each got.

#306 Add /incident info
  server/command/command.go
  webapp/src/slash_command.ts
Labels: 1: UX Review, 2: Dev Review

#309 Bump version and disable linting
  .circleci/config.yml
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 2: Dev Review

#311 Add E2E test for /incident info
  tests-e2e/cypress/integration/frontstage/slash_command_spec.js
Labels: 2: Dev Review

#308 MM-29136 - Fix backstage jump to channel
  go.mod
  go.sum
  server/api/incidents_test.go
  server/incident/incident.go
  server/incident/incident_test.go
  server/incident/mocks/mock_service.go
  server/incident/service.go
  webapp/package.json
  webapp/src/client.ts
  webapp/src/components/backstage/incidents/incident_details/incident_details.tsx
  webapp/src/types/incident.ts
  webapp/src/websocket_events.ts
Labels: 2: Dev Review

#301 MM-28037: invalid slash command handling
  .circleci/config.yml
  server/api/incidents.go
  server/incident/incident.go
  server/incident/mocks/mock_service.go
  server/incident/service.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
  tests-e2e/cypress/integration/frontstage/incident_rhs_checklist_spec.js
  webapp/src/client.ts
  webapp/src/components/checklist.tsx
  webapp/src/components/checklist_item.tsx
Labels: 4: Reviews Complete

#312 MM-28296: improved slash command autocomplete
  tests-e2e/cypress/integration/backstage/playbook_details_spec.js
  webapp/src/components/backstage/step_edit.tsx
Labels: 4: Reviews Complete

#310 MM-28607: run slash command polish
  server/incident/service.go
  server/playbook/playbook.go
  tests-e2e/cypress/integration/frontstage/incident_rhs_checklist_spec.js
  webapp/src/components/assets/icons/spinner.tsx
  webapp/src/components/backstage/incidents/incident_details/incident_details.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/backstage/stage_edit.tsx
  webapp/src/components/checklist.scss
  webapp/src/components/checklist_item.tsx
  webapp/src/components/rhs/rhs_main.tsx
  webapp/src/types/playbook.ts
Labels: 4: Reviews Complete

#315 MM-29158: fix custom components in react select
  webapp/src/components/backstage/incidents/incident_list/incident_list.tsx
  webapp/src/components/checklist_item.tsx
  webapp/src/components/profile/profile_selector.tsx
Labels: 4: Reviews Complete

#317 MM-26181: deprecate /end-dialog endpoint
  server/api/api.yaml
  server/api/incidents.go
  server/api/incidents_test.go
  server/incident/service.go
Labels: 2: Dev Review

#305 Adding playbook backstage tests
  tests-e2e/cypress/integration/backstage/playbook_creation_spec.js
  webapp/src/components/backstage/playbook_edit.tsx
Labels: 2: Dev Review

#314 Updated copy and styling
  server/playbook/playbook.go
  tests-e2e/cypress/integration/frontstage/incident_dialog_spec.js
  tests-e2e/cypress/integration/frontstage/incident_rhs_spec.js
  tests-e2e/cypress/integration/frontstage/slash_command_spec.js
  tests-e2e/cypress/support/plugin_ui_commands.js
  webapp/src/components/assets/icons/alert_icon.tsx
  webapp/src/components/assets/icons/siren_icon.tsx
  webapp/src/components/assets/left_dots.tsx
  webapp/src/components/assets/left_fade.tsx
  webapp/src/components/assets/right_dots.tsx
  webapp/src/components/assets/right_fade.tsx
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/incidents/incident_details/incident_details.tsx
  webapp/src/components/backstage/incidents/incident_list/incident_list.tsx
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/backstage/template_selector.tsx
  webapp/src/components/rhs/rhs_main.tsx
Labels: 2: Dev Review

#319 MM-28674: Stage simplification
  .circleci/config.yml
  server/api/incidents.go
  server/command/command.go
  server/incident/incident.go
  server/incident/mocks/mock_service.go
  server/incident/service.go
  tests-e2e/cypress/integration/backstage/playbook_creation_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/footer_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/header_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/open_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/stages_spec.js
  tests-e2e/cypress/integration/frontstage/slash_command/commander_spec.js
  tests-e2e/cypress/integration/frontstage/slash_command/info_spec.js
  tests-e2e/cypress/integration/frontstage/slash_command/stage_spec.js
  webapp/src/actions.ts
  webapp/src/components/assets/icons/three_dots_icon.tsx
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/checklist.scss
  webapp/src/components/dot_menu.tsx
  webapp/src/components/rhs/incident_details.scss
  webapp/src/components/rhs/incident_details.tsx
Labels: 4: Reviews Complete

#321 MM-28941: stage progress bar
  webapp/src/components/rhs/incident_details.tsx
Labels: 4: Reviews Complete

#320 MM-28922: what are incidents landing page
  tests-e2e/cypress/integration/backstage/backstage_spec.js
  tests-e2e/cypress/integration/backstage/incident_list_spec.js
  webapp/src/components/assets/no_content_incidents_svg.tsx
  webapp/src/components/backstage/incidents/incident_list/incident_list.tsx
Labels: 4: Reviews Complete

#322 fix sort by status
  webapp/src/components/backstage/incidents/incident_list/incident_list.tsx
Labels: 2: Dev Review

#325 MM-29286: Change API version to v0
  client/client.go
  server/api/api.go
  server/api/api.yaml
  server/api/api_test.go
  server/api/incidents_test.go
  server/api/playbooks_test.go
  server/api/subscriptions_test.go
  server/command/command.go
  server/incident/service.go
  tests-e2e/cypress/support/endpoints.json
  tests-e2e/cypress/support/plugin_api_commands.js
  webapp/src/client.ts
Labels: 2: Dev Review

#324 MM-28373: Remove data migration
  server/plugin.go
  server/sqlstore/data_migration.go
  server/sqlstore/data_migration_test.go
  server/sqlstore/incident_test.go
  server/sqlstore/migrate.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook_test.go
  server/sqlstore/support_for_test.go
Labels: 4: Reviews Complete

#323 MM-26166 incident metadata endpoint
  server/api/incidents.go
  server/api/incidents_test.go
  server/incident/incident.go
  server/incident/incident_test.go
  server/incident/mocks/mock_service.go
  server/incident/service.go
  server/sqlstore/incident.go
  server/sqlstore/incident_test.go
  webapp/src/client.ts
  webapp/src/components/backstage/incidents/incident_details/incident_details.tsx
  webapp/src/types/incident.ts
Labels: 4: Reviews Complete

#318 MM-28604 - RHS List View
  server/api/incidents.go
  server/command/command.go
  server/incident/incident.go
  server/sqlstore/incident.go
  server/sqlstore/incident_test.go
  tests-e2e/cypress/integration/backstage/backstage_spec.js
  tests-e2e/cypress/integration/backstage/incident_list_spec.js
  tests-e2e/cypress/integration/backstage/playbook_details_spec.js
  tests-e2e/cypress/integration/backstage/playbook_list_spec.js
  tests-e2e/cypress/integration/frontstage/incident_dialog_spec.js
  tests-e2e/cypress/integration/frontstage/incident_rhs_checklist_spec.js
  tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/header_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/open_spec.js
  tests-e2e/cypress/support/index.js
  tests-e2e/cypress/support/plugin_api_commands.js
  tests-e2e/cypress/support/plugin_ui_commands.js
  tests-e2e/cypress/support/server_api_commands.js
  tests-e2e/cypress/support/ui_commands.js
  webapp/src/actions.ts
  webapp/src/client.ts
  webapp/src/components/assets/icons/dot_menu_icon.tsx
  webapp/src/components/assets/icons/left_chevron.tsx
  webapp/src/components/assets/icons/three_dots_icon.tsx
  webapp/src/components/backstage/incidents/status_badge.tsx
  webapp/src/components/dot_menu.tsx
  webapp/src/components/duration.tsx
  webapp/src/components/rhs/incident_details.tsx
  webapp/src/components/rhs/rhs_details_view.tsx
  webapp/src/components/rhs/rhs_list_view.tsx
  webapp/src/components/rhs/rhs_main.tsx
  webapp/src/components/rhs/rhs_shared.tsx
  webapp/src/components/rhs/rhs_title.tsx
  webapp/src/components/rhs/rhs_welcome_view.tsx
  webapp/src/hooks.ts
  webapp/src/index.tsx
  webapp/src/reducer.ts
  webapp/src/rhs_opener.ts
  webapp/src/selectors.ts
  webapp/src/types/actions.ts
  webapp/src/types/incident.ts
  webapp/src/types/rhs.ts
  webapp/src/websocket_events.ts
Labels: 4: Reviews Complete

#327 MM-29482 - Add button hovers on triple dots
  tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js
  webapp/src/components/assets/icons/dot_menu_icon.tsx
  webapp/src/components/assets/icons/three_dots_icon.tsx
  webapp/src/components/backstage/playbook.scss
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/dot_menu.tsx
  webapp/src/components/rhs/incident_details.tsx
  webapp/src/components/rhs/rhs_list_view.tsx
Labels: 4: Reviews Complete

#326 MM-29485: explicitly support "no stages"
  server/api/incidents_test.go
  server/incident/incident.go
  server/incident/incident_test.go
  tests-e2e/cypress/integration/frontstage/rhs/stages_spec.js
  webapp/src/components/rhs/incident_details.tsx
Labels: 2: Dev Review

#328 MM-29481, MM-29483, MM-29484 - Commander dropdown, /incident list fixes
  server/command/command.go
  server/command/command_test.go
  webapp/src/components/profile/profile_selector.scss
  webapp/src/components/profile/profile_selector.tsx
Labels: 2: Dev Review

#313 Create .gitbook.yaml
  .gitbook.yaml
  docs/SUMMARY.md
  docs/administrator-guide/incident-response-slash-commands.md
  docs/administrator-guide/overview.md
  docs/administrator-guide/permissions.md
  docs/glossary.md
  docs/incidents/ending-an-incident.md
  docs/incidents/joining-an-incident.md
  docs/incidents/managing-an-incident.md
  docs/incidents/reviewing-incidents.md
  docs/incidents/starting-an-incident.md
  docs/playbooks/creating-a-playbook.md
  docs/playbooks/incident-task-management.md
  docs/playbooks/playbook-overview.md
  docs/telemetry.md
Labels: 4: Reviews Complete

#331 MM-29606 - Fix flaky RHS list spec
  tests-e2e/cypress/integration/frontstage/incident_creation_spec.js
  tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js
  tests-e2e/cypress/support/plugin_api_commands.js
Labels: 4: Reviews Complete

#335 MM-29380: remove create playbook prompt on mobile
  server/command/command.go
  server/incident/incident.go
  server/incident/mocks/mock_service.go
  server/incident/service.go
  server/incident/service_test.go
Labels: 2: Dev Review

#333 Update README.md
  README.md
Labels: 4: Reviews Complete

#329 MM-29126: sync starter template (#15654)
  .editorconfig
  .gitattributes
  Makefile
  build/go.mod
  build/go.sum
  build/pluginctl/main.go
  build/sync/README.md
  build/sync/main.go
  build/sync/plan.yml
  build/sync/plan/actions.go
  build/sync/plan/actions_test.go
  build/sync/plan/checks.go
  build/sync/plan/checks_test.go
  build/sync/plan/git/file_history.go
  build/sync/plan/git/file_history_test.go
  build/sync/plan/git/testdata/testfile.txt
  build/sync/plan/plan.go
  build/sync/plan/plan_test.go
  build/sync/plan/setup.go
  build/sync/plan/testdata/a
  build/sync/plan/testdata/b/c
Labels: 2: Dev Review, Hacktoberfest, hacktoberfest-accepted

#334 IR docs v2
  docs/README.md
  docs/SUMMARY.md
  docs/administrator-guide/incident-response-slash-commands.md
  docs/administrator-guide/overview.md
  docs/assets/delete_playbook.png
  docs/assets/file.md
  docs/assets/stage_task_header.png
  docs/assets/stage_task_slashcommand.png
  docs/incidents/joining-an-incident.md
  docs/incidents/managing-an-incident.md
  docs/incidents/starting-an-incident.md
  docs/incidents/starting-and-joining-incidents.md
  docs/incidents/viewing-incident-details.md
  docs/playbooks/creating-a-playbook.md
  docs/playbooks/incident-task-management.md
  docs/playbooks/playbook-overview.md
Labels: 1: UX Review, 2: Dev Review

#337 MM-29699: Fix crash after /incident stage with no arguments
  server/command/command.go
  tests-e2e/cypress/integration/frontstage/slash_command/stage_spec.js
Labels: 4: Reviews Complete

#338 Incident response v3 docs
  README.md
  docs/README.md
  docs/SUMMARY.md
  docs/administrator-guide/overview.md
  docs/contributing.md
  docs/help-and-support.md
  docs/incidents/starting-and-joining-an-incident.md
Labels: 2: Dev Review

#339 Update SUMMARY.md
  docs/SUMMARY.md
Labels: 2: Dev Review

#342 Revert change in channel export path
  webapp/src/client.ts
Labels: 4: Reviews Complete

#341 IR-docs-v4
  README.md
  assets/incident_response.png
  docs/README.md
  docs/SUMMARY.md
  docs/assets/confirm_end_incident.png
  docs/assets/delete_playbook.png
  docs/assets/incident_end_slash_command.png
  docs/assets/incident_response_screen.png
  docs/assets/incident_restart_slash_command.png
  docs/assets/playbook_stage_edit.png
  docs/incidents/ending-an-incident.md
  docs/incidents/viewing-incident-details.md
  docs/playbooks/creating-a-playbook.md
  docs/playbooks/creating-and-managing-playbooks.md
  docs/playbooks/playbook-overview.md
Labels: 4: Reviews Complete

#343 Update SUMMARY.md
  docs/SUMMARY.md
  docs/incidents/ending-an-incident.md
Labels: 2: Dev Review

#344 restore plugin-ci/lint
  .circleci/config.yml
Labels: 4: Reviews Complete

#340 MM-26182: Standardize filtering parameters
  client/doc.go
  client/incidents.go
  server/api/api.yaml
  server/api/incidents.go
  server/api/playbooks.go
  server/command/command.go
  server/incident/filter_options.go
  server/playbook/filter_options.go
  server/sqlstore/incident.go
  server/sqlstore/incident_test.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_test.go
  webapp/src/components/backstage/incidents/incident_list/incident_list.tsx
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/sortable_col_header.tsx
  webapp/src/types/incident.ts
Labels: 4: Reviews Complete

#316 [MM-28729] Fix days calculation for duration
  webapp/src/components/duration.test.tsx
  webapp/src/components/duration.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#346 Update ending-an-incident.md
  README.md
  docs/README.md
  docs/SUMMARY.md
  docs/administrator-guide/incident-response-slash-commands.md
  docs/assets/incident_end_slash_command.png
  docs/assets/incident_response_landing.png
  docs/incidents/ending-an-incident.md
  docs/incidents/starting-and-joining-an-incident.md
  docs/incidents/viewing-incident-details.md
  docs/playbooks/creating-and-managing-playbooks.md
Labels: 2: Dev Review

#345 set RUDDER env for build artifacts only
  .circleci/config.yml
Labels: 4: Reviews Complete

#349 Use replace for local modules.
  client/go.mod
  go.mod
Labels: 4: Reviews Complete

#347 MM-26194: Standardize HTTP status codes
  server/api/api.go
  server/api/incidents.go
  server/api/incidents_test.go
  server/api/playbooks.go
  server/api/playbooks_test.go
  server/incident/incident.go
  tests-e2e/cypress/support/plugin_api_commands.js
Labels: 4: Reviews Complete

#352 Update README.md
  README.md
  docs/README.md
  docs/SUMMARY.md
  docs/administrator-guide/incident-response-slash-commands.md
  docs/glossary.md
  docs/incidents/ending-an-incident.md
  docs/incidents/starting-and-joining-an-incident.md
  docs/telemetry.md
Labels: 4: Reviews Complete

#353 Update telemetry formatting
  docs/telemetry.md
Labels: 2: Dev Review

#354 Revert "Update telemetry formatting"
  docs/telemetry.md
Labels: 4: Reviews Complete

#350 MM-29720 - Consistently track Mattermost User ID aross telemetry events
  go.mod
  go.sum
  server/api/incidents.go
  server/api/incidents_test.go
  server/api/playbooks.go
  server/api/playbooks_test.go
  server/command/command.go
  server/incident/incident.go
  server/incident/mocks/mock_service.go
  server/incident/service.go
  server/incident/service_test.go
  server/playbook/mocks/mock_service.go
  server/playbook/playbook.go
  server/playbook/service.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
  server/telemetry/rudder_test.go
Labels: 4: Reviews Complete

#361 MM-29886 - Fix for createIncidentFromDialog allows creating incidents in arbitrary teams
  server/api/incidents.go
  server/api/incidents_test.go
Labels: 2: Dev Review

#359 MM-29754 - Revisit telemetry event structure
  server/incident/incident.go
  server/incident/service.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
  server/telemetry/rudder_test.go
Labels: 4: Reviews Complete

#363 MM-29897 - Fix for: /incident announce allows announcing to arbitrary channels
  server/command/command.go
  server/permissions/permissions.go
Labels: 2: Dev Review

#364 MM-29899 - Fix for: createIncidentFromDialog allows reading contents of arbitrary posts
  server/api/incidents.go
  server/api/incidents_test.go
Labels: 2: Dev Review

#368 Admin Installation Steps
  docs/SUMMARY.md
  docs/administrator-guide/installation-and-activation.md
Labels: 4: Reviews Complete

#355 [MM-29944] Add plugin icon and metadata
  assets/incident_plugin_icon.svg
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 4: Reviews Complete

#371 MM-30135 - Fix: Playbook update in 1.1 is a bit broken
  webapp/src/client.ts
Labels: 2: Dev Review
