Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2020-12, with the labels that each got.

#394 MM-30259: Fix backstage bug
  tests-e2e/cypress/integration/backstage/incident_list_spec.js
  webapp/src/client.ts
Labels: 4: Reviews Complete

#393 Update SUMMARY.md
  docs/README.md
  docs/SUMMARY.md
Labels: 4: Reviews Complete

#391 MM-30787 - Deleting a status post should update Last Updated field
  server/incident/service.go
  tests-e2e/.eslintrc
  tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js
  tests-e2e/cypress/support/plugin_api_commands.js
  webapp/src/index.tsx
  webapp/src/selectors.ts
  webapp/src/websocket_events.ts
Labels: 2: Dev Review

#396 Change incident bot's icon
  assets/incident_plugin_icon.png
Labels: 2: Dev Review

#399 bumping v1.2.0-alpha.2 pre-emptively for next push
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 4: Reviews Complete

#397 Fixing flaky e2e tests
  tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js
Labels: 4: Reviews Complete

#398 MM-31038 - Ending an incident cancels any outstanding reminder
  server/incident/reminder.go
  server/incident/service.go
Labels: 4: Reviews Complete

#401 MM-31039 - Previous reminder time becomes default for next reminder time
  server/incident/incident.go
  server/incident/incident_test.go
  server/incident/service.go
  server/sqlstore/incident.go
  server/sqlstore/migrations.go
  tests-e2e/cypress/integration/frontstage/rhs/latest_update_spec.js
  tests-e2e/cypress/support/ui_commands.js
Labels: 2: Dev Review

#400 MM-31047 - Add 10 second timer to list in devMode && testingMode
  server/api/incidents.go
  server/config/config.go
  server/config/mocks/mock_service.go
  server/config/service.go
  server/incident/incident.go
  server/incident/incident_test.go
  server/incident/mocks/mock_service.go
  server/incident/mocks/mock_store.go
  server/incident/service.go
  server/sqlstore/incident.go
  server/sqlstore/migrations.go
  tests-e2e/cypress/integration/frontstage/rhs/latest_update_spec.js
  tests-e2e/cypress/support/ui_commands.js
Labels: 2: Dev Review

#402 MM-31086: Make SQL migrations idempotent
  server/sqlstore/migrations.go
  server/sqlstore/migrations_utils.go
  server/sqlstore/store_test.go
  server/sqlstore/system.go
  server/sqlstore/versions.go
Labels: 4: Reviews Complete

#405 Fix msql migrations
  server/sqlstore/migrations_utils.go
Labels: 2: Dev Review

#406 MM-30519 Moving broadcast channel, adding reminder timer and message template to preferences tab.
  server/api/incidents.go
  server/incident/incident.go
  server/incident/incident_test.go
  server/incident/service.go
  server/playbook/playbook.go
  server/playbook/playbook_test.go
  server/sqlstore/incident.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook.go
  tests-e2e/cypress/integration/frontstage/rhs/latest_update_spec.js
  tests-e2e/cypress/support/plugin_api_commands.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/backstage/channel_selector.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/stages_and_steps_edit.tsx
  webapp/src/components/backstage/step_edit.tsx
  webapp/src/components/backstage/styles.tsx
  webapp/src/types/playbook.ts
  webapp/src/websocket_events.ts
Labels: 4: Reviews Complete

#384 #15761
  webapp/src/components/checklist_item.tsx
Labels: 4: Reviews Complete

#408 MM-31187 Enable broadcast to private channels.
  server/api/playbooks.go
  server/api/playbooks_test.go
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/backstage/channel_selector.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/websocket_events.ts
Labels: 3: QA Review

#411 MM-31255: Bump plugin-api version
  go.mod
  go.sum
Labels: 4: Reviews Complete

#410 MM-31241, MM-31237: Fix update status dialog
  server/incident/service.go
  tests-e2e/cypress/integration/backstage/incident_list_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/latest_update_spec.js
  tests-e2e/cypress/support/server_api_commands.js
  tests-e2e/cypress/support/ui_commands.js
Labels: 4: Reviews Complete

#403 Update incident-response-slash-commands.md
  docs/administrator-guide/incident-response-slash-commands.md
Labels: 4: Reviews Complete

#415 MM-31242: fix unusual backstage shadows
  webapp/src/components/assets/left_fade.tsx
  webapp/src/components/assets/right_fade.tsx
Labels: 4: Reviews Complete

#414 MM-31240: Set min height on backstage header
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/incidents/incident_details/incident_details.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/styles.tsx
Labels: 4: Reviews Complete

#395 Change the text of the ephemeral message from "You can only show..." to "You can only see..."
  server/command/command.go
  tests-e2e/cypress/integration/frontstage/slash_command/commander_spec.js
Labels: 4: Reviews Complete

#416 MM-31243: broadcast channel tweaks
  tests-e2e/cypress/integration/backstage/playbook_details_spec.js
  webapp/src/components/backstage/channel_selector.tsx
  webapp/src/components/backstage/playbook_edit.tsx
Labels: 4: Reviews Complete

#417 MM-31234: remove reminder post on end
  build/custom.mk
  server/incident/incident.go
  server/incident/mocks/mock_job_once_scheduler.go
  server/incident/reminder.go
  server/incident/service.go
  server/incident/service_test.go
Labels: 2: Dev Review

#418 bump to v1.2.0
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 2: Dev Review

#412 MM-28969 Enabled open RHS with incident list when issuing /incident list from webapp
  server/command/command.go
  webapp/src/slash_command.ts
Labels: 4: Reviews Complete
