Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2021-01, with the labels that each got.

#407 Fix start incident double execute
  webapp/src/components/post_menu.tsx
Labels: 4: Reviews Complete

#422 [MM-31683] Fixing e2e and postgres
  .circleci/config.yml
  tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js
  tests-e2e/cypress/integration/frontstage/slash_command/test_spec.js
  tests-e2e/cypress/support/ui_commands.js
Labels: 4: Reviews Complete

#423 Update README.md
  README.md
Labels: 4: Reviews Complete

#419 MM-31205 - Refactoring & use the redux as the source of truth for the frontend
  server/api/incidents.go
  server/api/incidents_test.go
  server/command/command.go
  server/incident/incident.go
  server/incident/incident_test.go
  server/incident/service_test.go
  server/sqlstore/incident_test.go
  server/telemetry/rudder_test.go
  webapp/src/components/rhs/rhs_details_view.tsx
  webapp/src/components/rhs/rhs_title.tsx
  webapp/src/hooks.ts
  webapp/src/selectors.ts
Labels: 4: Reviews Complete

#425 MM-31007: handle err fetching incident by channel
  webapp/src/websocket_events.ts
Labels: 3: QA Review

#427 Fix e2e tests again
  tests-e2e/cypress/integration/frontstage/slash_command/test_spec.js
  tests-e2e/cypress/support/ui_commands.js
  tests-e2e/package-lock.json
  tests-e2e/package.json
Labels: 2: Dev Review

#426 Remove search bar bug workarounds
  tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js
Labels: 2: Dev Review

#421 MM-31634 Remove stages and restore single checklist.
  server/api/incidents.go
  server/api/incidents_test.go
  server/command/command.go
  server/incident/incident.go
  server/incident/incident_test.go
  server/incident/service.go
  server/incident/service_test.go
  server/sqlstore/incident.go
  server/sqlstore/incident_test.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
  server/telemetry/rudder_test.go
  tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/footer_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/stages_spec.js
  tests-e2e/cypress/integration/frontstage/slash_command/stage_spec.js
  tests-e2e/cypress/integration/frontstage/slash_command/test_spec.js
  webapp/src/actions.ts
  webapp/src/client.ts
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/backstage/stages_and_steps_edit.tsx
  webapp/src/components/rhs/rhs_details_view.tsx
  webapp/src/components/rhs/rhs_footer_tasks.tsx
  webapp/src/components/rhs/rhs_incident_summary.tsx
  webapp/src/components/rhs/rhs_incident_tasks.tsx
  webapp/src/components/rhs/rhs_list_incident.tsx
  webapp/src/components/rhs/stage.tsx
  webapp/src/types/playbook.ts
Labels: 4: Reviews Complete

#428 MM-31919: set id when rendering Textbox
  webapp/src/components/backstage/step_edit.tsx
  webapp/src/utils.test.ts
  webapp/src/utils.ts
Labels: 4: Reviews Complete

#434 testing e2e with master & 5.31 mattermost docker images
  .circleci/config.yml
Labels: 2: Dev Review

#433 MM-32148 - Generate version metadata from tags
  .gitignore
  Makefile
  build/manifest/main.go
  build/setup.mk
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 4: Reviews Complete

#438 MM-32130 Deleting tasks from an active incident.
  tests-e2e/cypress/integration/frontstage/incident_rhs_checklist_spec.js
  webapp/src/components/checklist.scss
  webapp/src/components/checklist_item.tsx
Labels: 4: Reviews Complete

#439 MM-32129 Modify assign tasks location.
  webapp/src/components/checklist.scss
  webapp/src/components/checklist_item.tsx
  webapp/src/components/profile/profile.tsx
  webapp/src/components/profile/profile_selector.scss
  webapp/src/components/profile/profile_selector.tsx
Labels: 4: Reviews Complete

#443 MM-32431 - Fix local e2e tests
  server/command/command.go
  tests-e2e/cypress/integration/backstage/incident_list_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/footer_spec.js
  tests-e2e/cypress/support/server_api_commands.js
  tests-e2e/cypress/support/ui_commands.js
Labels: 4: Reviews Complete
