Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2021-03, with the labels that each got.

#484 MM-33335 Use CurrentStatus as source of truth.
  server/incident/incident.go
  server/incident/incident_test.go
  server/incident/service.go
  server/sqlstore/incident.go
  server/sqlstore/incident_test.go
  server/telemetry/rudder.go
  server/telemetry/rudder_test.go
  webapp/src/types/incident.ts
Labels: 4: Reviews Complete

#466 Use filterOption in ProfileAutocomplete
  webapp/src/components/backstage/profile_autocomplete.tsx
Labels: 4: Reviews Complete

#482 Remove dead code
  webapp/src/components/checklist_item.tsx
Labels: 4: Reviews Complete

#357 MM-26942 Incidents Service
  client/client.go
  client/client_test.go
  client/doc.go
  client/doc_test.go
  client/error_response.go
  client/go.mod
  client/go.sum
  client/incident.go
  client/incidents.go
  client/incidents_checklist_items.go
  client/incidents_checklists.go
  client/incidents_test.go
  client/playbook.go
  client/playbooks.go
  client/sort.go
  client/unexport_test.go
  go.mod
  go.sum
  server/api/api.yaml
  server/api/api_test.go
  server/api/incidents.go
  server/api/incidents_test.go
  server/incident/filter_options.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#485 MM-32113: Fix banner width
  webapp/src/components/backstage/incidents/incident_details/export_link.tsx
  webapp/src/components/backstage/incidents/incident_details/incident_details.tsx
  webapp/src/components/backstage/playbook.scss
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/backstage/shared.tsx
Labels: 4: Reviews Complete

#486 MM-33439: Fetch invited users independently
  webapp/src/components/backstage/automation/invite_users_selector.tsx
Labels: 4: Reviews Complete

#469 MM-32387: activate but functionally disable without license
  go.mod
  go.sum
  plugin.json
  server/api/api.go
  server/api/api_test.go
  server/api/incidents_test.go
  server/api/playbooks_test.go
  server/command/command.go
  server/config/config.go
  server/config/mocks/mock_service.go
  server/config/service.go
  server/plugin.go
  server/sqlstore/store.go
  server/sqlstore/store_test.go
  server/sqlstore/support_for_test.go
  webapp/src/index.tsx
  webapp/src/license.ts
  webapp/src/registry_wrapper.tsx
Labels: 4: Reviews Complete

#488 MM-33310 "Message" in status update modal accepts empty character string
  server/api/incidents.go
  tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/header_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/latest_update_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/open_spec.js
  tests-e2e/cypress/support/index.js
Labels: 4: Reviews Complete

#480 MM-31913 Fix assignee dropdown
  tests-e2e/cypress/integration/backstage/incident_list_spec.js
  tests-e2e/cypress/integration/frontstage/incident_rhs_checklist_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/footer_spec.js
  tests-e2e/cypress/support/index.js
  tests-e2e/cypress/support/test_commands.js
  webapp/src/components/backstage/incidents/incident_list/incident_list.tsx
  webapp/src/components/profile/profile_selector.tsx
  webapp/src/hooks.ts
Labels: 4: Reviews Complete

#483 MM-31561: Commander automation
  go.sum
  server/api/incidents.go
  server/api/playbooks.go
  server/command/command.go
  server/incident/incident.go
  server/incident/mocks/mock_service.go
  server/incident/mocks/mock_store.go
  server/incident/service.go
  server/incident/service_test.go
  server/permissions/permissions.go
  server/playbook/playbook.go
  server/playbook/playbook_test.go
  server/sqlstore/incident.go
  server/sqlstore/incident_test.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook.go
  tests-e2e/cypress/integration/backstage/playbook_details_spec.js
  tests-e2e/cypress/integration/frontstage/incident_automation_spec.js
  tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js
  tests-e2e/cypress/support/plugin_api_commands.js
  tests-e2e/cypress/support/plugin_ui_commands.js
  webapp/src/client.ts
  webapp/src/components/backstage/automation/assign_commander_selector.tsx
  webapp/src/components/backstage/automation/auto_assign_commander.tsx
  webapp/src/components/backstage/automation/settings.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/profile/profile_selector.tsx
  webapp/src/types/playbook.ts
Labels: 4: Reviews Complete, Docs/Needed

#490 MM-29101 - Fix for Calling Users endpoint too often
  webapp/src/client.ts
  webapp/src/components/checklist_item.tsx
  webapp/src/components/rhs/rhs_incident_summary.tsx
  webapp/src/constants.ts
  webapp/src/hooks.ts
Labels: 4: Reviews Complete

#492 Fix master
  go.sum
Labels: 4: Reviews Complete

#491 Bring back IR_Incident's CreateAt and DeleteAt fields
  server/sqlstore/incident.go
  server/sqlstore/incident_test.go
  server/sqlstore/migrations.go
  server/sqlstore/store_test.go
  server/sqlstore/support_for_test.go
Labels: 4: Reviews Complete

#496 MM-33817 Javascript error when deleting a timeline event
  server/api/incidents.go
  webapp/src/client.ts
Labels: 4: Reviews Complete

#493 MM-33512 Create the updateStatus API endpoint
  client/client.go
  client/error_response.go
  client/go.mod
  client/go.sum
  client/incident.go
  client/incidents.go
  client/incidents_test.go
  client/sort.go
  go.sum
  server/api/api.yaml
  server/api/incidents.go
  server/api/incidents_test.go
  server/incident/incident.go
Labels: 4: Reviews Complete

#474 MM-30878 Change format of dates that are not this year
  webapp/src/components/backstage/incidents/incident_list/incident_list.tsx
Labels: 4: Reviews Complete

#498 MM-33790: Fix the reporter in the RHS is clickable but does nothing
  webapp/src/components/rhs/incident_details.scss
  webapp/src/components/rhs/rhs_incident_summary.tsx
  webapp/src/components/rhs/rhs_list_incident.tsx
  webapp/src/components/rhs/rhs_shared.tsx
Labels: 4: Reviews Complete

#497 MM-33731: Fix for Incidents can be created without a name
  server/api/incidents.go
  server/api/incidents_test.go
Labels: 4: Reviews Complete

#494 MM-33309 - Update confirm modal text
  webapp/src/components/checklist_item.tsx
  webapp/src/components/rhs/rhs_timeline_event_item.tsx
Labels: 4: Reviews Complete

#487 MM-32546 - Filtering events
  tests-e2e/cypress/integration/frontstage/rhs/timeline-spec.js
  webapp/src/actions.ts
  webapp/src/components/checklist_item.tsx
  webapp/src/components/dot_menu.tsx
  webapp/src/components/multi_checkbox.tsx
  webapp/src/components/rhs/rhs_timeline.tsx
  webapp/src/components/rhs/rhs_timeline_event_item.tsx
  webapp/src/reducer.ts
  webapp/src/selectors.ts
  webapp/src/types/actions.ts
  webapp/src/types/rhs.ts
Labels: 4: Reviews Complete

#500 MM-34207: css issue with RHS timeline
  webapp/src/components/rhs/rhs_timeline.tsx
Labels: 2: Dev Review

#495 MM-31562: Incident creation announcement
  server/api/incidents.go
  server/api/playbooks.go
  server/incident/incident.go
  server/incident/service.go
  server/permissions/permissions.go
  server/playbook/playbook.go
  server/playbook/playbook_test.go
  server/sqlstore/incident.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook.go
  tests-e2e/cypress/integration/backstage/playbook_details_spec.js
  tests-e2e/cypress/integration/frontstage/incident_automation_spec.js
  tests-e2e/cypress/support/plugin_api_commands.js
  tests-e2e/cypress/support/plugin_ui_commands.js
  tests-e2e/cypress/support/server_api_commands.js
  webapp/src/components/backstage/automation/announcement.tsx
  webapp/src/components/backstage/automation/auto_assign_commander.tsx
  webapp/src/components/backstage/automation/invite_users.tsx
  webapp/src/components/backstage/automation/settings.tsx
  webapp/src/components/backstage/automation/styles.tsx
  webapp/src/components/backstage/channel_selector.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/types/playbook.ts
Labels: 1. Editor Review, 3: QA Review, Docs/Done

#505 golangci: disable fieldalignment
  .golangci.yml
Labels: 4: Reviews Complete

#502 MM-33855 Ad-hoc Tasks
  server/api/incidents.go
  server/command/command.go
  server/incident/incident.go
  server/incident/mocks/mock_service.go
  server/incident/service.go
  tests-e2e/cypress/integration/frontstage/incident_rhs_checklist_spec.js
  tests-e2e/cypress/support/plugin_ui_commands.js
  webapp/package-lock.json
  webapp/src/actions.ts
  webapp/src/client.ts
  webapp/src/components/assets/buttons.tsx
  webapp/src/components/assets/inputs.tsx
  webapp/src/components/backstage/step_edit.tsx
  webapp/src/components/backstage/styles.tsx
  webapp/src/components/checklist_item.tsx
  webapp/src/components/checklist_item_input.tsx
  webapp/src/components/command_input.tsx
  webapp/src/components/rhs/rhs_incident_tasks.tsx
  webapp/src/components/rhs/rhs_shared.tsx
  webapp/src/components/widgets/generic_modal.tsx
Labels: 4: Reviews Complete

#489 MM-33408 Basic Stats View
  server/api/stats.go
  server/plugin.go
  server/sqlstore/stats.go
  server/sqlstore/stats_test.go
  tests-e2e/cypress/integration/backstage/backstage_spec.js
  tests-e2e/cypress/integration/backstage/playbook_creation_spec.js
  tests-e2e/cypress/support/plugin_ui_commands.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/client.ts
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/incidents/incident_list/incident_list.tsx
  webapp/src/components/backstage/stats.tsx
  webapp/src/index.tsx
  webapp/src/types/stats.ts
Labels: 4: Reviews Complete
