Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2021-11, with the labels that each got.

#840 MM-39090: Telemetry on preview page (and tiny refactor)
  webapp/src/components/backstage/playbooks/playbook.tsx
  webapp/src/components/backstage/playbooks/playbook_preview.tsx
  webapp/src/components/backstage/playbooks/playbook_preview_navbar.tsx
Labels: 4: Reviews Complete

#843 [MM-39570] Fix number of webhooks check
  webapp/src/components/backstage/automation/patterned_text_area.tsx
Labels: 4: Reviews Complete

#849 Migrate FormattedDuration from Moment to Luxon and remove moment dependency
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/formatted_duration.test.tsx
  webapp/src/components/formatted_duration.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#801 [MM-39252] Add followers to the playbook run
  client/playbook_run.go
  server/api/playbook_runs.go
  server/app/mocks/mock_playbook_run_service.go
  server/app/mocks/mock_playbook_run_store.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/app/playbook_run_service_test.go
  server/sqlstore/migrations.go
  server/sqlstore/mockmocks/mock_storeapi.go
  server/sqlstore/playbook_run.go
  webapp/i18n/en.json
  webapp/src/client.ts
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/followers.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_details/export_link.tsx
  webapp/src/types/playbook_run.ts
Labels: 4: Reviews Complete

#847 MM-39086: Remove experimental feature flag in playbook preview
  webapp/src/components/backstage/playbooks/playbook.tsx
Labels: 4: Reviews Complete

#857 [MM-38151] Lock translations to `en`, just for 1.21
  webapp/src/index.tsx
Labels: 4: Reviews Complete

#842 MM-31698: dynamic test data for e2e tests
  .circleci/config.yml
  tests-e2e/.eslintrc
  tests-e2e/cypress.json
  tests-e2e/cypress/fixtures/users.json
  tests-e2e/cypress/integration/backstage/backstage_spec.js
  tests-e2e/cypress/integration/backstage/playbook_creation_spec.js
  tests-e2e/cypress/integration/backstage/playbook_edit_spec.js
  tests-e2e/cypress/integration/backstage/playbook_list_permissions_spec.js
  tests-e2e/cypress/integration/backstage/playbook_list_spec.js
  tests-e2e/cypress/integration/backstage/playbook_overview_spec.js
  tests-e2e/cypress/integration/backstage/playbook_retro_timeline_spec.js
  tests-e2e/cypress/integration/backstage/playbook_run_list_spec.js
  tests-e2e/cypress/integration/frontstage/channel_header_spec.js
  tests-e2e/cypress/integration/frontstage/playbook_run_automation_spec.js
  tests-e2e/cypress/integration/frontstage/playbook_run_broadcast_spec.js
  tests-e2e/cypress/integration/frontstage/playbook_run_creation_spec.js
  tests-e2e/cypress/integration/frontstage/playbook_run_dialog_spec.js
  tests-e2e/cypress/integration/frontstage/playbook_run_rhs_checklist_spec.js
  tests-e2e/cypress/integration/frontstage/playbook_run_rhs_list_spec_dep.js
  tests-e2e/cypress/integration/frontstage/rhs/header_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/home_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/open_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/status_update_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/timeline-spec.js
  tests-e2e/cypress/integration/frontstage/rhs/welcome_spec_dep.js
  tests-e2e/cypress/integration/frontstage/slash_command/info_spec.js
  tests-e2e/cypress/integration/frontstage/slash_command/owner_spec.js
  tests-e2e/cypress/integration/frontstage/slash_command/test_spec.js
  tests-e2e/cypress/integration/frontstage/slash_command/todo_spec.js
  tests-e2e/cypress/plugins/db_request.js
  tests-e2e/cypress/plugins/index.js
  tests-e2e/cypress/support/api/common.js
  tests-e2e/cypress/support/api/keycloak.js
  tests-e2e/cypress/support/api/preference.js
  tests-e2e/cypress/support/api/system.js
  tests-e2e/cypress/support/index.js
  tests-e2e/cypress/support/legacy_api_commands.js
  tests-e2e/cypress/support/storybook_commands.js
  tests-e2e/cypress/support/task_commands.js
  tests-e2e/cypress/support/ui/channel.js
  tests-e2e/cypress/support/ui/channel_sidebar.js
  tests-e2e/cypress/support/ui/team.js
  tests-e2e/utils/artifacts.js
  tests-e2e/utils/dashboard.js
  tests-e2e/utils/file.js
  tests-e2e/utils/report.js
  tests-e2e/utils/test_cases.js
Labels: 2: Dev Review

#856 MM-38841: fix retro timeline dates
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline_event_item.tsx
Labels: 4: Reviews Complete

#851 MM-38720: Remove export channel action
  client/playbook.go
  client/playbook_run.go
  server/api/playbook_runs.go
  server/app/playbook.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_run.go
  webapp/i18n/en.json
  webapp/src/components/backstage/automation/export_channel_on_archive.tsx
  webapp/src/components/backstage/automation/settings.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/playbooks/playbook_preview_actions.tsx
  webapp/src/types/playbook.ts
Labels: 4: Reviews Complete

#863 MM-39465: API fix
  server/api/bot.go
  server/api/bot_test.go
  server/app/permissions.go
Labels: 4: Reviews Complete

#841 [MM-39652] Fix missing suggestion when CRT is on
  server/app/playbook_service.go
Labels: 4: Reviews Complete

#850 Add useRelative with playbooks
  webapp/src/components/rhs/post_card.tsx
Labels: 2: Dev Review

#865 [MM-39255] Make all participants followers by default
  server/app/playbook_run_service.go
  server/app/playbook_run_service_test.go
  server/plugin.go
Labels: 4: Reviews Complete

#859 Reorganize E2E Tests
  tests-e2e/cypress/integration/channels/actions_spec.js
  tests-e2e/cypress/integration/channels/broadcast_spec.js
  tests-e2e/cypress/integration/channels/channel_header_spec.js
  tests-e2e/cypress/integration/channels/rhs/checklist_spec.js
  tests-e2e/cypress/integration/channels/rhs/header_spec.js
  tests-e2e/cypress/integration/channels/rhs/home_spec.js
  tests-e2e/cypress/integration/channels/rhs/status_update_spec.js
  tests-e2e/cypress/integration/channels/rhs_spec.js
  tests-e2e/cypress/integration/channels/run_dialog_spec.js
  tests-e2e/cypress/integration/channels/run_spec.js
  tests-e2e/cypress/integration/channels/slash_command/info_spec.js
  tests-e2e/cypress/integration/channels/slash_command/owner_spec.js
  tests-e2e/cypress/integration/channels/slash_command/test_spec.js
  tests-e2e/cypress/integration/channels/slash_command/todo_spec.js
  tests-e2e/cypress/integration/navigation_spec.js
  tests-e2e/cypress/integration/playbooks/creation_button_spec.js
  tests-e2e/cypress/integration/playbooks/edit_spec.js
  tests-e2e/cypress/integration/playbooks/list_permissions_spec.js
  tests-e2e/cypress/integration/playbooks/list_spec.js
  tests-e2e/cypress/integration/playbooks/overview_spec.js
  tests-e2e/cypress/integration/runs/details_spec.js
  tests-e2e/cypress/integration/runs/list_spec.js
  tests-e2e/cypress/integration/runs/timeline_spec.js
  tests-e2e/cypress/support/plugin/ui_commands.js
Labels: 2: Dev Review

#844 MM-39285 - Support snoozing status update reminders
  server/api/playbook_runs.go
  server/app/mocks/mock_playbook_run_service.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/app/playbook_run_service_test.go
  server/app/reminder.go
  webapp/i18n/en.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/client.ts
  webapp/src/components/backstage/automation/assign_owner_selector.tsx
  webapp/src/components/backstage/automation/broadcast.tsx
  webapp/src/components/backstage/automation/input_keywords.tsx
  webapp/src/components/backstage/automation/invite_users_selector.tsx
  webapp/src/components/backstage/channel_selector.tsx
  webapp/src/components/backstage/profile_autocomplete.tsx
  webapp/src/components/backstage/runs_list/filters.tsx
  webapp/src/components/checklist_item.tsx
  webapp/src/components/modals/update_run_status_modal.tsx
  webapp/src/components/profile/profile_selector.tsx
  webapp/src/components/team/create_playbook_team_selector.tsx
  webapp/src/components/team/team_selector.tsx
  webapp/src/components/update_request_post.tsx
Labels: 4: Reviews Complete

#868 Apple Silicon / M1 ARM improvements
  .nvmrc
  Makefile
  plugin.json
  webapp/package-lock.json
  webapp/package.json
  webapp/skip_integrity_check.js
Labels: 2: Dev Review

#866 New go e2e style tests
  client/playbooks.go
  go.mod
  go.sum
  server/api/playbook_runs_test.go
  server/api_playbooks_test.go
  server/api_runs_test.go
  server/api_settings_test.go
  server/main_test.go
  server/sqlstore/support_for_test.go
  server/sqlstore/user_info_test.go
Labels: 2: Dev Review

#869 [MM-39908] Fix nil reference bug
  server/plugin.go
Labels: 4: Reviews Complete

#860 MM-39501: Close existing RHS when running playbook
  server/api/playbook_runs.go
  tests-e2e/cypress/integration/channels/rhs_spec.js
  webapp/src/actions.ts
  webapp/src/browser_routing.ts
  webapp/src/reducer.ts
  webapp/src/rhs_opener.ts
  webapp/src/websocket_events.ts
Labels: 2: Dev Review

#861 MM-39171: Force RHS open when clicking from Todo list
  server/app/playbook_run_service.go
  tests-e2e/cypress/integration/channels/rhs_spec.js
Labels: 4: Reviews Complete

#829 MM-39126 Use natural lang for default update time
  webapp/i18n/en.json
  webapp/src/components/backstage/default_update_timer.tsx
  webapp/src/components/datetime_input.tsx
Labels: Hacktoberfest, hacktoberfest-accepted

#858 MM-39145: Add description to playbook
  server/api/playbook_runs.go
  server/api/playbook_runs_test.go
  server/app/playbook.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_run.go
  server/sqlstore/playbook_run_test.go
  server/sqlstore/store_test.go
  server/sqlstore/support_for_test.go
  server/telemetry/rudder.go
  server/telemetry/rudder_test.go
  tests-e2e/cypress/integration/playbooks/creation_button_spec.js
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/playbook_edit_title_description_modal.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/description.tsx
  webapp/src/components/backstage/playbooks/playbook.tsx
  webapp/src/components/backstage/playbooks/playbook_preview.tsx
  webapp/src/components/backstage/playbooks/playbook_preview_description.tsx
  webapp/src/components/backstage/playbooks/playbook_preview_navbar.tsx
  webapp/src/components/backstage/template_selector.tsx
  webapp/src/components/rhs/rhs_about.tsx
  webapp/src/components/rhs/rhs_about_description.tsx
  webapp/src/components/widgets/generic_modal.tsx
  webapp/src/types/playbook.ts
  webapp/src/types/playbook_run.ts
Labels: 4: Reviews Complete

#872 MM-39938: react-select theming, support portaling
  tests-e2e/cypress/integration/playbooks/edit_spec.js
  tests-e2e/cypress/support/plugin/ui_commands.js
  webapp/src/components/backstage/automation/broadcast.tsx
  webapp/src/components/backstage/channel_selector.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/styles.tsx
  webapp/src/components/datetime_input.tsx
  webapp/src/components/update_request_post.tsx
  webapp/src/index.tsx
Labels: 4: Reviews Complete

#846 Add restore endpoint to unfinish Playbook Run
  server/api/playbook_runs.go
  server/app/mocks/mock_playbook_run_service.go
  server/app/mocks/mock_playbook_run_store.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/app/playbook_run_service_test.go
  server/sqlstore/playbook_run.go
  server/sqlstore/playbook_run_test.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
  server/telemetry/rudder_test.go
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline_event_item.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline_retro.tsx
  webapp/src/types/rhs.ts
Labels: 4: Reviews Complete, AutoMerge, Hacktoberfest, hacktoberfest-accepted

#874 MM-39939: Hide enabled actions that have no actual content
  webapp/src/components/backstage/playbooks/playbook_preview_actions.tsx
  webapp/src/components/backstage/playbooks/playbook_preview_checklists.tsx
  webapp/src/components/backstage/playbooks/playbook_preview_status_updates.tsx
Labels: 4: Reviews Complete

#854 MM-39165: Make "Go to channel" more prominent
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/followers.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_details/export_link.tsx
  webapp/src/components/backstage/playbook_runs/shared.tsx
Labels: 1: UX Review, 2: Dev Review

#880 MM-40048: Fix ordered lists rendering in playbook preview
  webapp/src/components/checklist_item.tsx
Labels: 4: Reviews Complete

#877 [MM-39933]:On click sort numeric playbook columns in descending order
  webapp/src/hooks/crud.ts
Labels: 2: Dev Review

#879 MM-38593: Improve semantics for archived playbooks
  client/playbooks.go
  server/api/playbook_runs.go
  server/api/playbook_runs_test.go
  server/api/playbooks.go
  server/api/playbooks_test.go
  server/api_playbooks_test.go
  server/app/mocks/mock_playbook_service.go
  server/app/mocks/mock_playbook_store.go
  server/app/playbook.go
  server/app/playbook_service.go
  server/command/command.go
  server/main_test.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_test.go
  tests-e2e/cypress/integration/channels/rhs_spec.js
  tests-e2e/cypress/integration/playbooks/overview_spec.js
  tests-e2e/cypress/support/plugin/api_commands.js
  webapp/i18n/en.json
  webapp/src/actions.ts
  webapp/src/client.ts
  webapp/src/components/assets/buttons.tsx
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/backstage/playbook_list_row.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
  webapp/src/components/backstage/playbook_runs/shared.tsx
  webapp/src/components/backstage/playbooks/playbook.tsx
  webapp/src/components/backstage/playbooks/playbook_preview.tsx
  webapp/src/components/backstage/playbooks/playbook_preview_navbar.tsx
  webapp/src/components/backstage/runs_list/row.tsx
  webapp/src/components/backstage/status_badge.tsx
  webapp/src/components/rhs/rhs_about_title.tsx
  webapp/src/components/rhs/rhs_list_playbook_run.tsx
  webapp/src/hooks/crud.ts
  webapp/src/index.tsx
  webapp/src/reducer.ts
  webapp/src/types/actions.ts
  webapp/src/types/websocket_events.ts
  webapp/src/websocket_events.ts
Labels: 4: Reviews Complete

#870 [MM-39857] Add auto-follow playbook runs
  server/api/playbooks.go
  server/app/mocks/mock_playbook_service.go
  server/app/mocks/mock_playbook_store.go
  server/app/playbook.go
  server/app/playbook_run_service.go
  server/app/playbook_service.go
  server/data/users/353ds3j4u3yt3njhb6d1p93kia/profile.png
  server/data/users/bmxt33gb8tr7dnd1eth71r7saa/profile.png
  server/data/users/qfrqoc691tdsbqmccbdmrqsp1y/profile.png
  server/data/users/y63dn1bjtiynt8x4zk5xcz3ine/profile.png
  server/sqlstore/migrations.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_run.go
  webapp/i18n/en.json
  webapp/src/client.ts
  webapp/src/components/backstage/playbooks/playbook.tsx
  webapp/src/components/backstage/runs_list/checkbox_input.tsx
Labels: 2: Dev Review

#875 [MM-39772] Use relative URLs in the channel header
  server/app/playbook_run_service.go
  server/app/playbook_service.go
  server/app/urls.go
  server/app/urls_test.go
  tests-e2e/cypress/integration/channels/channel_header_spec.js
Labels: 4: Reviews Complete

#878 Accommodate long and multiple keywords
  webapp/i18n/en.json
  webapp/src/components/backstage/playbooks/playbook_preview_actions.tsx
  webapp/src/components/backstage/playbooks/playbook_preview_badges.tsx
Labels: 4: Reviews Complete

#884 [MM-39897] test spec for run retrospective
  tests-e2e/cypress/integration/runs/retrospective_spec.js
  tests-e2e/cypress/support/plugin/api_commands.js
Labels: 4: Reviews Complete

#887 [MM-35201] Set `disabled` attribute on settings inputs
  webapp/src/components/backstage/automation/patterned_input.tsx
  webapp/src/components/backstage/automation/patterned_text_area.tsx
Labels: 4: Reviews Complete

#862 [MM-38586] Skip instead of delete playbook run tasks
  server/api/playbook_runs.go
  server/app/mocks/mock_playbook_run_service.go
  server/app/playbook.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
  tests-e2e/cypress/integration/channels/rhs/checklist_spec.js
  webapp/i18n/en.json
  webapp/src/client.ts
  webapp/src/components/backstage/runs_list/row.tsx
  webapp/src/components/checklist_item.tsx
  webapp/src/components/collapsible_checklist.tsx
  webapp/src/types/playbook.ts
Labels: 4: Reviews Complete

#891 Ignore test-generated data
  .gitignore
  server/data/users/353ds3j4u3yt3njhb6d1p93kia/profile.png
  server/data/users/bmxt33gb8tr7dnd1eth71r7saa/profile.png
  server/data/users/qfrqoc691tdsbqmccbdmrqsp1y/profile.png
  server/data/users/y63dn1bjtiynt8x4zk5xcz3ine/profile.png
Labels: 4: Reviews Complete

#890 MM-39364: Inline task description in RHS
  webapp/i18n/en.json
  webapp/src/components/backstage/playbooks/playbook_preview_checklists.tsx
  webapp/src/components/checklist_item.tsx
  webapp/src/components/rhs/rhs_checklists.tsx
  webapp/src/components/rhs/rhs_shared.tsx
Labels: 1: UX Review, 2: Dev Review

#888 [MM-40133] Add support for default notifications for followers
  server/app/playbook_run_service.go
  server/app/reminder.go
Labels: 2: Dev Review

#882 [MM-39849] Add followers to my runs filter
  client/playbook_run.go
  server/api/playbook_runs.go
  server/app/playbook_run.go
  server/sqlstore/playbook_run.go
  tests-e2e/cypress/integration/playbooks/list_permissions_spec.js
  tests-e2e/cypress/integration/runs/list_spec.js
  webapp/src/components/backstage/playbooks/playbook_usage.tsx
  webapp/src/components/backstage/runs_list/checkbox_input.tsx
  webapp/src/components/backstage/runs_list/filters.tsx
  webapp/src/components/backstage/runs_list/runs_list.tsx
  webapp/src/components/backstage/runs_list/search_input.tsx
  webapp/src/components/backstage/runs_page.tsx
  webapp/src/types/playbook_run.ts
Labels: 4: Reviews Complete

#814 [MM-38575] Import luxon as external dependency from mattermost-webapp, bump min version
  plugin.json
  webapp/webpack.config.js
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#885 MM-38298: Support Playbook search
  client/playbook.go
  server/api/playbooks.go
  server/api_playbooks_test.go
  server/app/playbook.go
  server/main_test.go
  server/sqlstore/playbook.go
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/backstage/playbook_runs/shared.tsx
  webapp/src/components/backstage/runs_list/filters.tsx
  webapp/src/components/backstage/search_input.tsx
  webapp/src/hooks/crud.ts
  webapp/src/types/playbook.ts
Labels: 4: Reviews Complete

#893 Cypress default config & README updates
  README.md
  tests-e2e/cypress/support/api/on_prem_default_config.json
Labels: 4: Reviews Complete

#892 MM-38954: Scroll the RHS to top when the run is finished
  webapp/src/components/rhs/rhs_run_details.tsx
  webapp/src/hooks/general.ts
Labels: 4: Reviews Complete

#905 temporarily drop min version to 6.0
  plugin.json
Labels: 2: Dev Review

#897 MM-37531: Make subheaders in RHS sticky
  webapp/src/components/collapsible_checklist.tsx
  webapp/src/components/rhs/rhs_checklists.tsx
Labels: 4: Reviews Complete

#900 MM-40263: Stats are erroring when there are no runs for a playbook
  server/sqlstore/stats.go
  server/sqlstore/stats_test.go
Labels: 2: Dev Review

#906 MM-40335: Fix for: z-index for owner dropdown is off
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline_event_item.tsx
  webapp/src/components/profile/profile_selector.scss
  webapp/src/components/rhs/rhs_shared.tsx
Labels: 4: Reviews Complete

#895 [MM-39140] Add copy URL to run and playbook
  tests-e2e/cypress/integration/playbooks/overview_spec.js
  tests-e2e/cypress/integration/runs/details_spec.js
  webapp/i18n/en.json
  webapp/src/client.ts
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
  webapp/src/components/backstage/playbooks/playbook.tsx
  webapp/src/utils.ts
Labels: 1: UX Review, 2: Dev Review

#904 Replace all CSS variables with opacity with rgba
  webapp/src/components/assets/buttons.tsx
  webapp/src/components/assets/no_content_playbooks_svg.tsx
  webapp/src/components/backstage/automation/assign_owner_selector.tsx
  webapp/src/components/backstage/automation/auto_assign_owner.tsx
  webapp/src/components/backstage/automation/broadcast.tsx
  webapp/src/components/backstage/automation/input_keywords.tsx
  webapp/src/components/backstage/automation/invite_users_selector.tsx
  webapp/src/components/backstage/automation/patterned_input.tsx
  webapp/src/components/backstage/automation/patterned_text_area.tsx
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/backstage_list_header.tsx
  webapp/src/components/backstage/backstage_navbar.tsx
  webapp/src/components/backstage/editable_text.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/backstage/playbook_list_row.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/report.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline_event_item.tsx
  webapp/src/components/backstage/playbook_runs/shared.tsx
  webapp/src/components/backstage/playbooks/playbook.tsx
  webapp/src/components/backstage/playbooks/playbook_preview_actions.tsx
  webapp/src/components/backstage/playbooks/stats_view.tsx
  webapp/src/components/backstage/profile_autocomplete.tsx
  webapp/src/components/backstage/runs_list/checkbox_input.tsx
  webapp/src/components/backstage/runs_list/pagination_row.tsx
  webapp/src/components/backstage/runs_list/row.tsx
  webapp/src/components/backstage/runs_list/run_list_header.tsx
  webapp/src/components/backstage/runs_list/runs_list.tsx
  webapp/src/components/backstage/search_input.tsx
  webapp/src/components/backstage/status_badge.tsx
  webapp/src/components/backstage/styles.tsx
  webapp/src/components/checklist_item.tsx
  webapp/src/components/collapsible_checklist.tsx
  webapp/src/components/dot_menu.tsx
  webapp/src/components/multi_checkbox.tsx
  webapp/src/components/multi_select.tsx
  webapp/src/components/pagination_row.tsx
  webapp/src/components/profile/profile.tsx
  webapp/src/components/profile/profile_button.tsx
  webapp/src/components/rhs/rhs_about.tsx
  webapp/src/components/rhs/rhs_checklists.tsx
  webapp/src/components/rhs/rhs_list_playbook_run.tsx
  webapp/src/components/rhs/rhs_list_view.tsx
  webapp/src/components/rhs/rhs_shared.tsx
  webapp/src/components/rhs/rhs_title.tsx
  webapp/src/components/tabs.tsx
  webapp/src/components/team/team_selector.tsx
  webapp/src/components/team/team_with_icon.tsx
  webapp/src/components/upgrade_banner.tsx
  webapp/src/components/widgets/pill.tsx
Labels: 4: Reviews Complete

#902 Action channel name template
  client/playbook_run.go
  server/api/playbooks.go
  server/api/playbooks_test.go
  server/api/urls.go
  server/app/permissions.go
  server/app/playbook.go
  server/app/playbook_run_service.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_test.go
  server/telemetry/rudder.go
  server/telemetry/rudder_test.go
  tests-e2e/cypress/integration/channels/actions_spec.js
  tests-e2e/cypress/integration/channels/rhs/home_spec.js
  tests-e2e/cypress/integration/playbooks/edit_spec.js
  tests-e2e/cypress/support/plugin/api_commands.js
  webapp/i18n/en.json
  webapp/src/components/backstage/automation/patterned_input.tsx
  webapp/src/components/backstage/automation/settings.tsx
  webapp/src/components/backstage/automation/toggle.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/playbooks/playbook_preview_actions.tsx
  webapp/src/components/rhs/rhs_home_item.tsx
  webapp/src/types/playbook.ts
Labels: 4: Reviews Complete

#883 [MM-39529] Adding an item in the run's RHS dropdown menu to edit a run summary
  tests-e2e/cypress/integration/channels/rhs/header_spec.js
  webapp/i18n/en.json
  webapp/src/components/dot_menu.tsx
  webapp/src/components/rhs/rhs_about.tsx
  webapp/src/components/rhs/rhs_about_buttons.tsx
  webapp/src/components/rhs/rhs_about_description.tsx
Labels: 4: Reviews Complete

#910 [MM-40357] Change followers to following
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/following.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
Labels: 4: Reviews Complete

#912 Improved run permissions specs
  tests-e2e/cypress/integration/playbooks/list_permissions_spec.js
  tests-e2e/cypress/integration/runs/permissions_spec.js
  tests-e2e/cypress/support/plugin/api_commands.js
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/participants.tsx
Labels: 1: PM Review, 2: Dev Review, 3: QA Review

#914 Revert "temporarily drop min version to 6.0 (#905)"
  plugin.json
Labels: 2: Dev Review

#901 MM-38736: Prompt before discarding unsaved retrospective
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/report.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/retrospective.tsx
Labels: 4: Reviews Complete
