Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2021-06, with the labels that each got.

#534 [MM-34647] Clearable fields in playbook automation
  webapp/src/components/assets/icons/clear_icon.tsx
  webapp/src/components/backstage/automation/announcement.tsx
  webapp/src/components/backstage/automation/assign_commander_selector.tsx
  webapp/src/components/backstage/channel_selector.tsx
  webapp/src/components/backstage/playbook_edit.tsx
Labels: 4: Reviews Complete

#566 MM-35046 MM-35043 Reminders to fill in the retrospective
  server/api/incidents.go
  server/incident/incident.go
  server/incident/mocks/mock_service.go
  server/incident/reminder.go
  server/incident/service.go
  server/playbook/playbook.go
  server/playbook/playbook_test.go
  server/sqlstore/incident.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook.go
  webapp/src/components/backstage/incidents/incident_backstage/retrospective/report.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/rhs/rhs_timeline_event_item.tsx
  webapp/src/types/incident.ts
  webapp/src/types/playbook.ts
  webapp/src/types/rhs.ts
Labels: 2: Dev Review

#568 MM-35045 Template retrospective report
  server/api/incidents.go
  server/playbook/playbook.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook.go
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/types/playbook.ts
Labels: 4: Reviews Complete

#578 MM-36122: delay e0/e10 release
  webapp/src/index.tsx
  webapp/src/make_update_main_menu.ts
Labels: 2: Dev Review

#580 Add hot module loading.
  Makefile
  webapp/babel.config.js
  webapp/package-lock.json
  webapp/package.json
  webapp/webpack.config.js
Labels: 2: Dev Review

#542 MM32419: Auto send outgoing webhook on status update
  server/api/api.yaml
  server/api/incidents.go
  server/api/playbooks.go
  server/incident/incident.go
  server/incident/service.go
  server/incident/service_test.go
  server/playbook/playbook.go
  server/playbook/playbook_test.go
  server/sqlstore/incident.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook.go
  tests-e2e/cypress/support/plugin_api_commands.js
  webapp/package-lock.json
  webapp/src/components/backstage/automation/settings.tsx
  webapp/src/components/backstage/automation/webhook.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/types/playbook.ts
Labels: 4: Reviews Complete

#581 MM-35695 - First pass at new playbook landing page
  client/go.sum
  client/incident.go
  server/api/incidents.go
  server/api/stats.go
  server/incident/filter_options.go
  server/plugin.go
  server/sqlstore/incident.go
  server/sqlstore/incident_test.go
  server/sqlstore/stats.go
  server/sqlstore/stats_test.go
  tests-e2e/cypress/integration/backstage/playbook_details_spec.js
  webapp/package-lock.json
  webapp/src/client.ts
  webapp/src/components/assets/icons/clipboards_checkmark.tsx
  webapp/src/components/assets/icons/clipboards_play.tsx
  webapp/src/components/assets/icons/icon.tsx
  webapp/src/components/assets/icons/profiles.tsx
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/playbooks/bar_graph.tsx
  webapp/src/components/backstage/playbooks/incident_list/incident_list.tsx
  webapp/src/components/backstage/playbooks/line_graph.tsx
  webapp/src/components/backstage/playbooks/playbook_backstage.tsx
  webapp/src/types/incident.ts
  webapp/src/types/stats.ts
Labels: 4: Reviews Complete

#585 Fix timeline command.
  server/command/command.go
Labels: 2: Dev Review

#586 golangci: disable unusedwrite
  .golangci.yml
Labels: 2: Dev Review

#583 MM-36263 Fix to show as much of retrospective as possible.
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/incidents/incident_backstage/incident_backstage.tsx
  webapp/src/components/backstage/incidents/incident_backstage/retrospective/report.tsx
  webapp/src/components/backstage/incidents/shared.tsx
Labels: 2: Dev Review

#589 MM-36349 - Save playbook triggers "discard changes" dialog
  webapp/src/components/backstage/playbook_edit.tsx
Labels: 4: Reviews Complete

#569 [MM-35825] Message on every keyword
  server/api/playbooks.go
  server/api/playbooks_test.go
  server/playbook/keywords_cache.go
  server/playbook/mocks/mock_service.go
  server/playbook/mocks/mock_store.go
  server/playbook/playbook.go
  server/playbook/playbook_test.go
  server/playbook/service.go
  server/playbook/service_test.go
  server/plugin.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_test.go
  server/sqlstore/store_test.go
  tests-e2e/cypress/support/plugin_api_commands.js
  webapp/src/components/backstage/automation/patterned_input.tsx
  webapp/src/components/backstage/automation/settings.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/types/playbook.ts
Labels: 4: Reviews Complete

#590 MM-36359 - Fix backstage stats not working on MySql
  server/plugin.go
  server/sqlstore/stats.go
Labels: 2: Dev Review

#591 Removed unused member_only
  client/playbook.go
  server/api/api.yaml
  server/api/playbooks.go
  server/api/playbooks_test.go
  server/command/command.go
  server/playbook/playbook.go
  server/sqlstore/playbook_test.go
  webapp/src/client.ts
  webapp/src/types/incident.ts
Labels: 4: Reviews Complete

#587 s/commander/owner/
  client/incident.go
  client/playbook.go
  server/api/api.yaml
  server/api/incidents.go
  server/api/incidents_test.go
  server/api/playbooks.go
  server/command/command.go
  server/incident/filter_options.go
  server/incident/incident.go
  server/incident/mocks/mock_service.go
  server/incident/mocks/mock_store.go
  server/incident/reminder.go
  server/incident/schema.json
  server/incident/service.go
  server/incident/service_test.go
  server/playbook/playbook.go
  server/sqlstore/incident.go
  server/sqlstore/incident_test.go
  server/sqlstore/playbook.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
  server/telemetry/rudder_test.go
  tests-e2e/cypress/integration/backstage/backstage_spec.js
  tests-e2e/cypress/integration/backstage/incident_list_spec.js
  tests-e2e/cypress/integration/backstage/playbook_details_spec.js
  tests-e2e/cypress/integration/frontstage/incident_automation_spec.js
  tests-e2e/cypress/integration/frontstage/incident_broadcast_spec.js
  tests-e2e/cypress/integration/frontstage/incident_dialog_spec.js
  tests-e2e/cypress/integration/frontstage/incident_rhs_checklist_spec.js
  tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/footer_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/header_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/latest_update_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/open_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/timeline-spec.js
  tests-e2e/cypress/integration/frontstage/slash_command/info_spec.js
  tests-e2e/cypress/integration/frontstage/slash_command/owner_spec.js
  tests-e2e/cypress/support/plugin_api_commands.js
  tests-e2e/cypress/support/plugin_ui_commands.js
  webapp/src/client.ts
  webapp/src/components/backstage/automation/assign_owner_selector.tsx
  webapp/src/components/backstage/automation/auto_assign_owner.tsx
  webapp/src/components/backstage/automation/settings.tsx
  webapp/src/components/backstage/incidents/incident_backstage/overview/about.tsx
  webapp/src/components/backstage/incidents/incident_backstage/overview/participants.tsx
  webapp/src/components/backstage/incidents/incident_backstage/retrospective/followups.tsx
  webapp/src/components/backstage/incidents/incident_backstage/retrospective/learnings.tsx
  webapp/src/components/backstage/incidents/incident_backstage/retrospective/timeline_retro.tsx
  webapp/src/components/backstage/incidents/incident_list/incident_list.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/playbooks/incident_list/incident_list.tsx
  webapp/src/components/rhs/rhs_about.tsx
  webapp/src/components/rhs/rhs_list_incident.tsx
  webapp/src/components/rhs/rhs_timeline.tsx
  webapp/src/components/rhs/rhs_timeline_event_item.tsx
  webapp/src/types/backstage.ts
  webapp/src/types/incident.ts
  webapp/src/types/playbook.ts
  webapp/src/types/rhs.ts
Labels: 4: Reviews Complete

#593 s/UserIDtoIsAdmin/IsAdmin
  server/api/playbooks.go
  server/api/playbooks_test.go
  server/command/command.go
  server/playbook/playbook.go
  server/sqlstore/playbook_test.go
Labels: 2: Dev Review

#592 MM-35626: Adapt upgrade flow to Cloud
  server/bot/poster.go
  server/config/config.go
  server/config/mocks/mock_service.go
  webapp/src/components/assets/upgrade_illustration_svg.tsx
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/upgrade_modal.tsx
  webapp/src/components/backstage/upgrade_modal_data.tsx
  webapp/src/components/backstage/upgrade_modal_footer.tsx
  webapp/src/components/cloud_modal.tsx
  webapp/src/components/cloud_upgrade_post.tsx
  webapp/src/components/custom_post_styles.tsx
  webapp/src/components/post_text.tsx
  webapp/src/components/retrospective_reminder_posts.tsx
  webapp/src/components/rhs/rhs_timeline_placeholder.tsx
  webapp/src/hooks.ts
  webapp/src/index.tsx
  webapp/src/license.ts
Labels: 4: Reviews Complete

#584 MM-36262 Disable buttons on older or published retrospective reminders.
  webapp/src/components/assets/buttons.tsx
  webapp/src/components/retrospective_reminder_posts.tsx
Labels: 1: UX Review, 2: Dev Review

#600 MM-36474: Skip useOpenCloudModal creation if not in cloud
  webapp/src/hooks.ts
Labels: 2: Dev Review

#597 MM-36167: Use SKU short name with feature check as fallback
  webapp/src/license.test.ts
  webapp/src/license.ts
Labels: 4: Reviews Complete

#588 Add support of the post actions
  build/custom.mk
  server/api/signal.go
  server/bot/bot.go
  server/bot/mocks/mock_poster.go
  server/bot/poster.go
  server/incident/service.go
  server/playbook/keywords_ignore.go
  server/playbook/mocks/mock_keywords_ignorer.go
  server/playbook/mocks/mock_service.go
  server/playbook/playbook.go
  server/playbook/service.go
  server/playbook/service_test.go
  server/plugin.go
  server/telemetry/rudder.go
  server/telemetry/rudder_test.go
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/playbook_edit.tsx
Labels: 1: PM Review, 1: UX Review, 2: Dev Review

#604 Bump mattermost-plugin-api version
  go.mod
  go.sum
Labels: 2: Dev Review

#605 MM-36572 - Experimental features flag for new playbook dashboard
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/incidents/incident_backstage/incident_backstage.tsx
  webapp/src/components/backstage/playbook_edit.tsx
Labels: 4: Reviews Complete

#570 [MM-35059] Make /incident test bulk-data command create playbooks
  README.md
  server/command/command.go
Labels: 4: Reviews Complete

#601 MM-36243 - Playbook dashboard UI polish #1
  client/incident.go
  server/api/incidents.go
  server/api/stats.go
  server/app/incident.go
  server/app/incident_service.go
  server/app/sort.go
  server/sqlstore/incident.go
  server/sqlstore/migrations.go
  server/sqlstore/stats.go
  server/sqlstore/store_test.go
  server/sqlstore/support_for_test.go
  webapp/package-lock.json
  webapp/src/components/assets/icons/playbook_icon.tsx
  webapp/src/components/backstage/incidents/incident_backstage/incident_backstage.tsx
  webapp/src/components/backstage/playbooks/bar_graph.tsx
  webapp/src/components/backstage/playbooks/incident_list/incident_list.tsx
  webapp/src/components/backstage/playbooks/incident_list/progress_bar.tsx
  webapp/src/components/backstage/playbooks/incident_list/row.tsx
  webapp/src/components/backstage/playbooks/line_graph.tsx
  webapp/src/components/backstage/playbooks/playbook_backstage.tsx
  webapp/src/selectors.ts
  webapp/src/types/incident.ts
  webapp/src/types/stats.ts
  webapp/src/utils.ts
Labels: 2: Dev Review

#607 Update mattermost-plugin-api to use the DB RPC API
  go.mod
  go.sum
  server/api/api_test.go
  server/api/playbook_runs_test.go
  server/api/playbooks_test.go
  server/app/playbook_run_service_test.go
  server/app/service_test.go
  server/plugin.go
Labels: 2: Dev Review

#609 Upgrade to node 16 & npm 7
  .circleci/config.yml
  webapp/package-lock.json
  webapp/package.json
Labels: 4: Reviews Complete

#613 MM-36713: Make the plugin available for all users
  webapp/src/index.tsx
  webapp/src/make_update_main_menu.ts
Labels: 2: Dev Review

#616 MM-36689: Match export channel UX to all other restricted features
  server/api/telemetry.go
  server/bot/bot.go
  server/bot/poster.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
  webapp/src/components/backstage/playbook_runs/playbook_run_details/export_link.tsx
  webapp/src/components/backstage/upgrade_modal_data.tsx
  webapp/src/constants.ts
  webapp/src/hooks.ts
  webapp/src/selectors.ts
Labels: 2: Dev Review

#614 Require mattermost-server 5.37
  plugin.json
Labels: 4: Reviews Complete

#617 Adminify settings
  client/client.go
  client/settings.go
  server/api/api.go
  server/api/settings.go
  server/api/settings_test.go
  server/app/permissions.go
  server/plugin.go
  webapp/src/client.ts
  webapp/src/components/backstage/settings.tsx
  webapp/src/components/backstage/styles.tsx
  webapp/src/hooks.ts
Labels: 2: Dev Review

#610 MM-36244 - Generic upgrade banner/flow; Upgrade banner/flow for playbook dashboard
  .circleci/config.yml
  server/api/telemetry.go
  server/bot/bot.go
  server/bot/poster.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
  webapp/package-lock.json
  webapp/src/components/assets/buttons.tsx
  webapp/src/components/assets/error_svg.tsx
  webapp/src/components/assets/success_svg.tsx
  webapp/src/components/assets/upgrade_playbook_background_svg.tsx
  webapp/src/components/assets/upgrade_playbook_dashboard_svg.tsx
  webapp/src/components/assets/upgrade_playbook_error_svg.tsx
  webapp/src/components/assets/upgrade_playbook_success_svg.tsx
  webapp/src/components/assets/upgrade_timeline_background_svg.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/report.tsx
  webapp/src/components/backstage/playbook_runs/shared.tsx
  webapp/src/components/backstage/playbooks/playbook_backstage.tsx
  webapp/src/components/backstage/playbooks/stats_view.tsx
  webapp/src/components/backstage/playbooks/upgrade_playbook_placeholder.tsx
  webapp/src/components/rhs/rhs_timeline.tsx
  webapp/src/components/rhs/rhs_timeline_placeholder.tsx
  webapp/src/components/upgrade_banner.tsx
  webapp/src/constants.ts
  webapp/src/hooks.ts
Labels: 4: Reviews Complete

#621 MM-36707 - Remove experimental feature flag for Playbook Dashboard
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/playbook_edit.tsx
Labels: 2: Dev Review

#622 MM-36748: Add optional chaining to prevent undefined error
  webapp/src/components/retrospective_reminder_posts.tsx
Labels: 4: Reviews Complete

#611 MM-36168: Remove mentions to specific tiers
  server/app/permissions.go
  server/bot/poster.go
  webapp/src/components/backstage/convert_enterprise_notice.tsx
  webapp/src/components/backstage/upgrade_modal_data.tsx
Labels: 4: Reviews Complete

#618 MM-36264 Restrict to E10 and remove from behind experimantal feature flag.
  server/api/telemetry.go
  server/app/playbook_run_service.go
  server/bot/bot.go
  server/bot/poster.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
  webapp/src/components/assets/upgrade_playbook_background_svg.tsx
  webapp/src/components/assets/upgrade_retrospective_svg.tsx
  webapp/src/components/assets/upgrade_timeline_background_svg.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/retrospective.tsx
  webapp/src/constants.ts
  webapp/src/hooks.ts
Labels: 4: Reviews Complete

#619 Support prompting for feedback
  server/api/bot.go
  server/bot/bot.go
  server/bot/mocks/mock_poster.go
  server/bot/poster.go
  server/config/config.go
  server/config/mocks/mock_service.go
  server/config/service.go
  webapp/package-lock.json
  webapp/package.json
  webapp/src/client.ts
  webapp/src/components/backstage/backstage.tsx
Labels: 4: Reviews Complete

#620 MM-36540 - Improve graph searching & polish
  server/sqlstore/stats.go
  webapp/src/components/assets/icons/clear_icon.tsx
  webapp/src/components/backstage/playbooks/bar_graph.tsx
  webapp/src/components/backstage/playbooks/line_graph.tsx
  webapp/src/components/backstage/playbooks/playbook_backstage.tsx
  webapp/src/components/backstage/playbooks/playbook_run_list/playbook_run_list.tsx
  webapp/src/components/backstage/playbooks/stats_view.tsx
  webapp/src/components/widgets/pill.tsx
Labels: 4: Reviews Complete

#615 MM-36345 - Run directly from playbook dashboard
  server/api/telemetry.go
  server/app/playbook.go
  server/command/command.go
  server/plugin.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
  webapp/src/actions.ts
  webapp/src/client.ts
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_list/playbook_run_list.tsx
  webapp/src/components/backstage/playbooks/playbook_backstage.tsx
  webapp/src/components/widgets/pill.tsx
Labels: 4: Reviews Complete, AutoMerge
