Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2021-02, with the labels that each got.

#429 MM-31636 Add status field
  server/api/api.yaml
  server/api/incidents.go
  server/api/incidents_test.go
  server/command/command.go
  server/incident/filter_options.go
  server/incident/incident.go
  server/incident/incident_test.go
  server/incident/mocks/mock_service.go
  server/incident/mocks/mock_store.go
  server/incident/service.go
  server/incident/service_test.go
  server/sqlstore/incident.go
  server/sqlstore/incident_test.go
  server/sqlstore/migrations.go
  server/sqlstore/support_for_test.go
  server/telemetry/rudder.go
  server/telemetry/rudder_test.go
  tests-e2e/cypress/integration/backstage/incident_list_spec.js
  tests-e2e/cypress/integration/frontstage/incident_broadcast_spec.js
  tests-e2e/cypress/integration/frontstage/incident_creation_spec.js
  tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/header_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/latest_update_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/open_spec.js
  tests-e2e/cypress/integration/frontstage/slash_command/test_spec.js
  tests-e2e/cypress/support/index.js
  tests-e2e/cypress/support/plugin_api_commands.js
  tests-e2e/cypress/support/ui_commands.js
  webapp/src/components/backstage/incidents/incident_details/incident_details.tsx
  webapp/src/components/backstage/incidents/incident_list/incident_list.tsx
  webapp/src/components/backstage/incidents/incident_list/status_filter.tsx
  webapp/src/components/rhs/rhs_details_view.tsx
  webapp/src/components/rhs/rhs_footer.tsx
  webapp/src/components/rhs/rhs_incident_summary.tsx
  webapp/src/components/rhs/rhs_list_incident.tsx
  webapp/src/components/rhs/rhs_title.tsx
  webapp/src/selectors.ts
  webapp/src/types/incident.ts
  webapp/src/websocket_events.ts
Labels: 4: Reviews Complete

#441 Add telemetry on reminder and broadcast features
  server/telemetry/rudder.go
Labels: 2: Dev Review

#448 MM-32519 Fixing sorting on status.
  server/incident/filter_options.go
  webapp/src/components/backstage/incidents/incident_list/incident_list.tsx
Labels: 4: Reviews Complete

#450 MM-32544 - fix e2e
  .circleci/config.yml
  tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js
Labels: 2: Dev Review

#442 MM-32357 Telemetry for timeline tab
  server/api/incidents.go
  server/api/incidents_test.go
  server/incident/incident.go
  server/plugin.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
  webapp/src/client.ts
  webapp/src/components/rhs/rhs_tab_view.tsx
Labels: 4: Reviews Complete

#451 MM-32516: selectively align profile selector to right
  webapp/src/components/checklist_item.tsx
  webapp/src/components/profile/profile_selector.scss
  webapp/src/components/profile/profile_selector.tsx
Labels: 4: Reviews Complete

#445 MM-32246: fix welcome rhs as sysadmin
  server/api/api.yaml
  server/api/playbooks.go
  server/api/playbooks_test.go
  tests-e2e/cypress/integration/frontstage/rhs/welcome_spec.js
  webapp/src/client.ts
  webapp/src/types/incident.ts
Labels: 4: Reviews Complete

#454 Remove reference to contribution docs
  README.md
Labels: 1. Editor Review

#455 generate release_notes_url
  build/manifest/main.go
  plugin.json
Labels: 4: Reviews Complete

#453 Update README.md
  README.md
Labels: 4: Reviews Complete

#447 MM-32094 - Backend for Timeline v1 standard events and custom events
  server/api/incidents_test.go
  server/bot/bot.go
  server/bot/mocks/mock_poster.go
  server/bot/poster.go
  server/incident/incident.go
  server/incident/mocks/mock_store.go
  server/incident/reminder.go
  server/incident/service.go
  server/incident/service_test.go
  server/sqlstore/incident.go
  server/sqlstore/migrations.go
  server/sqlstore/timeline_event_test.go
Labels: 3: QA Review

#459 MM-32545: Timeline display all events; clean up design/wording
  server/incident/service.go
  tests-e2e/cypress/integration/frontstage/rhs/timeline-spec.js
  webapp/src/components/checklist_item.tsx
  webapp/src/components/rhs/rhs_timeline.tsx
  webapp/src/components/rhs/rhs_timeline_event_item.tsx
  webapp/src/components/shared.ts
  webapp/src/types/incident.ts
  webapp/src/types/rhs.ts
Labels: 4: Reviews Complete

#432 MM-31940 - RHS Timeline with status
  server/api/incidents.go
  server/api/incidents_test.go
  server/bot/bot.go
  server/bot/mocks/mock_poster.go
  server/bot/poster.go
  server/incident/incident.go
  server/incident/mocks/mock_store.go
  server/incident/reminder.go
  server/incident/service.go
  server/incident/service_test.go
  server/plugin.go
  server/sqlstore/incident.go
  server/sqlstore/migrations.go
  server/sqlstore/timeline_event_test.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
  tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/timeline-spec.js
  tests-e2e/cypress/support/plugin_api_commands.js
  webapp/src/client.ts
  webapp/src/components/checklist_item.tsx
  webapp/src/components/rhs/rhs_details_view.tsx
  webapp/src/components/rhs/rhs_tab_view.tsx
  webapp/src/components/rhs/rhs_timeline.tsx
  webapp/src/components/rhs/rhs_timeline_event_item.tsx
  webapp/src/components/shared.ts
  webapp/src/types/incident.ts
  webapp/src/types/rhs.ts
Labels: 4: Reviews Complete

#458 log a warning only when failing to promote commander to channel admin
  server/incident/service.go
  server/incident/service_test.go
Labels: 4: Reviews Complete

#460 MM-32408 Moving some stuff to use styled components.
  tests-e2e/cypress/integration/frontstage/incident_rhs_checklist_spec.js
  webapp/src/components/checklist.scss
  webapp/src/components/checklist_item.tsx
  webapp/src/components/rhs/incident_details.scss
  webapp/src/components/rhs/rhs_incident_tasks.tsx
Labels: 4: Reviews Complete

#465 fix tests
  server/incident/service_test.go
Labels: 4: Reviews Complete

#471 remove subscriptions
  build/custom.mk
  client/client.go
  client/doc.go
  client/event_subscriptions.go
  server/api/subscriptions.go
  server/api/subscriptions_test.go
  server/plugin.go
  server/pluginkvstore/mocks/mock_kvapi.go
  server/pluginkvstore/mocks/serverpluginapi/mock_plugin.go
  server/pluginkvstore/pluginapi_client.go
  server/pluginkvstore/subscription_store.go
  server/subscription/service.go
  server/subscription/subscription.go
Labels: 4: Reviews Complete

#473 Use only one version when naming the build
  build/manifest/main.go
Labels: 4: Reviews Complete

#463 MM-32453 - Playbook can be edited to remove all the members
  tests-e2e/cypress/integration/backstage/playbook_creation_spec.js
  webapp/src/components/backstage/share_playbook.tsx
Labels: 4: Reviews Complete

#470 MM-32744 Remove checklist item timestamps
  webapp/src/components/checklist_item.tsx
Labels: 4: Reviews Complete

#464 MM-32637 - Incident reminders shouldn't apply on archiving
  server/incident/service.go
Labels: 4: Reviews Complete

#446 rip out unused source plugin id checking
  server/api/api.go
  server/api/api_test.go
  server/api/incidents_test.go
  server/api/playbooks_test.go
  server/plugin.go
Labels: 4: Reviews Complete, AutoMerge

#430 MM-31643 Add reporter field.
  server/incident/incident.go
  server/incident/service.go
  server/sqlstore/incident.go
  server/sqlstore/migrations.go
  webapp/src/components/profile/profile_selector.tsx
  webapp/src/components/rhs/rhs_incident_summary.tsx
  webapp/src/types/incident.ts
Labels: 4: Reviews Complete

#472 MM-32852 - Fix for Mobile app: `/incident list`
  server/command/command.go
  tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/header_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/open_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/timeline-spec.js
  tests-e2e/cypress/support/index.js
  webapp/src/types/incident.ts
Labels: 4: Reviews Complete

#467 MM-32452 Allow guest users access to their own incidents.
  server/api/incidents.go
  server/api/incidents_test.go
  server/api/playbooks.go
  server/api/playbooks_test.go
  server/command/command.go
  server/incident/incident.go
  server/permissions/permissions.go
  server/sqlstore/incident.go
  server/sqlstore/incident_test.go
Labels: 4: Reviews Complete

#440 MM-31560: Invite users on incident creation
  server/api/incidents.go
  server/api/incidents_test.go
  server/api/playbooks.go
  server/api/playbooks_test.go
  server/incident/incident.go
  server/incident/service.go
  server/playbook/playbook.go
  server/playbook/playbook_test.go
  server/sqlstore/incident.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_test.go
  tests-e2e/cypress/integration/backstage/incident_list_spec.js
  tests-e2e/cypress/integration/backstage/playbook_details_spec.js
  tests-e2e/cypress/integration/frontstage/incident_automation_spec.js
  tests-e2e/cypress/integration/frontstage/slash_command/test_spec.js
  tests-e2e/cypress/support/api/user.js
  tests-e2e/cypress/support/plugin_api_commands.js
  tests-e2e/cypress/support/plugin_ui_commands.js
  tests-e2e/cypress/support/server_api_commands.js
  tests-e2e/cypress/support/ui_commands.js
  webapp/src/components/backstage/automation/invite_users.tsx
  webapp/src/components/backstage/automation/invite_users_selector.tsx
  webapp/src/components/backstage/automation/settings.tsx
  webapp/src/components/backstage/automation/styles.tsx
  webapp/src/components/backstage/automation/toggle.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/profile_autocomplete.tsx
  webapp/src/types/playbook.ts
Labels: 4: Reviews Complete, Docs/Done

#452 Update plugin-api and mattermost-sever hashes
  .circleci/config.yml
  go.mod
  go.sum
Labels: 4: Reviews Complete

#457 added newid if pure multibyte character set
  server/incident/service.go
  server/incident/service_test.go
Labels: 4: Reviews Complete

#461 MM-32615 - Add to Timeline from post dropdown menu
  server/api/incidents.go
  server/command/command.go
  server/incident/filter_options.go
  server/incident/incident.go
  server/incident/mocks/mock_service.go
  server/incident/service.go
  server/sqlstore/incident.go
  server/sqlstore/timeline_event_test.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
  tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/header_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/open_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/timeline-spec.js
  tests-e2e/cypress/support/index.js
  tests-e2e/cypress/support/plugin_ui_commands.js
  tests-e2e/cypress/support/server_api_commands.js
  webapp/src/actions.ts
  webapp/src/components/post_menu.tsx
  webapp/src/components/rhs/rhs_timeline.tsx
  webapp/src/components/rhs/rhs_timeline_event_item.tsx
  webapp/src/index.tsx
  webapp/src/types/incident.ts
  webapp/src/types/rhs.ts
Labels: 3: QA Review

#475 MM-32358 - /incident timeline slash command for mobile
  server/command/command.go
Labels: 4: Reviews Complete

#468 MM-32547 - Remove any event from Timeline
  server/api/api.yaml
  server/api/incidents.go
  server/incident/incident.go
  server/incident/mocks/mock_service.go
  server/incident/mocks/mock_store.go
  server/incident/service.go
  server/sqlstore/incident.go
  tests-e2e/cypress/integration/frontstage/rhs/timeline-spec.js
  webapp/src/client.ts
  webapp/src/components/checklist_item.tsx
  webapp/src/components/rhs/rhs_shared.tsx
  webapp/src/components/rhs/rhs_timeline_event_item.tsx
  webapp/src/types/incident.ts
  webapp/src/types/rhs.ts
Labels: 4: Reviews Complete

#477 MM-32853 & MM-32951 - Hovermenu tweaks and timeline notice
  tests-e2e/cypress/integration/frontstage/rhs/timeline-spec.js
  webapp/src/components/checklist_item.tsx
  webapp/src/components/rhs/rhs_shared.tsx
  webapp/src/components/rhs/rhs_timeline.tsx
Labels: 4: Reviews Complete

#478 MM-32358 - /incident timeline slash command for mobile
  server/command/command.go
Labels: 2: Dev Review

#479 MM-32128 New Status Badges
  tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/header_spec.js
  webapp/src/components/backstage/incidents/incident_details/incident_details.tsx
  webapp/src/components/backstage/incidents/incident_list/incident_list.tsx
  webapp/src/components/backstage/incidents/status_badge.tsx
  webapp/src/components/rhs/rhs_incident_summary.tsx
  webapp/src/components/rhs/rhs_list_incident.tsx
  webapp/src/components/rhs/rhs_title.tsx
Labels: 4: Reviews Complete

#481 Fix height of checklist item containers
  webapp/src/components/checklist_item.tsx
Labels: 4: Reviews Complete
