Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2021-08, with the labels that each got.

#664 MM-37546 - Fix for: Wrong participant count
  server/sqlstore/stats.go
Labels: 4: Reviews Complete

#666 MM-37529: Fix clicking on links in the description
  webapp/src/components/rhs/rhs_about_description.tsx
Labels: 4: Reviews Complete

#667 MM-37526: Render newlines in the description text
  webapp/src/components/rhs/rhs_about_description.tsx
Labels: 2: Dev Review

#665 MM-37538: Reset reminder when updating status to Archived
  server/app/playbook_run_service.go
Labels: 4: Reviews Complete

#671 MM-37519: Make the owner section slightly narrower
  webapp/src/components/rhs/rhs_about.tsx
Labels: 2: Dev Review

#672 MM-37569: Prevent empty title and use Esc to discard changes
  webapp/src/components/rhs/rhs_about_title.tsx
Labels: 4: Reviews Complete

#669 RHS Run Detail: description placeholder UX
  webapp/src/components/rhs/rhs_about_description.tsx
Labels: 4: Reviews Complete

#670 MM-37526: Fix the newline render fix
  webapp/src/components/rhs/rhs_about_description.tsx
Labels: 2: Dev Review

#674 simplify to use --button-bg for template icons
  webapp/src/components/assets/icons/alert_icon.tsx
  webapp/src/components/assets/icons/file_icon.tsx
  webapp/src/components/backstage/template_selector.tsx
Labels: 1: UX Review, 2: Dev Review, CherryPick/Approved

#673 Mm 37532 split name and team
  webapp/src/components/backstage/playbook.scss
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_list/playbook_run_list.scss
  webapp/src/components/backstage/playbook_runs/playbook_run_list/playbook_run_list.tsx
Labels: 4: Reviews Complete

#677 MM-37592: fix rhs_home theme color
  webapp/src/components/rhs/rhs_home.tsx
Labels: 4: Reviews Complete

#675 MM-37588 updated templates
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/template_selector.tsx
  webapp/src/types/playbook.ts
Labels: 1: PM Review, 4: Reviews Complete, AutoMerge

#654 Update document.title in backstage.
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
  webapp/src/components/backstage/playbooks/playbook_backstage.tsx
  webapp/src/hooks/routing.ts
Labels: 2: Dev Review

#680 MM-37698: Simplify CSS and fix layout movement
  webapp/src/components/rhs/rhs_about_description.tsx
Labels: 4: Reviews Complete

#682 MM-37678: Disallow title editing if user has no permissions to change channel name
  webapp/src/components/rhs/rhs_about_title.tsx
Labels: 4: Reviews Complete

#668 [MM-35248] Make backstage current team agnostic
  server/app/playbook_run_service.go
  server/app/playbook_run_service_test.go
  server/app/playbook_service.go
  server/app/service_test.go
  server/app/urls.go
  server/command/command.go
  tests-e2e/cypress/integration/backstage/backstage_spec.js
  tests-e2e/cypress/integration/backstage/playbook_creation_spec.js
  tests-e2e/cypress/integration/backstage/playbook_details_spec.js
  tests-e2e/cypress/integration/backstage/playbook_list_spec.js
  tests-e2e/cypress/integration/backstage/playbook_run_details_spec.js
  tests-e2e/cypress/integration/backstage/playbook_run_list_spec.js
  webapp/src/actions.ts
  webapp/src/browser_routing.ts
  webapp/src/client.ts
  webapp/src/components/backstage/automation/announcement.tsx
  webapp/src/components/backstage/automation/auto_assign_owner.tsx
  webapp/src/components/backstage/automation/settings.tsx
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/channel_selector.tsx
  webapp/src/components/backstage/css_utils.tsx
  webapp/src/components/backstage/new_playbook.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/description.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/participants.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/updates.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/report.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_list/playbook_run_list.tsx
  webapp/src/components/backstage/playbooks/playbook_backstage.tsx
  webapp/src/components/backstage/playbooks/playbook_run_list/playbook_run_list.tsx
  webapp/src/components/backstage/playbooks/playbook_run_list/row.tsx
  webapp/src/components/backstage/share_playbook.tsx
  webapp/src/components/cloud_upgrade_post.tsx
  webapp/src/components/error_page.tsx
  webapp/src/components/post_menu.tsx
  webapp/src/components/post_text.tsx
  webapp/src/components/retrospective_reminder_posts.tsx
  webapp/src/components/rhs/post_card.tsx
  webapp/src/components/rhs/rhs_about_buttons.tsx
  webapp/src/components/rhs/rhs_about_description.tsx
  webapp/src/components/rhs/rhs_checklists.tsx
  webapp/src/components/rhs/rhs_footer.tsx
  webapp/src/components/rhs/rhs_home.tsx
  webapp/src/components/rhs/rhs_home_item.tsx
  webapp/src/components/rhs/rhs_list_view.tsx
  webapp/src/components/rhs/rhs_post_update.tsx
  webapp/src/components/rhs/rhs_title.tsx
  webapp/src/components/rhs/rhs_welcome_view.tsx
  webapp/src/hooks/routing.ts
  webapp/src/index.tsx
  webapp/src/make_update_main_menu.ts
  webapp/src/registry_wrapper.tsx
Labels: 2: Dev Review

#639 Support global header.
  server/app/playbook_run_service_test.go
  server/app/service_test.go
  server/app/urls.go
  server/command/command.go
  tests-e2e/cypress/integration/backstage/backstage_spec.js
  tests-e2e/cypress/integration/backstage/playbook_creation_spec.js
  tests-e2e/cypress/integration/backstage/playbook_details_spec.js
  tests-e2e/cypress/integration/backstage/playbook_list_spec.js
  tests-e2e/cypress/integration/backstage/playbook_run_details_spec.js
  tests-e2e/cypress/integration/backstage/playbook_run_list_spec.js
  tests-e2e/cypress/integration/frontstage/playbook_run_dialog_spec.js
  tests-e2e/cypress/integration/frontstage/playbook_run_rhs_list_spec_dep.js
  tests-e2e/cypress/integration/frontstage/rhs/welcome_spec_dep.js
  tests-e2e/cypress/support/plugin/ui_commands.js
  webapp/src/browser_routing.ts
  webapp/src/components/backstage/backstage.tsx
  webapp/src/index.tsx
Labels: 2: Dev Review

#684 Recursively document PlaybookRunWebhookPayload
  server/app/playbook.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/sqlstore/playbook_run_test.go
  server/telemetry/rudder.go
  server/telemetry/rudder_test.go
Labels: 4: Reviews Complete, Awaiting Submitter Action, AutoMerge

#691 MM-37893: calc global header height in backstage
  webapp/src/components/backstage/backstage.tsx
Labels: 2: Dev Review

#685 [GH-17956] migrate status_filter to styled component
  webapp/src/components/backstage/playbook_runs/playbook_run_list/playbook_run_list.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_list/status_filter.scss
  webapp/src/components/backstage/playbook_runs/playbook_run_list/status_filter.tsx
  webapp/src/components/backstage/playbooks/playbook_run_list/playbook_run_list.tsx
  webapp/src/components/checklist_item.tsx
  webapp/src/components/profile/profile_selector.tsx
  webapp/src/components/team/create_playbook_team_selector.tsx
  webapp/src/components/team/team_selector.tsx
Labels: 4: Reviews Complete

#689 MM-37891: remove close button in backstage
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/backstage_navbar.tsx
Labels: 4: Reviews Complete

#692 Cherry pick for 1.16.1
  README.md
  assets/plugin_icon.png
  assets/plugin_icon.svg
  server/plugin.go
  tests-e2e/cypress/integration/backstage/playbook_details_spec.js
  tests-e2e/cypress/integration/frontstage/playbook_run_automation_spec.js
  tests-e2e/cypress/integration/frontstage/playbook_run_broadcast_spec.js
  tests-e2e/cypress/integration/frontstage/playbook_run_creation_spec.js
  tests-e2e/cypress/integration/frontstage/playbook_run_dialog_spec.js
  tests-e2e/cypress/integration/frontstage/playbook_run_rhs_checklist_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/header_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/latest_update_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/open_spec.js
  tests-e2e/cypress/integration/frontstage/slash_command/info_spec.js
  tests-e2e/cypress/integration/frontstage/slash_command/owner_spec.js
  tests-e2e/cypress/integration/frontstage/slash_command/test_spec.js
Labels: 2: Dev Review

#690 Show no dropdown for a single team
  webapp/src/components/team/create_playbook_team_selector.tsx
Labels: 1: UX Review, 2: Dev Review

#687 [MM-37188] Ignore system message signals
  server/app/playbook_service.go
Labels: 4: Reviews Complete

#683 Mm 37645 customizable auto categorization
  server/api/playbook_runs.go
  server/api/playbooks.go
  server/app/playbook.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/app/playbook_run_service_test.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_run.go
  webapp/src/components/backstage/automation/patterned_input.tsx
  webapp/src/components/backstage/automation/settings.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/types/playbook.ts
Labels: 4: Reviews Complete

#633 MM-35518 - Add CodeQL check
  .github/workflows/codeql-analysis.yml
Labels: 2: Dev Review

#697 MM-37542: Support dynamic channel header tooltip
  tests-e2e/cypress/integration/frontstage/channel_header_spec.js
  webapp/src/components/channel_header.tsx
  webapp/src/index.tsx
Labels: 4: Reviews Complete

#686 MM-37482 - Simplify status to InProgress and Finished; add Finish command
  client/playbook.go
  client/playbook_run.go
  client/playbook_runs.go
  server/api/api.yaml
  server/api/playbook_runs.go
  server/api/playbook_runs_test.go
  server/app/mocks/mock_playbook_run_service.go
  server/app/mocks/mock_playbook_run_store.go
  server/app/playbook.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/app/playbook_run_service_test.go
  server/app/playbook_run_test.go
  server/app/reminder.go
  server/bot/poster.go
  server/command/command.go
  server/sqlstore/migrations.go
  server/sqlstore/migrations_utils.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_run.go
  server/sqlstore/playbook_run_test.go
  server/sqlstore/stats_test.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
  server/telemetry/rudder_test.go
  tests-e2e/cypress/integration/frontstage/playbook_run_broadcast_spec.js
  tests-e2e/cypress/integration/frontstage/playbook_run_rhs_list_spec_dep.js
  tests-e2e/cypress/integration/frontstage/rhs/latest_update_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/open_spec.js
  tests-e2e/cypress/support/plugin/api_commands.js
  tests-e2e/cypress/support/plugin/cleanup.js
  tests-e2e/cypress/support/plugin/ui_commands.js
  webapp/src/actions.ts
  webapp/src/components/backstage/automation/settings.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/followups.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline_retro.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_list/playbook_run_list.tsx
  webapp/src/components/backstage/playbook_runs/status_badge.tsx
  webapp/src/components/backstage/playbooks/playbook_run_list/playbook_run_list.tsx
  webapp/src/components/backstage/playbooks/playbook_run_list/row.tsx
  webapp/src/components/rhs/rhs_checklists.tsx
  webapp/src/components/rhs/rhs_footer.tsx
  webapp/src/components/rhs/rhs_list_playbook_run.tsx
  webapp/src/components/rhs/rhs_timeline.tsx
  webapp/src/components/rhs/rhs_timeline_event_item.tsx
  webapp/src/hooks/general.ts
  webapp/src/slash_command.ts
  webapp/src/types/playbook.ts
  webapp/src/types/playbook_run.ts
  webapp/src/types/rhs.ts
Labels: 4: Reviews Complete

#698 MM-37994: team name in playbook permissions
  tests-e2e/cypress/integration/backstage/playbook_edit_spec.js
  tests-e2e/cypress/integration/backstage/playbook_overview_spec.js
  webapp/src/components/backstage/playbooks/playbook_backstage.tsx
Labels: 4: Reviews Complete

#700 COALESCE(CategoryName)
  server/sqlstore/playbook_run.go
Labels: 2: Dev Review

#701 COALESCE(CategoryName) when querying playbooks too
  server/sqlstore/playbook.go
Labels: 2: Dev Review

#702 MM-37701 - Fix: Active participants in stats graph is including bots
  server/sqlstore/stats.go
  server/sqlstore/stats_test.go
  server/sqlstore/support_for_test.go
Labels: 4: Reviews Complete

#694 MM-37895 error page rendering
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/error_page.tsx
Labels: 4: Reviews Complete

#696 MM-37088: updated font styling
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/playbook.scss
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/metrics.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/retrospective_summary.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/followups.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/learnings.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/retrospective.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_list/playbook_run_list.scss
  webapp/src/components/backstage/playbook_runs/playbook_run_list/playbook_run_list.tsx
  webapp/src/components/backstage/playbook_runs/shared.tsx
  webapp/src/components/backstage/playbooks/playbook_backstage.tsx
  webapp/src/components/backstage/styles.tsx
  webapp/src/components/rhs/rhs_about_title.tsx
  webapp/src/components/rhs/rhs_checklists.tsx
  webapp/src/components/rhs/rhs_home.tsx
  webapp/src/components/rhs/rhs_home_item.tsx
  webapp/src/components/rhs/rhs_welcome_view.tsx
  webapp/src/styles/headings.ts
Labels: 4: Reviews Complete

#699 MM-37634, MM-37483: New Post update dialog with markdown preview
  webapp/package-lock.json
  webapp/package.json
  webapp/src/actions.ts
  webapp/src/client.ts
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/updates.tsx
  webapp/src/components/checklist_item.tsx
  webapp/src/components/command_input.tsx
  webapp/src/components/markdown_textbox.tsx
  webapp/src/components/modals/update_run_status_modal.tsx
  webapp/src/components/rhs/post_card.tsx
  webapp/src/components/rhs/rhs_post_update.tsx
  webapp/src/components/widgets/generic_modal.tsx
  webapp/src/hooks/crud.ts
  webapp/src/hooks/general.ts
  webapp/src/selectors.ts
  webapp/src/slash_command.test.ts
  webapp/src/slash_command.ts
  webapp/src/types/store.ts
  webapp/src/webapp_globals.ts
Labels: 4: Reviews Complete

#706 Remove deprecated linters
  .golangci.yml
  Makefile
  server/app/permissions.go
  server/app/playbook_run_service.go
  server/bot/poster.go
Labels: 4: Reviews Complete

#716 MM-37633 - Thread broadcast messages; Post as bot
  server/app/mocks/mock_playbook_run_service.go
  server/app/mocks/mock_playbook_run_store.go
  server/app/mocks/mock_playbook_service.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/app/playbook_run_service_test.go
  server/bot/bot.go
  server/bot/mocks/mock_poster.go
  server/bot/poster.go
  server/config/mocks/mock_service.go
  server/sqlstore/migrations.go
  server/sqlstore/mocks/mock_configurationapi.go
  server/sqlstore/playbook_run.go
  tests-e2e/cypress.json
  tests-e2e/cypress/integration/frontstage/playbook_run_broadcast_spec.js
  tests-e2e/cypress/support/api/system.js
  tests-e2e/cypress/support/index.js
  tests-e2e/cypress/support/plugin/api_commands.js
Labels: 4: Reviews Complete
