Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2021-05, with the labels that each got.

#539 MM-35291 - Fix incident backstage rendering
  webapp/src/components/backstage/incidents/incident_backstage/incident_backstage.tsx
Labels: 4: Reviews Complete

#537 MM-35293 - Fix for empty channel members header
  webapp/src/components/backstage/incidents/incident_backstage/overview/participants.tsx
Labels: 4: Reviews Complete

#541 Fix permissions server-side
  .circleci/config.yml
  server/api/incidents.go
  server/permissions/permissions.go
Labels: 2: Dev Review

#547 MM-35153: avoid reconnect errors
  webapp/src/websocket_events.test.ts
  webapp/src/websocket_events.ts
Labels: 4: Reviews Complete

#543 MM-35244: updated telemetry
  server/api/incidents.go
  server/incident/incident.go
  server/incident/mocks/mock_service.go
  server/incident/service.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
  server/telemetry/rudder_test.go
  webapp/src/components/rhs/rhs_timeline.tsx
Labels: 4: Reviews Complete

#538 MM-35296 - Fix description bugs
  server/api/incidents.go
  server/api/incidents_test.go
  server/command/command.go
  server/incident/incident.go
  server/incident/mocks/mock_service.go
  server/incident/service.go
  server/incident/service_test.go
  server/sqlstore/incident.go
  server/sqlstore/incident_test.go
Labels: 4: Reviews Complete

#544 MM-35041 MM-35042 Basic retrospective tab and infrastructure
  server/api/incidents.go
  server/incident/incident.go
  server/incident/mocks/mock_service.go
  server/incident/service.go
  server/sqlstore/incident.go
  server/sqlstore/migrations.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
  tests-e2e/cypress/integration/frontstage/rhs/welcome_spec.js
  webapp/src/client.ts
  webapp/src/components/assets/buttons.tsx
  webapp/src/components/backstage/incidents/incident_backstage/incident_backstage.tsx
  webapp/src/components/backstage/incidents/incident_backstage/retrospective/followups.tsx
  webapp/src/components/backstage/incidents/incident_backstage/retrospective/learnings.tsx
  webapp/src/components/backstage/incidents/incident_backstage/retrospective/profile_vertical.tsx
  webapp/src/components/backstage/incidents/incident_backstage/retrospective/report.tsx
  webapp/src/components/backstage/incidents/incident_backstage/retrospective/retrospective.tsx
  webapp/src/components/backstage/incidents/incident_backstage/retrospective/timeline.tsx
  webapp/src/components/backstage/incidents/incident_backstage/retrospective/timeline_retro.tsx
  webapp/src/components/rhs/rhs_welcome_view.tsx
  webapp/src/types/incident.ts
Labels: 2: Dev Review

#550 MM-35518 - Add CodeQL check
  .github/workflows/codeql-analysis.yml
Labels: 4: Reviews Complete

#536 MM-32420 - Send a message when new incident member joins
  go.mod
  server/api/incidents.go
  server/incident/incident.go
  server/incident/mocks/mock_service.go
  server/incident/mocks/mock_store.go
  server/incident/service.go
  server/permissions/permissions.go
  server/playbook/playbook.go
  server/playbook/playbook_test.go
  server/sqlstore/incident.go
  server/sqlstore/incident_test.go
  server/sqlstore/migrations.go
  server/sqlstore/migrations_utils.go
  server/sqlstore/playbook.go
  tests-e2e/cypress/support/plugin_api_commands.js
  webapp/src/actions.ts
  webapp/src/client.ts
  webapp/src/components/backstage/automation/invite_users_selector.tsx
  webapp/src/components/backstage/automation/message_on_join.tsx
  webapp/src/components/backstage/automation/settings.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/template_selector.tsx
  webapp/src/index.tsx
  webapp/src/reducer.ts
  webapp/src/selectors.ts
  webapp/src/types/actions.ts
  webapp/src/types/playbook.ts
  webapp/src/websocket_events.ts
Labels: 4: Reviews Complete

#555 Fix race condition
  server/incident/service.go
Labels: 2: Dev Review

#556 MM-35496 - Playbook prompts for save despite no changes
  webapp/src/components/backstage/step_edit.tsx
Labels: 4: Reviews Complete

#554 MM-35600 - Fix JS error on change commander
  server/api/api.go
  server/api/api_test.go
  server/api/error_handler.go
  server/api/incidents.go
  server/api/incidents_test.go
  server/api/playbooks.go
  server/api/playbooks_test.go
  server/api/stats.go
  server/plugin.go
Labels: 2: Dev Review

#549 MM-17468: Accept a number of days instead of two date arguments in `/incident test bulk-data`
  README.md
  server/command/command.go
Labels: 4: Reviews Complete

#546 MM-34665: Pricing differentiation features
  go.mod
  go.sum
  server/api/api.go
  server/api/bot.go
  server/api/incidents.go
  server/api/incidents_test.go
  server/api/playbooks.go
  server/api/playbooks_test.go
  server/api/stats.go
  server/bot/bot.go
  server/bot/mocks/mock_poster.go
  server/bot/poster.go
  server/command/command.go
  server/config/config.go
  server/config/mocks/mock_service.go
  server/config/service.go
  server/plugin.go
  webapp/src/actions.ts
  webapp/src/client.ts
  webapp/src/components/assets/buttons.tsx
  webapp/src/components/assets/upgrade_illustration_svg.tsx
  webapp/src/components/assets/upgrade_success_illustration_svg.tsx
  webapp/src/components/assets/upgrade_timeline_success_svg.tsx
  webapp/src/components/assets/upgrade_timeline_svg.tsx
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/new_playbook.tsx
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/backstage/start_trial_notice.tsx
  webapp/src/components/backstage/styles.tsx
  webapp/src/components/backstage/template_selector.tsx
  webapp/src/components/backstage/upgrade_badge.tsx
  webapp/src/components/backstage/upgrade_modal.tsx
  webapp/src/components/backstage/upgrade_modal_data.tsx
  webapp/src/components/backstage/upgrade_modal_footer.tsx
  webapp/src/components/backstage/upgrade_modal_header.tsx
  webapp/src/components/backstage/upgrade_modal_illustration.tsx
  webapp/src/components/post_menu.tsx
  webapp/src/components/post_menu_modal.tsx
  webapp/src/components/rhs/rhs_details_view.tsx
  webapp/src/components/rhs/rhs_tab_view.tsx
  webapp/src/components/rhs/rhs_timeline.tsx
  webapp/src/components/rhs/rhs_timeline_placeholder.tsx
  webapp/src/components/widgets/generic_modal.tsx
  webapp/src/constants.ts
  webapp/src/hooks.ts
  webapp/src/index.tsx
  webapp/src/license.ts
  webapp/src/make_update_main_menu.ts
  webapp/src/reducer.ts
  webapp/src/registry_wrapper.tsx
  webapp/src/selectors.ts
  webapp/src/types/actions.ts
Labels: 4: Reviews Complete

#553 Set defaults for playbooks to be open. Access to all and create public channel.
  tests-e2e/cypress/integration/backstage/playbook_creation_spec.js
  webapp/src/components/backstage/playbook_edit.tsx
Labels: 2: Dev Review

#558 MM-35605 - Fix for Playbooks can be closed without changes getting saved
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/route_leaving_guard.tsx
Labels: 2: Dev Review

#559 MM-35605 - Fix a linting error that snuck in somehow
  webapp/src/components/backstage/new_playbook.tsx
Labels: 2: Dev Review

#557 MM-35044 Ability to publish retrospective
  .circleci/config.yml
  server/api/incidents.go
  server/incident/incident.go
  server/incident/mocks/mock_service.go
  server/incident/service.go
  server/incident/service_test.go
  server/plugin.go
  server/sqlstore/incident.go
  server/sqlstore/migrations.go
  tests-e2e/cypress/integration/backstage/playbook_details_spec.js
  tests-e2e/cypress/integration/frontstage/incident_automation_spec.js
  webapp/src/client.ts
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/incidents/incident_backstage/incident_backstage.tsx
  webapp/src/components/backstage/incidents/incident_backstage/retrospective/report.tsx
  webapp/src/components/backstage/incidents/shared.tsx
  webapp/src/components/rhs/rhs_timeline_event_item.tsx
  webapp/src/types/backstage.ts
  webapp/src/types/incident.ts
  webapp/src/types/rhs.ts
Labels: 2: Dev Review

#565 MM-35889: Add telemetry for upgrade features
  server/api/incidents.go
  server/api/incidents_test.go
  server/api/telemetry.go
  server/bot/bot.go
  server/bot/poster.go
  server/plugin.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
  webapp/src/client.ts
  webapp/src/components/backstage/upgrade_modal.tsx
  webapp/src/components/rhs/rhs_timeline_placeholder.tsx
  webapp/src/constants.ts
Labels: 4: Reviews Complete

#562 MM-35650 - Long slash commands don't ellipsis
  webapp/src/components/checklist_item.tsx
  webapp/src/components/widgets/text_with_tooltip_when_ellipsis.tsx
Labels: 2: Dev Review

#567 Fixed errors when rendering HTML
  server/api/api.yaml
Labels: 4: Reviews Complete

#571 MM-35951 - Fix default message on join
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/types/playbook.ts
Labels: 2: Dev Review

#575 MM-36042: Fix admin notification on playbook restriction
  server/bot/poster.go
Labels: 2: Dev Review

#572 Reword license mentions
  README.md
  plugin.json
Labels: 1: PM Review

#574 Fix channel selector selector
  tests-e2e/cypress/integration/backstage/playbook_details_spec.js
  webapp/src/components/backstage/channel_selector.tsx
Labels: 4: Reviews Complete

#576 MM-36002: Remove enterprise terminology
  server/api/bot.go
  server/bot/poster.go
  server/permissions/permissions.go
  webapp/src/components/backstage/convert_enterprise_notice.tsx
  webapp/src/components/backstage/incidents/incident_details/export_link.tsx
  webapp/src/components/backstage/upgrade_modal_data.tsx
Labels: 4: Reviews Complete
