Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2021-09, with the labels that each got.

#719 MM-3775 - e2e tests for new runs permissions system
  tests-e2e/cypress/integration/backstage/playbook_list_permissions_spec.js
Labels: 4: Reviews Complete

#718 MM-30208 Fix incorrect character set being used for IR_System table.
  server/sqlstore/migrations.go
  server/sqlstore/store_test.go
Labels: 4: Reviews Complete

#717 Add keywords selector
  webapp/src/components/backstage/automation/input_keywords.tsx
  webapp/src/components/backstage/automation/settings.tsx
  webapp/src/components/backstage/playbook_edit.tsx
Labels: 4: Reviews Complete

#714 Configure client/client4 for subpaths.
  webapp/src/client.ts
  webapp/src/index.tsx
Labels: 4: Reviews Complete

#722 Tooling: i18n ICU MessageFormat syntax checking
  webapp/.eslintrc.json
  webapp/babel.config.js
  webapp/package-lock.json
  webapp/package.json
Labels: 2: Dev Review

#720 MM-38188 Adding missing primary keys
  server/sqlstore/migrations.go
  server/sqlstore/migrations_utils.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_test.go
  server/sqlstore/store_test.go
  server/sqlstore/support_for_test.go
Labels: 4: Reviews Complete

#725 Rename channel header button
  tests-e2e/cypress/integration/frontstage/channel_header_spec.js
  webapp/src/components/channel_header.tsx
Labels: 4: Reviews Complete

#705 Mm 37191 omit run deleted
  webapp/src/components/backstage/playbooks/playbook_backstage.tsx
  webapp/src/types/playbook.ts
Labels: 4: Reviews Complete

#721 MM-38183: Custom duration picker in Default update timer
  webapp/src/components/backstage/default_update_timer.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/template_selector.tsx
Labels: 4: Reviews Complete, AutoMerge

#723 MM-38277: Fix broadcast channel description
  webapp/src/components/modals/update_run_status_modal.tsx
  webapp/src/components/widgets/text_with_tooltip.tsx
  webapp/src/components/widgets/tooltip.tsx
Labels: 4: Reviews Complete

#730 MM-38254 - Fix for: Wrong filter summary text
  webapp/src/components/backstage/runs_list/runs_list.tsx
Labels: 4: Reviews Complete

#729 MM-38058 - Fix for: Playbook run's backstage button theme is incorrect
  webapp/src/components/backstage/styles.tsx
Labels: 4: Reviews Complete

#728 MM-37513 - Fix for: RHS title is styled the same way in both RHS Home and RHS Details
  webapp/src/components/rhs/rhs_title.tsx
Labels: 4: Reviews Complete

#727 MM-37545 - Fix for: Backstage actions icon misaligned
  webapp/src/components/backstage/playbook.scss
  webapp/src/components/backstage/playbook_list_row.tsx
Labels: 4: Reviews Complete

#733 MM-36267 - Fix for: Tiny straight line in empty timeline in dark theme
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline.tsx
Labels: 2: Dev Review

#731 MM-38453 - Fix for: Text theming incorrect for actions->keyword input
  webapp/src/components/backstage/automation/input_keywords.tsx
Labels: 1: UX Review, 2: Dev Review

#732 MM-38245 - Fix for: ...playbooks.../edit/automation no longer deep links
  server/app/playbook_service.go
Labels: 2: Dev Review

#736 MM-38460 - Fix for: Delete entry confirmation dialog doesn't close
  tests-e2e/cypress/integration/backstage/playbook_retro_timeline_spec.js
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/retrospective.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline_event_item.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline_retro.tsx
  webapp/src/components/rhs/rhs_timeline.tsx
Labels: 2: Dev Review

#708 MM-37775 - New run permissions
  server/api/playbook_runs.go
  server/api/playbook_runs_test.go
  server/api/playbooks.go
  server/api/playbooks_test.go
  server/api/stats.go
  server/api/telemetry.go
  server/app/permissions.go
  server/app/playbook_run_service.go
  server/sqlstore/playbook_run.go
  server/sqlstore/playbook_run_test.go
  tests-e2e/cypress/integration/backstage/playbook_list_permissions_spec.js
Labels: 4: Reviews Complete

#738 Fixing primary key test
  server/sqlstore/migrations_utils.go
  server/sqlstore/store_test.go
Labels: 4: Reviews Complete

#741 MM-38295: markdown inputs in playbook-edit
  webapp/src/components/backstage/automation/message_on_join.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/styles.tsx
  webapp/src/components/checklist_item.tsx
  webapp/src/components/command_input.tsx
  webapp/src/components/markdown_textbox.tsx
Labels: 4: Reviews Complete

#742 require client/v0.6.0, fixing repository name
  go.mod
Labels: 2: Dev Review

#740 MM-38122 Update plugin ID
  client/client.go
  plugin.json
  server/api/api.yaml
  server/api/playbook_runs_test.go
  server/api/playbooks_test.go
  server/api/settings_test.go
  server/app/playbook_run_service_test.go
  server/command/command.go
  server/plugin.go
  server/sqlstore/migrations.go
  server/sqlstore/store_test.go
  server/sqlstore/support_for_test.go
  tests-e2e/cypress/integration/backstage/backstage_spec.js
  tests-e2e/cypress/integration/backstage/playbook_creation_spec.js
  tests-e2e/cypress/support/api/cloud_default_config.json
  tests-e2e/cypress/support/api/on_prem_default_config.json
  tests-e2e/cypress/support/api/plugin.js
  tests-e2e/cypress/support/plugin/api_commands.js
  tests-e2e/db-setup/mm534.sql
  webapp/webpack.config.js
Labels: 2: Dev Review

#735 Removed all instances of 'an playbook'
  README.md
  server/api/api.yaml
  server/app/playbook_run.go
  server/sqlstore/playbook_run.go
  tests-e2e/cypress/integration/frontstage/rhs/open_spec.js
  tests-e2e/cypress/integration/frontstage/slash_command/info_spec.js
  tests-e2e/cypress/integration/frontstage/slash_command/owner_spec.js
  tests-e2e/cypress/support/plugin/api_commands.js
  webapp/src/client.ts
  webapp/src/reducer.ts
  webapp/src/rhs_opener.ts
Labels: 4: Reviews Complete

#744 MM-38438: Don't allow empty channel names.
  server/api/playbook_runs.go
  tests-e2e/cypress/integration/frontstage/playbook_run_dialog_spec.js
Labels: 4: Reviews Complete

#743 MM-38443: ensure status post profiles loaded
  tests-e2e/cypress/integration/backstage/playbook_run_details_spec.js
  tests-e2e/cypress/support/plugin/api_commands.js
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/updates.tsx
  webapp/src/components/rhs/post_card.tsx
Labels: 4: Reviews Complete

#724 MM-37637, MM-38257: Post update reminder timer and revamped FormattedDuration
  tests-e2e/.eslintrc
  tests-e2e/cypress.json
  tests-e2e/cypress/integration/frontstage/playbook_run_broadcast_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/latest_update_spec.js
  tests-e2e/cypress/support/plugin/ui_commands.js
  tests-e2e/cypress/tsconfig.json
  tests-e2e/package-lock.json
  tests-e2e/package.json
  webapp/.eslintrc.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/actions.ts
  webapp/src/components/__snapshots__/duration.test.tsx.snap
  webapp/src/components/__snapshots__/formatted_duration.test.tsx.snap
  webapp/src/components/assets/buttons.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/about.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline_event_item.tsx
  webapp/src/components/backstage/profile_autocomplete.tsx
  webapp/src/components/backstage/runs_list/row.tsx
  webapp/src/components/datetime_input.tsx
  webapp/src/components/duration.test.tsx
  webapp/src/components/duration.tsx
  webapp/src/components/formatted_duration.test.tsx
  webapp/src/components/formatted_duration.tsx
  webapp/src/components/modals/update_run_status_modal.tsx
  webapp/src/components/retrospective_reminder_posts.tsx
  webapp/src/components/rhs/rhs_list_playbook_run.tsx
  webapp/src/components/widgets/generic_modal.tsx
  webapp/src/hooks/crud.ts
  webapp/src/slash_command.ts
  webapp/src/types/playbook_run.ts
  webapp/src/utils.ts
Labels: 4: Reviews Complete

#746 Fixing kvstore migration.
  server/sqlstore/migrations.go
Labels: 4: Reviews Complete

#749 MM-37703 - Fix for: Task assignee dropdown is cut off by center channel
  webapp/src/components/profile/profile_selector.scss
  webapp/src/components/profile/profile_selector.tsx
Labels: 2: Dev Review

#752 MM-38566 Updating to new playbooks icon.
  assets/plugin_icon.png
  assets/plugin_icon.svg
  webapp/src/components/assets/icons/incident_icon.tsx
  webapp/src/components/assets/icons/playbooks_product_icon.tsx
  webapp/src/components/assets/icons/post_menu_icon.tsx
  webapp/src/components/channel_header.tsx
Labels: 4: Reviews Complete

#756 MM-37247 Improving outgoing webhooks.
  server/app/playbook_run_service.go
  server/app/playbook_run_service_test.go
  server/httptools/client.go
Labels: 4: Reviews Complete

#760 MM-38775: Remove dependency on playbook in Update Status modal
  server/api/api.yaml
  server/api/playbook_runs.go
  server/app/playbook_run.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook_run.go
  tests-e2e/.eslintrc
  tests-e2e/cypress/integration/frontstage/rhs/status_update_spec.js
  webapp/src/actions.ts
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/modals/update_run_status_modal.tsx
  webapp/src/types/playbook.ts
  webapp/src/types/playbook_run.ts
Labels: 4: Reviews Complete

#762 MM-37541 Fix svg mask on FF
  webapp/src/components/rhs/rhs_home.tsx
Labels: 2: Dev Review

#758 MM-38722: Fix UpgradeModal misalignment by exposing inner components in GenericModal
  webapp/src/components/backstage/upgrade_modal.tsx
  webapp/src/components/widgets/generic_modal.tsx
Labels: 4: Reviews Complete

#757 MM-38569: Fix timeline permalinks for deleted status posts
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline_event_item.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline_retro.tsx
  webapp/src/types/rhs.ts
  webapp/src/webapp_globals.ts
Labels: 4: Reviews Complete

#748 MM-38037 - Fix for: Team selector opens off screen (in Playbooks backstage)
  webapp/src/components/team/create_playbook_team_selector.tsx
  webapp/src/hooks/general.ts
Labels: 4: Reviews Complete

#750 MM-38681, MM-38680, MM-38699: Assorted followup mini fixes, typing improvements, warning message fixes
  tests-e2e/cypress/integration/backstage/playbook_run_details_spec.js
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/updates.tsx
  webapp/src/components/backstage/runs_list/checkbox_input.tsx
  webapp/src/components/datetime_input.tsx
  webapp/src/components/markdown_textbox.tsx
  webapp/src/components/modals/update_run_status_modal.tsx
  webapp/src/components/retrospective_reminder_posts.tsx
  webapp/src/components/rhs/post_card.tsx
  webapp/src/components/rhs/rhs_home.tsx
  webapp/src/hooks/crud.ts
  webapp/src/hooks/general.ts
  webapp/src/reducer.ts
  webapp/src/selectors.ts
  webapp/src/slash_command.ts
Labels: 4: Reviews Complete

#759 MM-37699: improved finished run semantics
  tests-e2e/cypress/integration/frontstage/rhs/open_spec.js
  webapp/src/components/assets/buttons.tsx
  webapp/src/components/checklist_item.tsx
  webapp/src/components/checklist_item_input.tsx
  webapp/src/components/rhs/collapsible_checklist.tsx
  webapp/src/components/rhs/rhs_about.tsx
  webapp/src/components/rhs/rhs_about_title.tsx
  webapp/src/components/rhs/rhs_checklists.tsx
  webapp/src/components/rhs/rhs_post_update.tsx
  webapp/src/components/rhs/rhs_post_update_button.tsx
  webapp/src/rhs_opener.ts
Labels: 4: Reviews Complete

#754 MM-38744 - Fix for: Broadcast stops if one channel is read-only
  server/app/playbook_run_service.go
Labels: 2: Dev Review

#747 MM-38255 - Fix for: Update content overlaps with the border of the text box
  webapp/src/components/markdown_textbox.tsx
Labels: 4: Reviews Complete

#764 MM-38734 Fix unknown channels being removed when somone without premissions saves playbook.
  server/api/playbooks.go
  server/api/playbooks_test.go
Labels: 2: Dev Review

#763 MM-38566: Rename Playbooks bot
  server/plugin.go
Labels: 4: Reviews Complete

#765 MM-38251: workaround "Run" from Playbooks
  tests-e2e/cypress/integration/backstage/playbook_overview_spec.js
  webapp/src/actions.ts
  webapp/src/components/backstage/playbooks/playbook_backstage.tsx
Labels: 2: Dev Review

#769 MM-38852: Fix size of checkered flag icon
  webapp/src/components/rhs/rhs_post_update.tsx
Labels: 4: Reviews Complete

#767 MM-38585 - Fix for: Rendering of private playbooks for users in a run
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
  webapp/src/components/backstage/runs_list/row.tsx
Labels: 4: Reviews Complete

#753 MM-38582 - Simplify status filtering widget for playbook runs
  tests-e2e/cypress/integration/backstage/playbook_run_list_spec.js
  webapp/src/components/backstage/playbooks/playbook_backstage.tsx
  webapp/src/components/backstage/runs_list/filters.tsx
  webapp/src/components/backstage/runs_list/runs_list.tsx
Labels: 4: Reviews Complete

#766 MM-38731 - Fix for: Old status update dialog partially exposed in web/desktop
  server/api/playbook_runs.go
  server/app/reminder.go
  server/bot/bot.go
  webapp/src/client.ts
  webapp/src/components/update_request_post.tsx
  webapp/src/index.tsx
Labels: 4: Reviews Complete

#761 [MM-37314] Fix the categorization bug
  server/app/playbook_run_service.go
  server/app/playbook_run_service_test.go
Labels: 4: Reviews Complete

#768 MM-38779: test with globalheader
  .circleci/config.yml
  tests-e2e/cypress/integration/frontstage/playbook_run_automation_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/open_spec.js
Labels: 4: Reviews Complete

#771 fix linting issue
  webapp/src/components/update_request_post.tsx
Labels: 2: Dev Review

#745 MM-38522 - POC: Digest of user's current tasks
  server/app/mocks/mock_playbook_run_service.go
  server/app/mocks/mock_playbook_run_store.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/command/command.go
  server/sqlstore/playbook_run.go
  server/sqlstore/playbook_run_test.go
  server/sqlstore/support_for_test.go
Labels: 4: Reviews Complete

#772 MM-38608 - Include list of Runs in Progress
  server/app/mocks/mock_playbook_run_service.go
  server/app/mocks/mock_playbook_run_store.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/command/command.go
  server/sqlstore/playbook_run.go
  server/sqlstore/playbook_run_test.go
Labels: 4: Reviews Complete

#774 MM-38935: Webapp, i18n mvp tooling
  Makefile
  webapp/.eslintrc.json
  webapp/i18n/en.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/datetime_input.tsx
  webapp/src/components/modals/update_run_status_modal.tsx
  webapp/src/components/rhs/rhs_home_item.tsx
  webapp/src/index.tsx
Labels: 4: Reviews Complete

#773 MM-38609 - Checklist Notifications: List of overdue status updates
  server/app/mocks/mock_playbook_run_service.go
  server/app/mocks/mock_playbook_run_store.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/command/command.go
  server/sqlstore/playbook_run.go
  server/sqlstore/playbook_run_test.go
Labels: 4: Reviews Complete
