Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2021-04, with the labels that each got.

#506 MM-33942: fix preferences styling
  webapp/src/components/backstage/styles.tsx
Labels: 4: Reviews Complete

#507 Retrieve only active users
  webapp/src/components/backstage/playbook_edit.tsx
Labels: 4: Reviews Complete

#503 MM-31558: Outgoing webhook on incident's creation
  server/api/api.yaml
  server/api/incidents.go
  server/api/playbooks.go
  server/incident/incident.go
  server/incident/service.go
  server/incident/service_test.go
  server/playbook/playbook.go
  server/playbook/playbook_test.go
  server/sqlstore/incident.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook.go
  tests-e2e/cypress/integration/frontstage/incident_automation_spec.js
  tests-e2e/cypress/support/plugin_api_commands.js
  webapp/src/components/backstage/automation/settings.tsx
  webapp/src/components/backstage/automation/styles.tsx
  webapp/src/components/backstage/automation/webhook_on_creation.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/types/playbook.ts
Labels: 4: Reviews Complete, Docs/Needed

#513 MM-34614 Prevent command box from grabbing focus when already opened.
  webapp/src/components/checklist_item_input.tsx
Labels: 2: Dev Review

#512 MM-34604 Better stats colours
  webapp/src/components/backstage/stats.tsx
Labels: 2: Dev Review

#508 MM-34479 System console setting for which teams plugin is enabled on.
  client/incident.go
  plugin.json
  server/api/incidents.go
  server/api/incidents_test.go
  server/api/playbooks.go
  server/api/playbooks_test.go
  server/command/command.go
  server/config/configuration.go
  server/permissions/permissions.go
  server/plugin.go
  webapp/src/actions.ts
  webapp/src/components/assets/icons/channel_header_button.tsx
  webapp/src/index.tsx
  webapp/src/make_update_main_menu.ts
  webapp/src/reducer.test.ts
  webapp/src/reducer.ts
  webapp/src/rhs_opener.ts
  webapp/src/selectors.ts
  webapp/src/system_console_enabled_teams.tsx
  webapp/src/types/actions.ts
  webapp/src/types/incident.ts
Labels: 2: Dev Review

#514 Fix merge error.
  server/api/incidents_test.go
Labels: 4: Reviews Complete

#515 MM-34772: Fix broadcast status update
  server/incident/service.go
  tests-e2e/cypress/integration/frontstage/incident_broadcast_spec.js
  tests-e2e/cypress/support/plugin_ui_commands.js
  tests-e2e/cypress/support/ui_commands.js
Labels: 4: Reviews Complete

#504 MM-31564: backend support for inviting groups
  client/go.mod
  client/go.sum
  client/incident.go
  client/playbook.go
  go.mod
  go.sum
  server/api/incidents.go
  server/api/incidents_test.go
  server/api/playbooks.go
  server/api/playbooks_test.go
  server/incident/incident.go
  server/incident/service.go
  server/playbook/playbook.go
  server/playbook/playbook_test.go
  server/sqlstore/incident.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_test.go
  server/sqlstore/support_for_test.go
  webapp/src/types/playbook.ts
Labels: 4: Reviews Complete

#501 Archive docs
  README.md
  docs-archive/README.md
  docs-archive/SUMMARY.md
  docs-archive/contributing.md
  docs-archive/creating-and-managing-playbooks.md
  docs-archive/ending-an-incident.md
  docs-archive/glossary.md
  docs-archive/help-and-support.md
  docs-archive/incident-response-slash-commands.md
  docs-archive/installation-and-activation.md
  docs-archive/oldREADME.md
  docs-archive/permissions.md
  docs-archive/playbook-overview.md
  docs-archive/starting-and-joining-an-incident.md
  docs-archive/viewing-incident-details.md
  docs/assets/confirm_end_incident.png
  docs/assets/delete_playbook.png
  docs/assets/file.md
  docs/assets/incident_end_slash_command.png
  docs/assets/incident_response_landing.png
  docs/assets/incident_response_screen.png
  docs/assets/incident_restart_slash_command.png
  docs/assets/playbook_stage_edit.png
  docs/assets/stage_task_header.png
  docs/assets/stage_task_slashcommand.png
  docs/incidents/reviewing-incidents.md
Labels: 1: PM Review

#519 circleci: store_test_results for Cypress
  .circleci/config.yml
  tests-e2e/cypress.json
  tests-e2e/cypress/results/.gitignore
  tests-e2e/package-lock.json
  tests-e2e/package.json
  tests-e2e/reporter-config.json
Labels: 2: Dev Review

#516 MM-34098, MM-34047, MM-34482, MM-34567 - New Incident backstage: overview
  .circleci/config.yml
  client/go.mod
  client/incident.go
  client/incidents.go
  go.sum
  server/api/api.yaml
  server/api/incidents.go
  server/api/incidents_test.go
  server/incident/incident.go
  server/incident/service.go
  tests-e2e/cypress/integration/backstage/backstage_spec.js
  tests-e2e/cypress/integration/backstage/incident_list_spec.js
  tests-e2e/cypress/integration/backstage/playbook_creation_spec.js
  tests-e2e/cypress/integration/backstage/playbook_list_spec.js
  tests-e2e/cypress/integration/frontstage/incident_automation_spec.js
  tests-e2e/cypress/integration/frontstage/incident_creation_spec.js
  tests-e2e/cypress/integration/frontstage/incident_dialog_spec.js
  tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/header_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/latest_update_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/open_spec.js
  tests-e2e/cypress/support/index.js
  tests-e2e/cypress/support/plugin_api_commands.js
  tests-e2e/cypress/support/plugin_ui_commands.js
  tests-e2e/cypress/support/ui_commands.js
  tests-e2e/db-setup/mm534.sql
  tests-e2e/db-setup/test_data.sql
  tests-e2e/package-lock.json
  tests-e2e/package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/incidents/incident_backstage/incident_backstage.tsx
  webapp/src/components/backstage/incidents/incident_backstage/overview/description.tsx
  webapp/src/components/backstage/incidents/incident_backstage/overview/metrics.tsx
  webapp/src/components/backstage/incidents/incident_backstage/overview/overview.tsx
  webapp/src/components/backstage/incidents/incident_backstage/overview/participants.tsx
  webapp/src/components/backstage/incidents/incident_backstage/overview/profile_w_position.tsx
  webapp/src/components/backstage/incidents/incident_backstage/overview/retrospective_summary.tsx
  webapp/src/components/backstage/incidents/incident_backstage/overview/updates.tsx
  webapp/src/components/backstage/incidents/incident_details/checklist_timeline.tsx
  webapp/src/components/backstage/incidents/incident_list/incident_list.tsx
  webapp/src/components/backstage/incidents/incident_list/status_filter.tsx
  webapp/src/components/backstage/incidents/shared.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/styles.tsx
  webapp/src/components/backstage/template_selector.tsx
  webapp/src/components/checklist_item.tsx
  webapp/src/components/dot_menu.tsx
  webapp/src/components/post_text.tsx
  webapp/src/components/rhs/post_card.tsx
  webapp/src/components/rhs/rhs_about.tsx
  webapp/src/components/rhs/rhs_details_view.tsx
  webapp/src/components/rhs/rhs_shared.tsx
  webapp/src/components/rhs/rhs_tab_view.tsx
  webapp/src/hooks.ts
  webapp/src/selectors.ts
  webapp/src/types/backstage.ts
  webapp/src/types/rhs.ts
Labels: 4: Reviews Complete

#521 Fix CI on master
  .circleci/config.yml
Labels: 2: Dev Review

#520 MM-34718: fix incident welcome when filtering
  tests-e2e/cypress/integration/backstage/incident_list_spec.js
  webapp/src/components/backstage/incidents/incident_list/incident_list.tsx
Labels: 4: Reviews Complete

#531 Temporarily hide the /stats page
  tests-e2e/cypress/integration/backstage/backstage_spec.js
  tests-e2e/cypress/integration/backstage/incident_list_spec.js
  tests-e2e/cypress/integration/backstage/playbook_creation_spec.js
  tests-e2e/cypress/integration/backstage/playbook_list_spec.js
  webapp/src/components/backstage/backstage.tsx
  webapp/src/make_update_main_menu.ts
Labels: 4: Reviews Complete

#524 MM-34568 - Design Polish on Incident Overview tab
  server/incident/service.go
  webapp/src/components/backstage/incidents/incident_backstage/incident_backstage.tsx
  webapp/src/components/backstage/incidents/incident_backstage/overview/about.tsx
  webapp/src/components/backstage/incidents/incident_backstage/overview/description.tsx
  webapp/src/components/backstage/incidents/incident_backstage/overview/overview.tsx
  webapp/src/components/backstage/incidents/incident_backstage/overview/participants.tsx
  webapp/src/components/backstage/incidents/incident_backstage/overview/updates.tsx
  webapp/src/components/backstage/incidents/incident_details/export_link.tsx
  webapp/src/components/backstage/incidents/shared.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/template_selector.tsx
  webapp/src/components/rhs/incident_details.scss
  webapp/src/components/rhs/rhs_about.tsx
  webapp/src/components/rhs/rhs_footer.tsx
  webapp/src/components/rhs/rhs_incident_tasks.tsx
  webapp/src/components/rhs/rhs_shared.tsx
Labels: 4: Reviews Complete

#529 MM-35074: don't initialize args parameter
  webapp/package-lock.json
  webapp/package.json
  webapp/src/slash_command.test.ts
  webapp/src/slash_command.ts
Labels: 4: Reviews Complete

#518 [MM-34601] Change "Invite Members" label to "Assign Commander"
  webapp/src/components/backstage/automation/assign_commander_selector.tsx
Labels: 4: Reviews Complete

#530 Update dependencies
  webapp/.eslintrc.json
  webapp/babel.config.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/assets/icons/incident_icon.tsx
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/incidents/incident_details/checklist_timeline.tsx
  webapp/src/components/backstage/incidents/incident_details/incident_details.tsx
  webapp/src/components/backstage/incidents/incident_list/status_filter.tsx
  webapp/src/components/profile/profile_selector.tsx
  webapp/tests/setup.js
  webapp/webpack.config.js
Labels: 4: Reviews Complete

#532 Validate webhook URL only when enabled
  server/api/playbooks.go
Labels: 4: Reviews Complete

#525 MM-34665: Pricing differentiation plan: backend support
  server/api/api.go
  server/api/incidents.go
  server/api/playbooks.go
  server/api/playbooks_test.go
  server/api/stats.go
  server/config/service.go
  server/playbook/mocks/mock_service.go
  server/playbook/mocks/mock_store.go
  server/playbook/playbook.go
  server/playbook/service.go
  server/plugin.go
  server/sqlstore/playbook.go
  webapp/src/actions.ts
  webapp/src/client.ts
  webapp/src/components/backstage/backstage.tsx
  webapp/src/index.tsx
  webapp/src/license.ts
  webapp/src/make_update_main_menu.ts
  webapp/src/reducer.ts
  webapp/src/selectors.ts
  webapp/src/types/actions.ts
  webapp/src/types/playbook.ts
  webapp/src/types/websocket_events.ts
  webapp/src/websocket_events.ts
Labels: 4: Reviews Complete

#527 MM-33850 - Event for when participants joined/left the incident
  server/incident/incident.go
  server/incident/mocks/mock_service.go
  server/incident/service.go
  server/plugin.go
  tests-e2e/cypress/integration/frontstage/rhs/timeline-spec.js
  webapp/src/components/rhs/rhs_timeline.tsx
  webapp/src/components/rhs/rhs_timeline_event_item.tsx
  webapp/src/types/rhs.ts
Labels: 4: Reviews Complete

#533 MM-34675 Improve UI for system console toggle.
  webapp/src/system_console_enabled_teams.tsx
Labels: CherryPick/Approved

#523 MM-34775 Playbook open by default
  server/api/incidents.go
  server/permissions/permissions.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_test.go
  tests-e2e/cypress/integration/backstage/playbook_creation_spec.js
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/share_playbook.tsx
Labels: 2: Dev Review

#535 MM-35051 Experimental features flag
  plugin.json
  server/api/api.go
  server/config/configuration.go
  webapp/src/browser_routing.ts
  webapp/src/components/backstage/backstage.tsx
  webapp/src/hooks.ts
  webapp/src/make_update_main_menu.ts
  webapp/src/types/settings.ts
Labels: 2: Dev Review
