Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2021-07, with the labels that each got.

#595 [MM-32418] Export channel on incident archive
  client/playbook.go
  client/playbook_run.go
  server/api/playbook_runs.go
  server/app/playbook.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/bot/bot.go
  server/bot/mocks/mock_poster.go
  server/bot/poster.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_run.go
  webapp/src/components/backstage/automation/export_channel_on_archive.tsx
  webapp/src/components/backstage/automation/settings.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/types/playbook.ts
Labels: 4: Reviews Complete, AutoMerge

#623 MM-36768: Allow playbook editing regardless of the license
  server/app/permissions.go
Labels: 4: Reviews Complete

#625 redirect /incidents to /runs
  webapp/src/components/backstage/backstage.tsx
Labels: 2: Dev Review

#627 MM-36766 - Remove RHS tabs
  tests-e2e/cypress/integration/frontstage/playbook_run_rhs_checklist_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/timeline-spec.js
  webapp/src/actions.ts
  webapp/src/components/rhs/rhs_about.tsx
  webapp/src/components/rhs/rhs_checklists.tsx
  webapp/src/components/rhs/rhs_details_view.tsx
  webapp/src/components/rhs/rhs_main.tsx
  webapp/src/components/rhs/rhs_playbook_run_tasks.tsx
  webapp/src/components/rhs/rhs_run_details.tsx
  webapp/src/components/rhs/rhs_tab_view.tsx
  webapp/src/reducer.ts
  webapp/src/selectors.ts
  webapp/src/types/actions.ts
  webapp/src/types/rhs.ts
Labels: 4: Reviews Complete

#632 MM-36876: useProfilesInChannel should try once
  webapp/src/hooks.ts
Labels: 4: Reviews Complete

#635 stop random scroll on edit playbook
  webapp/src/components/checklist_item_input.tsx
Labels: 2: Dev Review

#637 properly initialize fixture users
  tests-e2e/cypress/support/index.js
Labels: 2: Dev Review

#598 MM-32421: categorize incident channel when a new incident member joins
  .gitignore
  go.mod
  go.sum
  server/api/playbook_runs.go
  server/app/playbook.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/app/playbook_run_service_test.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_run.go
  tests-e2e/cypress/integration/frontstage/rhs/timeline-spec.js
  webapp/src/components/backstage/automation/categorize_playbook_run.tsx
  webapp/src/components/backstage/automation/settings.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/multi_checkbox.tsx
  webapp/src/components/rhs/rhs_timeline.tsx
  webapp/src/types/playbook.ts
Labels: 4: Reviews Complete

#636 make playbook navbar sticky
  tests-e2e/cypress/support/plugin_ui_commands.js
  tests-e2e/cypress/support/ui_commands.js
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/backstage_navbar.tsx
  webapp/src/components/backstage/playbook_edit.tsx
Labels: 2: Dev Review

#640 Remove global stats view.
  server/api/stats.go
  server/sqlstore/stats.go
  server/sqlstore/stats_test.go
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/stats.tsx
Labels: 2: Dev Review

#642 Cleanup unused code.
  assets/center_channel.png
  webapp/src/actions.ts
  webapp/src/components/assets/empty_checklist.tsx
  webapp/src/components/assets/upgrade_playbook_dashboard_svg.tsx
  webapp/src/components/assets/upgrade_playbook_error_svg.tsx
  webapp/src/components/assets/upgrade_playbook_success_svg.tsx
  webapp/src/components/assets/upgrade_timeline_error_svg.tsx
  webapp/src/components/assets/upgrade_timeline_success_svg.tsx
  webapp/src/components/assets/upgrade_timeline_svg.tsx
  webapp/src/components/assets/waves.tsx
  webapp/src/components/backstage/automation/webhook.tsx
  webapp/src/components/backstage/playbook_runs/shared.tsx
  webapp/src/components/backstage/stages_and_steps_icon.tsx
  webapp/src/components/backstage/styles.tsx
  webapp/src/components/widgets/toggle.tsx
  webapp/src/constants.ts
  webapp/src/hooks.ts
  webapp/src/types/playbook.ts
Labels: 4: Reviews Complete

#643 Update dependencies.
  webapp/package-lock.json
  webapp/package.json
Labels: 2: Dev Review

#628 MM-36876 - Fix: Participant count in playbook dashboard incident list is not fetching correctly
  server/app/playbook_run.go
  server/sqlstore/playbook_run.go
  server/sqlstore/playbook_run_test.go
  server/sqlstore/support_for_test.go
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/participants.tsx
  webapp/src/components/backstage/playbooks/playbook_run_list/row.tsx
  webapp/src/hooks.ts
  webapp/src/selectors.ts
  webapp/src/types/playbook_run.ts
Labels: 4: Reviews Complete

#644 MM-35598 - Merge feature branch to master
  tests-e2e/cypress/integration/frontstage/playbook_run_rhs_checklist_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/timeline-spec.js
  webapp/src/actions.ts
  webapp/src/components/rhs/rhs_about.tsx
  webapp/src/components/rhs/rhs_checklists.tsx
  webapp/src/components/rhs/rhs_details_view.tsx
  webapp/src/components/rhs/rhs_main.tsx
  webapp/src/components/rhs/rhs_playbook_run_tasks.tsx
  webapp/src/components/rhs/rhs_run_details.tsx
  webapp/src/components/rhs/rhs_tab_view.tsx
  webapp/src/reducer.ts
  webapp/src/selectors.ts
  webapp/src/types/actions.ts
  webapp/src/types/rhs.ts
Labels: 4: Reviews Complete

#631 MM-36912 - Checklist header, collapsible, with progress bar
  tests-e2e/cypress/integration/frontstage/playbook_run_rhs_checklist_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/welcome_spec.js
  tests-e2e/cypress/support/plugin_ui_commands.js
  webapp/src/components/rhs/collapsible_checklist.tsx
  webapp/src/components/rhs/rhs_checklists.tsx
Labels: 4: Reviews Complete

#634 MM-35696: RHS Home (RHS Playbooks)
  client/playbook_run.go
  plugin.json
  server/api/playbooks.go
  server/api/playbooks_test.go
  server/app/playbook.go
  server/app/sort.go
  server/sqlstore/playbook.go
  tests-e2e/cypress.json
  tests-e2e/cypress/integration/frontstage/playbook_run_creation_spec.js
  tests-e2e/cypress/integration/frontstage/playbook_run_rhs_list_spec_dep.js
  tests-e2e/cypress/integration/frontstage/rhs/open_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/welcome_spec_dep.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/client.ts
  webapp/src/components/assets/box_open_svg.tsx
  webapp/src/components/assets/buttons.tsx
  webapp/src/components/assets/page_run_collaboration_svg.tsx
  webapp/src/components/assets/page_run_svg.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
  webapp/src/components/backstage/playbooks/playbook_backstage.tsx
  webapp/src/components/backstage/playbooks/playbook_run_list/playbook_run_list.tsx
  webapp/src/components/backstage/share_playbook.tsx
  webapp/src/components/backstage/template_selector.tsx
  webapp/src/components/checklist_item.tsx
  webapp/src/components/rhs/rhs_home.tsx
  webapp/src/components/rhs/rhs_home_item.tsx
  webapp/src/components/rhs/rhs_main.tsx
  webapp/src/components/rhs/rhs_timeline_event_item.tsx
  webapp/src/components/rhs/rhs_title.tsx
  webapp/src/components/shared.ts
  webapp/src/components/widgets/pill.tsx
  webapp/src/hooks/crud.ts
  webapp/src/hooks/general.ts
  webapp/src/hooks/index.ts
  webapp/src/hooks/routing.ts
  webapp/src/types/playbook.ts
  webapp/src/types/playbook_run.ts
  webapp/src/webapp_globals.ts
  webapp/webpack.config.js
Labels: 4: Reviews Complete

#638 Upgraded cypress 7
  tests-e2e/cypress.json
  tests-e2e/cypress/fixtures/theme.json
  tests-e2e/cypress/fixtures/timeouts.js
  tests-e2e/cypress/integration/backstage/playbook_creation_spec.js
  tests-e2e/cypress/integration/backstage/playbook_run_list_spec.js
  tests-e2e/cypress/integration/frontstage/playbook_run_rhs_checklist_spec.js
  tests-e2e/cypress/integration/frontstage/playbook_run_rhs_list_spec_dep.js
  tests-e2e/cypress/integration/frontstage/rhs/open_spec.js
  tests-e2e/cypress/integration/frontstage/rhs/timeline-spec.js
  tests-e2e/cypress/integration/frontstage/rhs/welcome_spec_dep.js
  tests-e2e/cypress/support/endpoints.json
  tests-e2e/cypress/support/plugin_api_commands.js
  tests-e2e/package-lock.json
  tests-e2e/package.json
  webapp/src/components/backstage/playbooks/playbook_backstage.tsx
Labels: 4: Reviews Complete

#648 Rebrand
  README.md
  build/custom.mk
  client/client_test.go
  client/doc_test.go
  client/go.mod
  client/playbook_runs_test.go
  client/playbooks_test.go
  go.mod
  plugin.json
  server/api/api.go
  server/api/api_test.go
  server/api/bot.go
  server/api/error_handler.go
  server/api/playbook_runs.go
  server/api/playbook_runs_test.go
  server/api/playbooks.go
  server/api/playbooks_test.go
  server/api/settings.go
  server/api/settings_test.go
  server/api/signal.go
  server/api/stats.go
  server/api/telemetry.go
  server/app/mocks/mock_job_once_scheduler.go
  server/app/mocks/mock_keywords_ignorer.go
  server/app/mocks/mock_playbook_run_service.go
  server/app/mocks/mock_playbook_run_store.go
  server/app/mocks/mock_playbook_service.go
  server/app/mocks/mock_playbook_store.go
  server/app/permissions.go
  server/app/playbook_run_service.go
  server/app/playbook_run_service_test.go
  server/app/playbook_service.go
  server/app/service_test.go
  server/bot/bot.go
  server/bot/mocks/mock_logger.go
  server/bot/mocks/mock_poster.go
  server/command/command.go
  server/config/mocks/mock_service.go
  server/playbook/mocks/mock_keywords_ignorer.go
  server/plugin.go
  server/sqlstore/migrations.go
  server/sqlstore/mocks/mock_configurationapi.go
  server/sqlstore/mocks/mock_kvapi.go
  server/sqlstore/mocks/mock_storeapi.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_run.go
  server/sqlstore/playbook_run_test.go
  server/sqlstore/playbook_test.go
  server/sqlstore/stats.go
  server/sqlstore/stats_test.go
  server/sqlstore/store.go
  server/sqlstore/store_test.go
  server/sqlstore/support_for_test.go
  server/sqlstore/timeline_event_test.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
  server/telemetry/rudder_test.go
Labels: 4: Reviews Complete

#650 Swap runs icon.
  webapp/src/components/backstage/backstage.tsx
Labels: 4: Reviews Complete

#653 Removing some references to old names.
  README.md
  client/client.go
  client/doc.go
  client/playbook_runs.go
  client/playbooks.go
  server/api/api.yaml
  server/app/playbook_run_service_test.go
  server/bot/poster.go
  server/command/command.go
  server/plugin.go
  tests-e2e/cypress/support/index.js
  tests-e2e/cypress/support/plugin_ui_commands.js
  tests-e2e/db-setup/mm534.sql
  webapp/src/make_update_main_menu.ts
Labels: 2: Dev Review

#652 Updated playbook templates
  server/api/telemetry.go
  server/app/playbook.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_test.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
  tests-e2e/cypress/integration/backstage/playbook_creation_spec.js
  webapp/src/client.ts
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/backstage/template_selector.tsx
  webapp/src/components/rhs/rhs_home.tsx
Labels: 4: Reviews Complete

#659 MM-37019: RHS Home Polish
  webapp/src/components/rhs/rhs_home.tsx
Labels: 2: Dev Review

#647 MM-36915 - Collapse/expand all checklists (save state per user)
  webapp/src/actions.ts
  webapp/src/components/rhs/collapsible_checklist.tsx
  webapp/src/components/rhs/rhs_checklists.tsx
  webapp/src/reducer.ts
  webapp/src/selectors.ts
  webapp/src/types/actions.ts
Labels: 4: Reviews Complete

#660 Fix for table 'mattermost.bots' not found in query
  server/sqlstore/playbook_run.go
  server/sqlstore/support_for_test.go
Labels: 2: Dev Review

#649 MM-36913 - Filter tasks w/ default (state saved per user)
  webapp/src/actions.ts
  webapp/src/components/dot_menu.tsx
  webapp/src/components/multi_checkbox.tsx
  webapp/src/components/rhs/rhs_checklists.tsx
  webapp/src/reducer.ts
  webapp/src/selectors.ts
  webapp/src/types/actions.ts
  webapp/src/types/playbook.ts
Labels: 4: Reviews Complete

#661 MM-37508 - RHS About collapsed saved state per user
  webapp/src/actions.ts
  webapp/src/components/rhs/rhs_about.tsx
  webapp/src/reducer.ts
  webapp/src/selectors.ts
  webapp/src/types/actions.ts
Labels: 4: Reviews Complete

#658 MM-37326: Inline editing
  client/playbook_run.go
  client/playbook_runs.go
  server/api/playbook_runs.go
  server/api/playbook_runs_test.go
  server/app/mocks/mock_playbook_run_service.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/app/playbook_run_service_test.go
  server/app/reminder.go
  tests-e2e/cypress/integration/frontstage/rhs/latest_update_spec.js
  tests-e2e/cypress/support/ui_commands.js
  webapp/src/actions.ts
  webapp/src/client.ts
  webapp/src/components/assets/icons/clock.tsx
  webapp/src/components/assets/icons/exclamation.tsx
  webapp/src/components/rhs/rhs_about.tsx
  webapp/src/components/rhs/rhs_about_description.tsx
  webapp/src/components/rhs/rhs_about_title.tsx
  webapp/src/hooks/general.ts
  webapp/src/reducer.ts
  webapp/src/selectors.ts
  webapp/src/types/actions.ts
Labels: 4: Reviews Complete

#656 MM-37325: RHS update timer
  client/playbook_run.go
  client/playbook_runs.go
  server/api/playbook_runs.go
  server/api/playbook_runs_test.go
  server/app/mocks/mock_playbook_run_service.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/app/playbook_run_service_test.go
  server/app/reminder.go
  tests-e2e/cypress/integration/frontstage/rhs/latest_update_spec.js
  tests-e2e/cypress/support/ui_commands.js
  webapp/src/actions.ts
  webapp/src/client.ts
  webapp/src/components/assets/buttons.tsx
  webapp/src/components/assets/icons/clock.tsx
  webapp/src/components/assets/icons/exclamation.tsx
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/dot_menu.tsx
  webapp/src/components/duration.tsx
  webapp/src/components/rhs/playbook_run_details.scss
  webapp/src/components/rhs/rhs_about.tsx
  webapp/src/components/rhs/rhs_about_buttons.tsx
  webapp/src/components/rhs/rhs_about_description.tsx
  webapp/src/components/rhs/rhs_about_title.tsx
  webapp/src/components/rhs/rhs_list_view.tsx
  webapp/src/components/rhs/rhs_participant.tsx
  webapp/src/components/rhs/rhs_post_update.tsx
  webapp/src/components/rhs/rhs_post_update_button.tsx
  webapp/src/components/rhs/rhs_title.tsx
  webapp/src/hooks/general.ts
  webapp/src/reducer.ts
  webapp/src/selectors.ts
  webapp/src/types/actions.ts
  webapp/src/types/playbook_run.ts
Labels: 4: Reviews Complete

#657 [MM-37314] Remove channel from prev category
  server/app/playbook_run_service.go
  server/app/playbook_run_service_test.go
  server/plugin.go
Labels: 4: Reviews Complete

#641 [MM-35264] Workspace wide scope - playbooks
  server/api/playbooks.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_run.go
  server/sqlstore/playbook_test.go
  server/sqlstore/support_for_test.go
  tests-e2e/cypress/integration/backstage/playbook_creation_spec.js
  tests-e2e/cypress/integration/backstage/playbook_details_spec.js
  tests-e2e/cypress/integration/backstage/playbook_list_spec.js
  webapp/src/components/backstage/new_playbook.tsx
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_list/playbook_run_list.tsx
  webapp/src/components/backstage/template_selector.tsx
  webapp/src/components/backstage/upgrade_modal_data.tsx
  webapp/src/components/rhs/rhs_home.tsx
  webapp/src/components/team/create_playbook_team_selector.tsx
  webapp/src/components/team/team_selector.tsx
  webapp/src/components/team/team_with_icon.tsx
  webapp/src/hooks/general.ts
  webapp/src/hooks/routing.ts
  webapp/src/selectors.ts
Labels: 2: Dev Review

#663 MM-37533 - Empty checklists after filtering should omit the body
  webapp/src/components/rhs/rhs_checklists.tsx
Labels: 2: Dev Review
