Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2021-12, with the labels that each got.

#831 [MM-39119] Auto complete categories in categorize playbook run
  tests-e2e/cypress/integration/playbooks/edit_spec.js
  tests-e2e/cypress/support/plugin/ui_commands.js
  webapp/i18n/en.json
  webapp/src/components/backstage/automation/assign_owner_selector.tsx
  webapp/src/components/backstage/automation/broadcast.tsx
  webapp/src/components/backstage/automation/categorize_playbook_run.tsx
  webapp/src/components/backstage/automation/clear_indicator.tsx
  webapp/src/components/backstage/automation/invite_users_selector.tsx
  webapp/src/components/backstage/automation/menu_list.tsx
  webapp/src/components/backstage/automation/settings.tsx
  webapp/src/components/backstage/category_selector.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/styles.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#919 [MM-40431] Add telemetry to follow/unfollow
  server/app/mocks/mock_playbook_run_service.go
  server/app/playbook.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/app/playbook_run_service_test.go
  server/app/playbook_service.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
Labels: 2: Dev Review

#918 Fix broken select in RHS
  webapp/src/components/update_request_post.tsx
Labels: 1: UX Review, 2: Dev Review

#909 Mm 38591 allow disabling status update
  server/api/playbook_runs.go
  server/app/playbook.go
  server/app/playbook_run.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_run.go
  tests-e2e/cypress/integration/channels/rhs/status_update_spec.js
  tests-e2e/cypress/integration/playbooks/edit_spec.js
  tests-e2e/cypress/integration/runs/details_spec.js
  tests-e2e/cypress/support/plugin/api_commands.js
  webapp/i18n/en.json
  webapp/src/components/backstage/automation/settings.tsx
  webapp/src/components/backstage/default_update_timer.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/updates.tsx
  webapp/src/components/backstage/playbooks/playbook_preview_status_updates.tsx
  webapp/src/components/datetime_input.tsx
  webapp/src/components/rhs/rhs_about.tsx
  webapp/src/components/rhs/rhs_post_update.tsx
  webapp/src/types/playbook.ts
  webapp/src/types/playbook_run.ts
Labels: 4: Reviews Complete

#911 Mm 38590 allow disabling retrospective
  server/api/playbook_runs.go
  server/app/playbook.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_run.go
  tests-e2e/cypress/integration/channels/actions_spec.js
  tests-e2e/cypress/integration/playbooks/edit_spec.js
  tests-e2e/cypress/integration/runs/details_spec.js
  tests-e2e/cypress/support/plugin/api_commands.js
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/retrospective.tsx
  webapp/src/components/backstage/playbooks/playbook_preview_retrospective.tsx
  webapp/src/components/retrospective_reminder_posts.tsx
  webapp/src/types/playbook.ts
  webapp/src/types/playbook_run.ts
Labels: 2: Dev Review

#923 [MM-40500] Fix copy link
  webapp/src/client.ts
Labels: 2: Dev Review

#925 MM-40503/MM-40270: Fix formatted message page crash
  webapp/src/components/backstage/start_trial_notice.tsx
Labels: 4: Reviews Complete

#926 Cypress: Reduce numTestsKeptInMemory
  tests-e2e/cypress.json
Labels: 2: Dev Review

#927 [MM-39958] Fix screen fill for playbook view
  webapp/src/components/backstage/backstage.tsx
Labels: 4: Reviews Complete

#931 MM-40505: Fix: "Unassigned" and "Others" checklist filter broken
  webapp/src/components/rhs/rhs_checklists.tsx
Labels: 2: Dev Review

#922 MM-40305: Preliminary work to simplify RHSChecklists component
  webapp/src/components/checklist_item.tsx
  webapp/src/components/rhs/rhs_checklist.tsx
  webapp/src/components/rhs/rhs_checklist_item.tsx
  webapp/src/components/rhs/rhs_checklist_list.tsx
  webapp/src/components/rhs/rhs_run_details.tsx
Labels: 2: Dev Review

#907 MM-37549: Avoid repetitive notifications on completing tasks
  client/playbook.go
  server/api/api.yaml
  server/app/playbook.go
  server/app/playbook_run_service.go
  server/app/playbook_run_service_test.go
  server/telemetry/rudder_test.go
  tests-e2e/cypress/integration/channels/rhs/checklist_spec.js
  tests-e2e/cypress/integration/channels/slash_command/owner_spec.js
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline_event_item.tsx
  webapp/src/components/checklist_item.tsx
  webapp/src/components/rhs/rhs_about.tsx
  webapp/src/types/playbook.ts
  webapp/src/types/playbook_run.ts
Labels: 1: UX Review, 1. Editor Review

#929 MM-40490: Endpoint to add a checklist item should be a POST, not PUT
  client/playbook_runs.go
  server/api/playbook_runs.go
  server/api_runs_test.go
  webapp/src/client.ts
Labels: 4: Reviews Complete

#930 MM-40511: Improve retro editing/saving flow; Fix: Guard against publishing retro accidentally
  tests-e2e/cypress/integration/runs/retrospective_spec.js
  webapp/i18n/en.json
  webapp/package.json
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/report.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/report_text_area.tsx
  webapp/src/components/rhs/rhs_about_description.tsx
Labels: 4: Reviews Complete

#928 MM-39457: Status update modal, add 'Finish Run' flow
  server/api/playbook_runs.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  tests-e2e/cypress/integration/channels/rhs/status_update_spec.js
  tests-e2e/cypress/support/plugin/ui_commands.js
  webapp/i18n/en.json
  webapp/src/actions.ts
  webapp/src/client.ts
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/backstage/playbook_runs/shared.tsx
  webapp/src/components/backstage/styles.tsx
  webapp/src/components/modals/update_run_status_modal.tsx
  webapp/src/components/rhs/post_card.tsx
  webapp/src/components/rhs/rhs_post_update.tsx
  webapp/src/components/update_request_post.tsx
  webapp/src/components/widgets/confirmation_modal.tsx
  webapp/src/components/widgets/generic_modal.tsx
  webapp/src/slash_command.ts
Labels: 1: UX Review

#935 MM-39896: Add more preview tests
  tests-e2e/cypress/integration/playbooks/overview_spec.js
  tests-e2e/cypress/support/plugin/api_commands.js
  webapp/src/components/backstage/playbooks/playbook_preview.tsx
Labels: 2: Dev Review

#942 MM-37227: move profile selector to styled components
  tests-e2e/cypress/support/api/role.js
  webapp/src/components/backstage/runs_list/playbook_selector.tsx
  webapp/src/components/profile/dropdown_selector_style.tsx
  webapp/src/components/profile/profile_selector.tsx
  webapp/src/components/team/create_playbook_team_selector.tsx
Labels: 2: Dev Review

#940 Improved skip integrity check
  Makefile
  webapp/package-lock.json
  webapp/package.json
  webapp/skip_integrity_check.js
Labels: 2: Dev Review

#941 MM-35035: Cypress parallelism
  .circleci/config.yml
Labels: 4: Reviews Complete

#949 MM-40656: Z-index issue between sticky headers and user profile dropdown
  webapp/src/components/profile/dropdown_selector_style.tsx
Labels: 4: Reviews Complete

#950 MM-40748: Fix cannot assign tasks in RHS
  webapp/src/components/checklist_item.tsx
Labels: 4: Reviews Complete

#945 MM-40001, MM-40637: playbooks/server i18n runtime-tooling and first-conversion
  .circleci/config.yml
  Makefile
  assets/i18n/en.json
  go.tools.mod
  go.tools.sum
  server/app/playbook_run_service.go
  server/plugin.go
  tests-e2e/cypress/integration/channels/slash_command/todo_spec.js
Labels: 2: Dev Review

#952 [MM-39899] Make restore idempotent
  server/api/playbooks.go
  server/app/playbook_service.go
Labels: 4: Reviews Complete

#946 MM-40684: Tests for team selection when creating a Playbook
  tests-e2e/cypress/integration/playbooks/creation_button_spec.js
Labels: 4: Reviews Complete

#944 MM-40305: Reorder checklists in RHS
  client/playbook_runs.go
  server/api/playbook_runs.go
  server/api_runs_test.go
  server/app/mocks/mock_playbook_run_service.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
  webapp/i18n/en.json
  webapp/src/actions.ts
  webapp/src/client.ts
  webapp/src/components/collapsible_checklist.tsx
  webapp/src/components/collapsible_checklist_hover_menu.tsx
  webapp/src/components/rhs/rhs_checklist.tsx
  webapp/src/components/rhs/rhs_checklist_list.tsx
  webapp/src/reducer.ts
  webapp/src/types/actions.ts
Labels: 2: Dev Review
