Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2021-10, with the labels that each got.

#786 [MM-38151]: add i18n ci check
  .circleci/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 4: Reviews Complete

#782 [MM-37223] Migrate SearchInput SCSS styles to styled-components
  webapp/src/components/backstage/runs_list/seach_input.scss
  webapp/src/components/backstage/runs_list/search_input.tsx
Labels: Hacktoberfest, hacktoberfest-accepted

#781 [GH-17954] migrate profile_button to styled component
  webapp/src/components/profile/profile_button.scss
  webapp/src/components/profile/profile_button.tsx
Labels: Hacktoberfest, hacktoberfest-accepted

#780 MM-38908: When clicking Run, navigate to the new URL provided by webapp
  plugin.json
  webapp/src/components/backstage/playbooks/playbook_backstage.tsx
Labels: 4: Reviews Complete

#788 Cherry-pick MM-38908: When clicking Run, navigate to the new URL provided by webapp (#780)
  plugin.json
  webapp/src/components/backstage/playbooks/playbook_backstage.tsx
Labels: 4: Reviews Complete

#779 [MM-38151] MM-38843, MM-37172: i18n, convert playbook overview
  server/api/stats.go
  server/sqlstore/stats.go
  tests-e2e/cypress/integration/backstage/playbook_overview_spec.js
  webapp/i18n/en.json
  webapp/src/components/backstage/playbooks/playbook_backstage.tsx
  webapp/src/components/backstage/playbooks/stats_view.tsx
  webapp/src/components/backstage/playbooks/upgrade_playbook_placeholder.tsx
  webapp/src/components/backstage/runs_list/runs_list.tsx
  webapp/src/components/widgets/pill.tsx
  webapp/src/constants.ts
  webapp/src/types/stats.ts
Labels: 4: Reviews Complete

#783 [MM-37225] Migrate Profile component from SCSS to styled-component
  webapp/src/components/profile/profile.scss
  webapp/src/components/profile/profile.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#793 tweak case of "Finished runs" and "Run name"
  tests-e2e/cypress/integration/backstage/playbook_run_list_spec.js
  webapp/src/components/backstage/runs_list/filters.tsx
  webapp/src/components/backstage/runs_list/run_list_header.tsx
Labels: 4: Reviews Complete, AutoMerge

#726 Mm 34850 multiple web hooks
  server/api/playbook_runs.go
  server/api/playbook_runs_test.go
  server/api/playbooks.go
  server/api/playbooks_test.go
  server/app/playbook.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/app/playbook_run_service_test.go
  server/app/playbook_test.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_run.go
  server/telemetry/rudder.go
  server/telemetry/rudder_test.go
  tests-e2e/cypress/integration/frontstage/playbook_run_automation_spec.js
  tests-e2e/cypress/support/plugin/api_commands.js
  webapp/src/components/backstage/automation/patterned_text_area.tsx
  webapp/src/components/backstage/automation/settings.tsx
  webapp/src/components/backstage/playbook_edit.tsx
  webapp/src/types/playbook.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#775 MM-38668 - Send digest once a day when user logs on
  build/custom.mk
  server/api/bot.go
  server/app/mocks/mock_playbook_run_service.go
  server/app/mocks/mock_user_info_store.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/app/user_info.go
  server/command/command.go
  server/plugin.go
  server/sqlstore/migrations.go
  server/sqlstore/user_info.go
  server/sqlstore/user_info_test.go
  webapp/src/client.ts
  webapp/src/index.tsx
Labels: 2: Dev Review

#776 MM-38872 - Telemetry for the todo message
  server/app/playbook_run_service.go
  webapp/src/components/rhs/rhs_run_details.tsx
Labels: 4: Reviews Complete

#777 MM-38670 - Design polish
  server/app/playbook_run_service.go
Labels: 4: Reviews Complete
