Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2022-07, with the labels that each got.

#1277 MM-44721: Run Details Page > RHS > Key metrics
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_activity.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_metrics.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_styles.tsx
Labels: 4: Reviews Complete

#1276 Mm 44766 participants
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_participants.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/send_message_button.tsx
  webapp/src/components/profile/profile_selector.tsx
Labels: 2: Dev Review

#1281 MM-45446: Auto scroll infrastructure
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/checklists.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/retrospective.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/summary.tsx
  webapp/src/components/rhs/rhs_checklist_list.tsx
Labels: 4: Reviews Complete

#1287 MM-45412: Fix categorization of users in owner dropdown list
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
  webapp/src/components/checklist_item/assign_to.tsx
Labels: 4: Reviews Complete

#1285 Mm 44852 request an update
  assets/i18n/en.json
  client/playbook_runs.go
  server/api/playbook_runs.go
  server/api_runs_test.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  webapp/i18n/en.json
  webapp/src/client.ts
  webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx
  webapp/src/components/backstage/toast_banner.tsx
Labels: 2: Dev Review

#1286 MM-45090: Track channel action update
  server/api/actions.go
  server/app/action.go
  server/app/actions_service.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
Labels: 4: Reviews Complete

#1279 MM-44500: fix template item hover, fix playbook menu being clipped
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/templates/template_item.tsx
Labels: 2: Dev Review

#1284 Refactor logic from createPlaybookRun
  server/api/playbook_runs.go
  server/app/playbook_run.go
Labels: 2: Dev Review

#1280 Reset page to 0 after update the params with the search param
  tests-e2e/cypress/integration/playbooks/pagination_spec.js
  webapp/src/hooks/crud.ts
Labels: 2: Dev Review

#1267 Mm 45156 RDP initial cypress e2e
  tests-e2e/cypress/integration/runs/actions_spec.js
  tests-e2e/cypress/integration/runs/rdp_general_spec.js
  tests-e2e/cypress/integration/runs/rdp_main_checklist_spec.js
  tests-e2e/cypress/integration/runs/rdp_main_finish_spec.js
  tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
  tests-e2e/cypress/integration/runs/rdp_main_retrospective_spec.js
  tests-e2e/cypress/integration/runs/rdp_main_statusupdate_spec.js
  tests-e2e/cypress/integration/runs/rdp_main_summary_spec.js
  webapp/src/components/backstage/playbook_runs/playbook_run/checklists.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/finish_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/header_button.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/retrospective.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_status_updates.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/summary.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
  webapp/src/components/backstage/status_badge.tsx
  webapp/src/components/broadcast_channel_selector.tsx
  webapp/src/components/patterned_text_area.tsx
  webapp/src/components/rhs/rhs_about_buttons.tsx
  webapp/src/components/rhs/rhs_title.tsx
  webapp/src/components/run_actions_modal.tsx
  webapp/src/selectors.ts
Labels: 4: Reviews Complete

#1266 Add endpoints for categories
  server/api/categories.go
  server/app/category.go
  server/app/category_service.go
  server/plugin.go
  server/sqlstore/category.go
  server/sqlstore/migrations.go
  server/sqlstore/store_test.go
  server/sqlstore/support_for_test.go
  server/sqlstore/user_info_test.go
Labels: 2: Dev Review

#1290 Use Toaster
  webapp/src/components/backstage/playbook_editor/controls.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx
  webapp/src/components/backstage/playbooks/playbook.tsx
  webapp/src/components/backstage/toast_banner.tsx
  webapp/src/hooks/crud.ts
Labels: 1: PM Review, 2: Dev Review

#1292 View all updates fix
  tests-e2e/cypress/integration/runs/rdp_rhs_statusupdates_spec.js
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/update_card.tsx
Labels: 4: Reviews Complete

#1291 MM-44548, MM-44816: Fix dnd jumps/glitches in playbook editor
  webapp/src/components/checklist/checklist_list.tsx
Labels: 2: Dev Review

#1300 MM-45345, MM-45346: Fix all the dropdowns
  tests-e2e/cypress/integration/channels/rhs/checklist_spec.js
  tests-e2e/cypress/integration/playbooks/edit_spec.js
  webapp/src/components/backstage/playbook_editor/controls.tsx
  webapp/src/components/backstage/playbook_editor/outline/inputs/broadcast_channels_selector.tsx
  webapp/src/components/backstage/playbook_editor/outline/inputs/webhooks_input.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
  webapp/src/components/backstage/runs_list/playbook_selector.tsx
  webapp/src/components/checklist_item/assign_to.tsx
  webapp/src/components/checklist_item/checklist_item.tsx
  webapp/src/components/checklist_item/command.tsx
  webapp/src/components/checklist_item/duedate.tsx
  webapp/src/components/checklist_item/hover_menu.tsx
  webapp/src/components/checklist_item_input.tsx
  webapp/src/components/command_input.tsx
  webapp/src/components/datetime_selector.tsx
  webapp/src/components/dot_menu.tsx
  webapp/src/components/dropdown.tsx
  webapp/src/components/profile/profile_selector.tsx
  webapp/src/components/team/team_selector.tsx
  webapp/src/hooks/general.ts
Labels: 2: Dev Review

#1304 Mm 45608 create public playbooks from rhs when no e20
  webapp/src/components/rhs/rhs_home.tsx
Labels: 2: Dev Review

#1306 MM-45609, MM-45610: fix team selector nav issue, fix command open/close
  webapp/src/components/checklist_item/command.tsx
  webapp/src/components/create_playbook_modal.tsx
  webapp/src/components/dropdown.tsx
  webapp/src/components/team/team_selector.tsx
  webapp/src/components/widgets/generic_modal.tsx
Labels: 2: Dev Review

#1303 Mm 45351 viewer test rdp
  tests-e2e/cypress/integration/runs/rdp_main_checklist_spec.js
  tests-e2e/cypress/integration/runs/rdp_main_retrospective_spec.js
  tests-e2e/cypress/integration/runs/rdp_main_summary_spec.js
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_runs/playbook_run/retrospective.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/summary.tsx
Labels: 2: Dev Review

#1293 [MM-44757] Restrict runs and playbooks in LHS
  server/api/categories.go
  server/app/category.go
  server/plugin.go
  server/sqlstore/category.go
  webapp/src/client.ts
  webapp/src/components/sidebar/playbooks_sidebar.tsx
  webapp/src/hooks/crud.ts
  webapp/src/types/category.ts
Labels: 2: Dev Review

#1289 MM-45474: Add active state to header buttons
  webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/header_button.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
Labels: 4: Reviews Complete

#1302 MM-45520: Run Details Page - RHS Info links
  webapp/i18n/en.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/backstage/playbook_edit/metrics/metric_edit.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/retrospective.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_activity.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_metrics.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_styles.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/metrics/metric_input.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/metrics/metrics_data.tsx
  webapp/src/components/backstage/playbook_runs/shared.tsx
  webapp/src/hooks/general.ts
Labels: 4: Reviews Complete

#1295 Mm44851 get involved
  assets/i18n/en.json
  client/playbook_runs.go
  server/api/playbook_runs.go
  server/api_runs_test.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
  webapp/i18n/en.json
  webapp/src/client.ts
  webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
Labels: 1: UX Review, 2: Dev Review

#1313 MM-45346: fix duedate selector in hover menu
  webapp/src/components/create_playbook_modal.tsx
  webapp/src/components/datetime_selector.tsx
  webapp/src/components/dropdown.tsx
  webapp/src/components/team/team_selector.tsx
Labels: 2: Dev Review

#1310 Add view all links
  webapp/i18n/en.json
  webapp/src/components/sidebar/group.tsx
  webapp/src/components/sidebar/item.tsx
  webapp/src/components/sidebar/playbooks_sidebar.tsx
  webapp/src/components/sidebar/sidebar.tsx
Labels: 1: UX Review, 2: Dev Review

#1308 recover kebab and request update as participant
  tests-e2e/cypress/integration/runs/rdp_main_statusupdate_spec.js
  webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx
Labels: 2: Dev Review

#1314 Rdp ux feedback batch
  webapp/src/components/backstage/playbook_runs/playbook_run/finish_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/summary.tsx
Labels: 2: Dev Review

#1317 MM-45575 Playbook member migration.
  server/sqlstore/migrations.go
  server/sqlstore/store_test.go
  server/sqlstore/user_info_test.go
Labels: 4: Reviews Complete

#1323 use followers noun to be consistent
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
Labels: 4: Reviews Complete

#1318 MM-45664: Make buttons non-editable for viewers
  webapp/src/components/checklist_item/assign_to.tsx
  webapp/src/components/checklist_item/command.tsx
  webapp/src/components/checklist_item/duedate.tsx
  webapp/src/components/checklist_item/hover_menu.tsx
  webapp/src/components/profile/profile_selector.tsx
Labels: 4: Reviews Complete

#1319 finish run to last pos + get involved modal + no-navigate
  tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
Labels: 4: Reviews Complete

#1315 fine tune run title control + toggle open in dotmenu
  webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
  webapp/src/components/dot_menu.tsx
Labels: 4: Reviews Complete

#1320 MM-45676: Increase margin between title and checklist box
  webapp/src/components/rhs/rhs_checklist_list.tsx
Labels: 2: Dev Review

#1316 fix rhs issues
  webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
Labels: 2: Dev Review

#1309 track role data for playbookRun + new events preparation
  server/telemetry/rudder.go
  server/telemetry/rudder_test.go
  webapp/src/client.ts
  webapp/src/components/backstage/playbook_editor/outline/outline.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/retrospective.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/overview.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/retrospective.tsx
  webapp/src/components/backstage/playbooks/metrics/playbook_key_metrics.tsx
  webapp/src/components/backstage/playbooks/playbook_usage.tsx
  webapp/src/components/rhs/rhs_run_details.tsx
  webapp/src/hooks/telemetry.ts
  webapp/src/types/telemetry.ts
Labels: 2: Dev Review

#1325 Filter playbooks for LHS
  server/api/categories.go
  server/app/playbook.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_test.go
Labels: 2: Dev Review

#1324 requested update timeline event
  client/playbook_run.go
  server/api_runs_test.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_activity.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/timeline_utils.ts
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline_event_item.tsx
  webapp/src/types/rhs.ts
Labels: 2: Dev Review

#1328 [MM-45728] Favoriting runs
  webapp/src/components/backstage/playbook_editor/playbook_editor.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
  webapp/src/hooks/general.ts
Labels: 2: Dev Review

#1327 MM-44754, MM-45087: Playbooks LHS Team Sidebar
  tests-e2e/cypress/integration/navigation_spec.js
  tests-e2e/cypress/integration/playbooks/feedback_spec.js
  webapp/i18n/en.json
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/main_body.tsx
  webapp/src/components/backstage/playbook_editor/playbook_editor.tsx
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
  webapp/src/components/backstage/playbooks/metrics/metrics_run_list.tsx
  webapp/src/components/backstage/runs_list/filters.tsx
  webapp/src/components/backstage/runs_list/runs_list.tsx
  webapp/src/components/backstage/runs_page.tsx
  webapp/src/components/create_playbook_modal.tsx
  webapp/src/components/sidebar/group.tsx
  webapp/src/components/sidebar/item.tsx
  webapp/src/components/sidebar/playbooks_sidebar.tsx
  webapp/src/components/sidebar/sidebar.tsx
  webapp/src/hooks/crud.ts
  webapp/src/hooks/general.ts
  webapp/src/index.tsx
Labels: 2: Dev Review

#1329 add 72px to avoid teambar in max-width calculations
  tests-e2e/cypress/integration/runs/list_spec.js
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
Labels: 2: Dev Review

#1330 Fix category store
  server/sqlstore/category.go
  server/sqlstore/category_test.go
Labels: 4: Reviews Complete

#1343 LHS: remove experimental checks (e.g. narrow-width runs/playbooks)
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/backstage/runs_page.tsx
Labels: 2: Dev Review

#1340 change e2e to avoid mixing state
  tests-e2e/cypress/integration/runs/rdp_main_retrospective_spec.js
Labels: 2: Dev Review

#1339 Add favoriting telemetry
  server/app/category.go
  server/app/category_service.go
  server/plugin.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
Labels: 2: Dev Review

#1344 Switch Favorite to favorites
  webapp/i18n/en.json
  webapp/src/components/backstage/lhs_navigation.tsx
  webapp/src/components/sidebar/playbooks_sidebar.tsx
  webapp/src/hooks/general.ts
Labels: 2: Dev Review

#1336 migrate RHS UI management to cssgrid
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx
  webapp/src/components/checklist_item/assign_to.tsx
Labels: 2: Dev Review

#1353 force padding at rdp participants
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_participants.tsx
Labels: 2: Dev Review

#1346 Improve copies for the new Run details page viewer actions
  assets/i18n/en.json
  tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx
Labels: 1. Editor Review

#1351 Collapse categories
  server/api/categories.go
  server/sqlstore/category.go
  webapp/src/client.ts
  webapp/src/components/sidebar/group.tsx
  webapp/src/components/sidebar/item.tsx
  webapp/src/components/sidebar/playbooks_sidebar.tsx
  webapp/src/components/sidebar/sidebar.tsx
Labels: 1: PM Review, 2: Dev Review

#1354 extract from redux event filters
  webapp/src/actions.ts
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_timeline.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/timeline_utils.ts
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline_retro.tsx
  webapp/src/reducer.ts
  webapp/src/selectors.ts
  webapp/src/types/actions.ts
  webapp/src/types/rhs.ts
Labels: 2: Dev Review

#1361 remove unneeded team selector from import flow
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/backstage/playbook_list_row.tsx
Labels: 2: Dev Review

#1352 Mm 45834 leave run
  server/api/playbook_runs.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  webapp/i18n/en.json
  webapp/src/client.ts
  webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
  webapp/src/components/backstage/playbook_runs/shared.tsx
  webapp/src/components/backstage/toast_banner.tsx
Labels: 2: Dev Review

#1367 fav icons and small issues for RDP
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_editor/playbook_editor.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
Labels: 2: Dev Review

#1365 Add hiding due date if task is done
  webapp/src/components/checklist_item/checklist_item.tsx
Labels: 2: Dev Review

#1363 e2e: Update Cypress
  .circleci/config.yml
  tests-e2e/cypress.config.js
  tests-e2e/cypress.json
  tests-e2e/cypress/integration/channels/general_actions_spec.js
  tests-e2e/cypress/integration/playbooks/edit_spec.js
  tests-e2e/cypress/integration/runs/rdp_rhs_runinfo_spec.js
  tests-e2e/cypress/support/e2e.js
  tests-e2e/package-lock.json
  tests-e2e/package.json
Labels: 4: Reviews Complete

#1368 Honour MetricsSettings.Enable
  server/plugin.go
Labels: 4: Reviews Complete

#1350 MM-42660 - Timeline event for status update snooze
  client/client.go
  client/reminder.go
  client/reminders.go
  server/api/playbook_runs.go
  server/api_runs_test.go
  server/app/playbook_run.go
  server/app/reminder.go
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline_event_item.tsx
  webapp/src/types/rhs.ts
Labels: 4: Reviews Complete

#1358 bump: react-select to fix react-17 white screen crashes
  webapp/package-lock.json
  webapp/package.json
Labels: 2: Dev Review

#1364 MM-45575 GraphQL updates for LHS list
  server/api/graphql.go
  server/api/graphql_playbook.go
  server/api/graphql_root.go
  server/api/graphql_run.go
  server/api/schema.graphqls
  server/api_graphql_playbooks_test.go
  server/plugin.go
  webapp/src/components/sidebar/playbooks_sidebar.tsx
  webapp/src/graphql/generated_types.ts
  webapp/src/graphql/hooks.ts
  webapp/src/graphql/playbook.graphql
  webapp/src/graphql/runs.graphql
  webapp/src/graphql_client.ts
  webapp/src/hooks/general.ts
  webapp/src/hooks/routing.ts
  webapp/src/index.tsx
Labels: 2: Dev Review
