Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2022-06, with the labels that each got.

#1192 MM-44323: disable duplicate if disallowed
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_editor/controls.tsx
  webapp/src/components/backstage/playbook_list_row.tsx
  webapp/src/components/dot_menu.tsx
Labels: 1: UX Review

#1226 Add cmd+enter support
  webapp/src/components/rhs/rhs_about_description.tsx
Labels: 2: Dev Review

#1227 Make plugin fetch consistant with webapp fetch.
  webapp/src/client.ts
  webapp/src/index.tsx
Labels: 2: Dev Review

#1182 [MM-42914] Scan SlackAttachments for trigger
  server/app/actions_service.go
Labels: 2: Dev Review, 3: QA Review, Lifecycle/1:stale

#1235 Fix periods
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_edit/retrospective_edit.tsx
  webapp/src/components/backstage/playbook_editor/outline/section_retrospective.tsx
  webapp/src/components/templates/template_data.tsx
Labels: 4: Reviews Complete

#1237 MM-44745: go directly to outline in single-team envs
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/templates/template_selector.tsx
Labels: 2: Dev Review

#1238 Mm 44716 add main checklist
  webapp/src/components/backstage/playbook_runs/playbook_run/checklists.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
  webapp/src/components/backstage/playbook_runs/shared.tsx
  webapp/src/components/rhs/rhs_checklist_list.tsx
Labels: 2: Dev Review

#1232 Add summary section to main form
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook_run.go
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/summary.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/retrospective.tsx
  webapp/src/types/playbook_run.ts
Labels: 2: Dev Review

#1240 MM-44770: fix run name & summary saving
  webapp/src/components/rhs/rhs_about_description.tsx
  webapp/src/components/rhs/rhs_about_title.tsx
Labels: 4: Reviews Complete, CherryPick/Candidate

#1236 MM-44763: allow direct dropdown editing again
  webapp/src/components/checklist_item/checklist_item.tsx
Labels: 1: UX Review

#1239 RHS support rundetails
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_editor/outline/outline.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs.tsx
  webapp/src/components/checklist/checklist_list.tsx
  webapp/src/components/rhs/rhs_checklist_list.tsx
  webapp/src/components/rhs/rhs_run_details.tsx
Labels: 4: Reviews Complete

#1242 MM-44748 Basic new LHS layout.
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/lhs_navigation.tsx
  webapp/src/components/backstage/main_body.tsx
  webapp/src/index.tsx
Labels: 4: Reviews Complete

#1243 Add menu component
  webapp/src/components/widgets/menu/menu.tsx
  webapp/src/components/widgets/menu/menu_group.tsx
  webapp/src/components/widgets/menu/menu_item.tsx
  webapp/src/components/widgets/menu/menu_wrapper.tsx
Labels: 2: Dev Review

#1246 Playbook sidebar starter
  webapp/src/components/sidebar/group.tsx
  webapp/src/components/sidebar/item.tsx
  webapp/src/components/sidebar/sidebar.tsx
Labels: 2: Dev Review

#1250 Add playbooks and runs in sidebar
  webapp/src/components/assets/icons/playbook_run_icon.tsx
  webapp/src/components/assets/icons/private_playbook_icon.tsx
  webapp/src/components/backstage/lhs_navigation.tsx
  webapp/src/components/sidebar/item.tsx
  webapp/src/components/sidebar/playbooks_sidebar.tsx
  webapp/src/components/sidebar/sidebar.tsx
Labels: 1: UX Review, 2: Dev Review

#1244 Mm 44715 RDP status update - finish run
  client/playbook_run.go
  client/playbook_runs.go
  server/api/playbook_runs.go
  server/api_runs_test.go
  server/app/playbook_run.go
  webapp/i18n/en.json
  webapp/src/client.ts
  webapp/src/components/backstage/playbook_runs/playbook_run/checklists.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/finish_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/index.ts
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_status_updates.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/summary.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/update_card.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/retrospective.tsx
  webapp/src/components/backstage/playbook_runs/shared.tsx
  webapp/src/components/dot_menu.tsx
  webapp/src/components/rhs/rhs_post_update.tsx
  webapp/src/components/sidebar/playbooks_sidebar.tsx
  webapp/src/components/time_spec.tsx
  webapp/src/types/playbook_run.ts
Labels: 2: Dev Review

#1252 MM-44962: Playbooks List and Playbook Editor UI changes to match new LHS experience
  webapp/i18n/en.json
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/backstage_list_header.tsx
  webapp/src/components/backstage/playbook_editor/playbook_editor.tsx
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/backstage/playbook_list_row.tsx
  webapp/src/components/pagination_row.tsx
  webapp/src/components/templates/template_item.tsx
  webapp/src/components/templates/template_selector.tsx
  webapp/src/components/widgets/header.tsx
  webapp/src/types/global.d.ts
Labels: 4: Reviews Complete

#1254 MM-45127: Fix scroll-to section in playbook editor.
  webapp/src/hooks/general.ts
Labels: 4: Reviews Complete

#1251 Mm 44713 add header
  webapp/i18n/en.json
  webapp/src/client.ts
  webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/header_button.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/summary.tsx
  webapp/src/components/modals/update_run_status_modal.tsx
  webapp/src/hooks/general.ts
Labels: 2: Dev Review

#1248 Mm 44717 add retrospective
  webapp/src/components/backstage/playbook_runs/playbook_run/finish_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/retrospective.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/metrics/metrics_data.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/report.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/retrospective.tsx
  webapp/src/hooks/crud.ts
Labels: 2: Dev Review

#1256 RDP header sticky when doing scroll
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
Labels: 4: Reviews Complete

#1249 Translations update from Mattermost Weblate
  assets/i18n/sv.json
  webapp/i18n/de.json
  webapp/i18n/en_AU.json
  webapp/i18n/hr.json
  webapp/i18n/hu.json
  webapp/i18n/ja.json
  webapp/i18n/nl.json
  webapp/i18n/pl.json
  webapp/i18n/sv.json
  webapp/i18n/tr.json
Labels: Do Not Merge/Mattermod

#1255 Configure playbooks for Notice.txt file auto-generation
  .config/notice-file/Readme.md
  .config/notice-file/config.yaml
Labels: 4: Reviews Complete

#1262 MM-44718 finish run extacted to hook
  webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/finish_run.tsx
Labels: 4: Reviews Complete

#1221 Mm 20021
  tests-e2e/cypress/integration/channels/rhs/template_spec.js
  webapp/src/components/backstage/playbook_editor/playbook_editor.tsx
  webapp/src/components/rhs/rhs_home.tsx
  webapp/src/components/templates/template_data.tsx
Labels: 3: QA Review, Lifecycle/frozen

#1261 Mm 45182 mm 45183 UI improvements
  webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/retrospective.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/summary.tsx
  webapp/src/components/rhs/rhs_checklist_list.tsx
Labels: 2: Dev Review

#1260 MM-44964: Runs List design revamp for LHS
  webapp/i18n/en.json
  webapp/src/components/backstage/backstage_list_header.tsx
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/backstage/runs_list/filters.tsx
  webapp/src/components/backstage/runs_list/row.tsx
  webapp/src/components/backstage/runs_list/run_list_header.tsx
  webapp/src/components/backstage/runs_list/runs_list.tsx
  webapp/src/components/backstage/runs_page.tsx
  webapp/src/components/backstage/styles.tsx
  webapp/src/components/sidebar/playbooks_sidebar.tsx
  webapp/src/components/team/team_selector.tsx
  webapp/src/hooks/general.ts
Labels: 1: UX Review, 2: Dev Review

#1263 fix state management when chaging run in lhs
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/retrospective.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_status_updates.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/metrics/metrics_data.tsx
  webapp/src/hooks/general.ts
  webapp/src/selectors.ts
Labels: 4: Reviews Complete

#1270 hackaton task inbox - prepare task list
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/rhs/rhs.tsx
  webapp/src/components/backstage/rhs/task_inbox/task.tsx
  webapp/src/components/backstage/rhs/task_inbox/task_inbox.tsx
Labels: 4: Reviews Complete

#1259 Mm 45108 viewer mode
  webapp/src/actions.ts
  webapp/src/components/backstage/playbook_editor/outline/outline.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/checklists.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
  webapp/src/components/checklist/checklist_list.tsx
  webapp/src/components/checklist/generic_checklist.tsx
  webapp/src/components/checklist_item/checklist_item_draggable.tsx
  webapp/src/components/rhs/rhs_checklist.tsx
  webapp/src/components/rhs/rhs_checklist_list.tsx
  webapp/src/components/rhs/rhs_run_details.tsx
  webapp/src/reducer.ts
  webapp/src/selectors.ts
  webapp/src/types/actions.ts
Labels: 4: Reviews Complete

#1257 Add create playbook dropdown
  webapp/i18n/en.json
  webapp/src/components/sidebar/create_playbook_dropdown.tsx
  webapp/src/components/sidebar/playbooks_sidebar.tsx
Labels: 2: Dev Review

#1273 MM-45401: Ellipsize Playbook link in Run Details Page RHS
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
Labels: 4: Reviews Complete
