Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2022-10, with the labels that each got.

#1478 Mm 45998 clear playbook before saving
  client/playbook.go
  server/api/graphql_root_playbook.go
  server/api/playbooks.go
  server/api_graphql_playbooks_test.go
  server/api_playbooks_test.go
Labels: 2: Dev Review

#1497 Mm 46916 lhs not refreshed after unfollow
  tests-e2e/cypress/integration/lhs_spec.js
  webapp/src/components/backstage/lhs_run_dot_menu.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
Labels: 2: Dev Review

#1499 Remove old checklists and related code.
  webapp/i18n/en.json
  webapp/src/components/backstage/bar_graph.tsx
  webapp/src/components/backstage/line_graph.tsx
  webapp/src/components/backstage/main_body.tsx
  webapp/src/components/backstage/metrics/metrics_card.tsx
  webapp/src/components/backstage/metrics/metrics_row.tsx
  webapp/src/components/backstage/metrics/metrics_run_list.tsx
  webapp/src/components/backstage/metrics/metrics_run_list_header.tsx
  webapp/src/components/backstage/metrics/metrics_stats_view.tsx
  webapp/src/components/backstage/metrics/no_metrics_placeholder.tsx
  webapp/src/components/backstage/metrics/playbook_key_metrics.tsx
  webapp/src/components/backstage/metrics/upgrade_key_metrics_placeholder.tsx
  webapp/src/components/backstage/playbook_editor/outline/section_retrospective.tsx
  webapp/src/components/backstage/playbook_editor/playbook_editor.tsx
  webapp/src/components/backstage/playbook_preview_cards.tsx
  webapp/src/components/backstage/playbook_usage.tsx
  webapp/src/components/backstage/playbooks/playbook.tsx
  webapp/src/components/backstage/playbooks/playbook_preview.tsx
  webapp/src/components/backstage/playbooks/playbook_preview_actions.tsx
  webapp/src/components/backstage/playbooks/playbook_preview_badges.tsx
  webapp/src/components/backstage/playbooks/playbook_preview_checklists.tsx
  webapp/src/components/backstage/playbooks/playbook_preview_description.tsx
  webapp/src/components/backstage/playbooks/playbook_preview_navbar.tsx
  webapp/src/components/backstage/playbooks/playbook_preview_retrospective.tsx
  webapp/src/components/backstage/playbooks/playbook_preview_section.tsx
  webapp/src/components/backstage/playbooks/playbook_preview_status_updates.tsx
  webapp/src/components/backstage/stats_view.tsx
  webapp/src/components/backstage/upgrade_playbook_placeholder.tsx
  webapp/src/components/checklist_item_input.tsx
  webapp/src/components/collapsible_checklist.tsx
  webapp/src/components/collapsible_checklist_hover_menu.tsx
  webapp/src/components/rhs/rhs_checklists_add_dialog.tsx
  webapp/src/components/rhs/rhs_checklists_delete_dialog.tsx
  webapp/src/components/rhs/rhs_checklists_rename_dialog.tsx
Labels: 2: Dev Review

#1504 I18n: codeowners for auto-request PR reviews
  CODEOWNERS
Labels: 4: Reviews Complete

#1501 move participant request-update cases behind professional license
  tests-e2e/cypress/integration/channels/slash_command/test_spec.js
  tests-e2e/cypress/integration/runs/rdp_main_statusupdate_spec.js
  tests-e2e/cypress/support/api/preference.js
  webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx
Labels: 4: Reviews Complete

#1500 Mm 46914 refresh lhs after starting run
  tests-e2e/cypress/integration/playbooks/overview_spec.js
  webapp/src/actions.ts
  webapp/src/components/backstage/playbook_editor/controls.tsx
  webapp/src/components/backstage/playbook_list_row.tsx
  webapp/src/components/modals/run_playbook_modal.tsx
Labels: 2: Dev Review

#1503 remove unused local svg icons
  tests-e2e/cypress/integration/lhs_spec.js
  webapp/src/components/assets/icons/alert_icon.tsx
  webapp/src/components/assets/icons/dot_menu_icon.tsx
  webapp/src/components/assets/icons/file_icon.tsx
  webapp/src/components/assets/icons/plus_icon.tsx
Labels: 2: Dev Review

#1505 Migrate upgrade_badge icon usage to compass icons.
  webapp/src/components/assets/buttons.tsx
  webapp/src/components/backstage/playbook_edit/metrics/metrics.tsx
  webapp/src/components/backstage/public_private_selector.tsx
  webapp/src/components/backstage/upgrade_badge.tsx
  webapp/src/components/post_menu.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#1511 MM-47454: Introduce a highly visible feedback button
  webapp/i18n/en.json
  webapp/src/components/assets/buttons.tsx
  webapp/src/components/checklist/checklist_list.tsx
  webapp/src/components/give_feedback_button.tsx
  webapp/src/components/global_header_right.tsx
  webapp/src/index.tsx
Labels: 2: Dev Review

#1488 1414 1445 manage participants list rdp
  server/api/graphql_root_run.go
  server/api/schema.graphqls
  server/api_graphql_runs_test.go
  tests-e2e/cypress/integration/runs/rdp_main_statusupdate_spec.js
  tests-e2e/cypress/integration/runs/rdp_rhs_participants_spec.js
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_participants.tsx
  webapp/src/components/backstage/search_input.tsx
  webapp/src/components/backstage/shared.tsx
  webapp/src/components/dot_menu.tsx
  webapp/src/components/profile/profile_selector.tsx
  webapp/src/graphql/generated_types.ts
  webapp/src/graphql/hooks.ts
  webapp/src/graphql/runs.graphql
  webapp/src/hooks/crud.ts
Labels: 2: Dev Review

#1515 MM-47558: fix a crash re: status update posts
  tests-e2e/cypress/integration/channels/post_type_components_spec.js
  webapp/src/components/update_post.tsx
Labels: 2: Dev Review

#1514 reduce GraphQL error logs
  server/api/graphql.go
  server/api/graphql_root_playbook.go
  server/api/graphql_root_run.go
  server/app/permissions_service.go
Labels: 4: Reviews Complete

#1495 Morph v0.10.0 v0.15.0
  server/sqlstore/migrations/mysql/000024_update_created_at_deleted_at_in_ir_incident.down.sql
  server/sqlstore/migrations/mysql/000024_update_created_at_deleted_at_in_ir_incident.up.sql
  server/sqlstore/migrations/mysql/000025_add_announcement_channel_id_to_ir_incident.down.sql
  server/sqlstore/migrations/mysql/000025_add_announcement_channel_id_to_ir_incident.up.sql
  server/sqlstore/migrations/mysql/000026_add_announcement_channel_id_to_ir_playbook.down.sql
  server/sqlstore/migrations/mysql/000026_add_announcement_channel_id_to_ir_playbook.up.sql
  server/sqlstore/migrations/mysql/000027_add_announcement_channel_enabled_to_ir_playbook.down.sql
  server/sqlstore/migrations/mysql/000027_add_announcement_channel_enabled_to_ir_playbook.up.sql
  server/sqlstore/migrations/mysql/000028_add_webhook_on_creation_url_to_ir_incident.down.sql
  server/sqlstore/migrations/mysql/000028_add_webhook_on_creation_url_to_ir_incident.up.sql
  server/sqlstore/migrations/mysql/000029_add_webhook_on_creation_url_to_ir_playbook.down.sql
  server/sqlstore/migrations/mysql/000029_add_webhook_on_creation_url_to_ir_playbook.up.sql
  server/sqlstore/migrations/mysql/000030_add_webhook_on_creation_enabled_to_ir_playbook.down.sql
  server/sqlstore/migrations/mysql/000030_add_webhook_on_creation_enabled_to_ir_playbook.up.sql
  server/sqlstore/migrations/mysql/000031_add_concatenated_invited_group_ids_to_ir_incident.down.sql
  server/sqlstore/migrations/mysql/000031_add_concatenated_invited_group_ids_to_ir_incident.up.sql
  server/sqlstore/migrations/mysql/000032_add_concatenated_invited_group_ids_to_ir_playbook.down.sql
  server/sqlstore/migrations/mysql/000032_add_concatenated_invited_group_ids_to_ir_playbook.up.sql
  server/sqlstore/migrations/mysql/000033_add_retrospective_to_ir_incident.down.sql
  server/sqlstore/migrations/mysql/000033_add_retrospective_to_ir_incident.up.sql
  server/sqlstore/migrations/postgres/000024_update_created_at_deleted_at_in_ir_incident.down.sql
  server/sqlstore/migrations/postgres/000024_update_created_at_deleted_at_in_ir_incident.up.sql
  server/sqlstore/migrations/postgres/000025_add_announcement_channel_id_to_ir_incident.down.sql
  server/sqlstore/migrations/postgres/000025_add_announcement_channel_id_to_ir_incident.up.sql
  server/sqlstore/migrations/postgres/000026_add_announcement_channel_id_to_ir_playbook.down.sql
  server/sqlstore/migrations/postgres/000026_add_announcement_channel_id_to_ir_playbook.up.sql
  server/sqlstore/migrations/postgres/000027_add_announcement_channel_enabled_to_ir_playbook.down.sql
  server/sqlstore/migrations/postgres/000027_add_announcement_channel_enabled_to_ir_playbook.up.sql
  server/sqlstore/migrations/postgres/000028_add_webhook_on_creation_url_to_ir_incident.down.sql
  server/sqlstore/migrations/postgres/000028_add_webhook_on_creation_url_to_ir_incident.up.sql
  server/sqlstore/migrations/postgres/000029_add_webhook_on_creation_url_to_ir_playbook.down.sql
  server/sqlstore/migrations/postgres/000029_add_webhook_on_creation_url_to_ir_playbook.up.sql
  server/sqlstore/migrations/postgres/000030_add_webhook_on_creation_enabled_to_ir_playbook.down.sql
  server/sqlstore/migrations/postgres/000030_add_webhook_on_creation_enabled_to_ir_playbook.up.sql
  server/sqlstore/migrations/postgres/000031_add_concatenated_invited_group_ids_to_ir_incident.down.sql
  server/sqlstore/migrations/postgres/000031_add_concatenated_invited_group_ids_to_ir_incident.up.sql
  server/sqlstore/migrations/postgres/000032_add_concatenated_invited_group_ids_to_ir_playbook.down.sql
  server/sqlstore/migrations/postgres/000032_add_concatenated_invited_group_ids_to_ir_playbook.up.sql
  server/sqlstore/migrations/postgres/000033_add_retrospective_to_ir_incident.down.sql
  server/sqlstore/migrations/postgres/000033_add_retrospective_to_ir_incident.up.sql
  server/sqlstore/migrations_test.go
Labels: 4: Reviews Complete

#1484 Gh 1444 1443 add participate/follow button channel rhs
  server/api/playbook_runs.go
  server/api/telemetry.go
  server/app/telemetry.go
  server/telemetry/rudder.go
  tests-e2e/cypress/integration/channels/rhs/about_spec.js
  tests-e2e/cypress/integration/channels/rhs/title_spec.js
  tests-e2e/cypress/integration/lhs_spec.js
  tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
  tests-e2e/cypress/integration/runs/rdp_rhs_runinfo_spec.js
  webapp/i18n/en.json
  webapp/rudder_transform.js
  webapp/src/components/backstage/follow_button.tsx
  webapp/src/components/backstage/lhs_run_dot_menu.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
  webapp/src/components/backstage/runs_list/row.tsx
  webapp/src/components/rhs/rhs_about.tsx
  webapp/src/components/rhs/rhs_participants.tsx
  webapp/src/components/rhs/rhs_title.tsx
  webapp/src/hooks/general.ts
  webapp/src/hooks/index.ts
  webapp/src/hooks/run.tsx
  webapp/src/index.tsx
  webapp/src/types/telemetry.ts
Labels: 4: Reviews Complete

#1519 Updated CodeQL to use latest version
  .github/codeql/codeql-config.yml
  .github/workflows/codeql-analysis.yml
Labels: 4: Reviews Complete

#1522 1413 add participants
  server/api/graphql_root_run.go
  server/app/playbook_run_service.go
  tests-e2e/cypress/integration/runs/rdp_rhs_participants_spec.js
  webapp/i18n/en.json
  webapp/src/components/assets/buttons.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/add_participant_modal.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_participants.tsx
  webapp/src/components/backstage/profile_autocomplete.tsx
  webapp/src/components/profile/profile.tsx
  webapp/src/selectors.ts
  webapp/src/types/playbook_run.ts
Labels: 2: Dev Review

#1494 GH-20841 - Enable/Disable run status updates
  assets/i18n/en.json
  client/playbook_run.go
  server/api/playbook_runs.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/sqlstore/playbook_run.go
  webapp/i18n/en.json
  webapp/src/client.ts
  webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/controls.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/enable_disable_run_status_update.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/retrospective/timeline_event_item.tsx
  webapp/src/types/rhs.ts
Labels: 4: Reviews Complete

#1521 Modify the invite members flow to invite participants
  server/app/playbook_run_service.go
  tests-e2e/cypress/integration/playbooks/edit_spec.js
  tests-e2e/cypress/support/plugin/ui_commands.js
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_edit/automation/assign_owner_selector.tsx
  webapp/src/components/backstage/playbook_edit/automation/invite_users.tsx
  webapp/src/components/backstage/playbook_edit/automation/invite_users_selector.tsx
  webapp/src/components/backstage/playbook_edit/automation/menu_list.tsx
Labels: 2: Dev Review

#1523 remove unused code: icons, styles and some old conmponents
  webapp/i18n/en.json
  webapp/src/components/assets/buttons.tsx
  webapp/src/components/assets/left_dots.tsx
  webapp/src/components/assets/left_fade.tsx
  webapp/src/components/assets/modal.tsx
  webapp/src/components/assets/right_dots.tsx
  webapp/src/components/assets/right_fade.tsx
  webapp/src/components/backstage/playbook_runs/shared.tsx
  webapp/src/components/rhs/post_card.tsx
  webapp/src/components/rhs/rhs_shared.tsx
  webapp/src/components/tabs.tsx
  webapp/src/components/team/team_selector.tsx
  webapp/src/components/team/team_with_icon.tsx
Labels: 2: Dev Review

#1529 CI: store screenshots
  .circleci/config.yml
Labels: 2: Dev Review

#1513 [MM-21265] Checkbox to show/hide skipped tasks
  webapp/src/components/rhs/rhs_checklist_list.tsx
  webapp/src/types/playbook.ts
Labels: 1: UX Review, Hacktoberfest, hacktoberfest-accepted

#1518 Gh 1507 pb run actions joinleave
  client/playbook.go
  client/playbook_run.go
  client/playbook_runs.go
  server/api/graphql_root_playbook.go
  server/api/graphql_root_run.go
  server/api/playbook_runs.go
  server/api/schema.graphqls
  server/api_graphql_runs_test.go
  server/api_runs_test.go
  server/app/playbook.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/app/telemetry.go
  server/main_test.go
  server/plugin.go
  server/sqlstore/migrations.go
  server/sqlstore/migrations/future/mysql/0.60.down.sql
  server/sqlstore/migrations/future/mysql/0.60.up.sql
  server/sqlstore/migrations/future/postgres/0.60.down.sql
  server/sqlstore/migrations/future/postgres/0.60.up.sql
  server/sqlstore/playbook.go
  server/sqlstore/playbook_run.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
  tests-e2e/cypress/integration/channels/rhs/checklist_spec.js
  tests-e2e/cypress/integration/channels/rhs/status_update_spec.js
  tests-e2e/cypress/integration/channels/slash_command/todo_spec.js
  tests-e2e/cypress/integration/lhs_spec.js
  tests-e2e/cypress/integration/playbooks/edit_spec.js
  tests-e2e/cypress/integration/runs/permissions_spec.js
  tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
  tests-e2e/cypress/integration/runs/rdp_rhs_participants_spec.js
  tests-e2e/cypress/support/plugin/api_commands.js
  tests-e2e/cypress/support/plugin/ui_commands.js
  webapp/i18n/en.json
  webapp/rudder_transform.js
  webapp/src/actions.ts
  webapp/src/client.ts
  webapp/src/components/actions_modal.tsx
  webapp/src/components/actions_modal_action.tsx
  webapp/src/components/backstage/playbook_edit/automation/channel_access.tsx
  webapp/src/components/backstage/playbook_editor/controls.tsx
  webapp/src/components/backstage/playbook_editor/outline/outline.tsx
  webapp/src/components/backstage/playbook_editor/outline/section_actions.tsx
  webapp/src/components/backstage/playbook_editor/playbook_editor.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_participants.tsx
  webapp/src/components/playbook_actions_modal.tsx
  webapp/src/components/run_actions_modal.tsx
  webapp/src/graphql/generated_types.ts
  webapp/src/graphql/playbook.graphql
  webapp/src/graphql/runs.graphql
  webapp/src/reducer.ts
  webapp/src/selectors.ts
  webapp/src/types/actions.ts
  webapp/src/types/playbook.ts
  webapp/src/types/playbook_run.ts
  webapp/src/types/run_actions.ts
  webapp/src/types/telemetry.ts
Labels: 4: Reviews Complete

#1496 [MM-45052] Add error checking in insights API
  .circleci/config.yml
  go.mod
  go.sum
  server/api/playbooks.go
Labels: 4: Reviews Complete

#1517 [MM-46382] Make convert to private playbook more prominent
  webapp/src/components/backstage/convert_private_playbook_modal.tsx
  webapp/src/components/backstage/playbook_access_modal.tsx
  webapp/src/components/backstage/playbook_editor/controls.tsx
Labels: Hacktoberfest, hacktoberfest-accepted

#1528 Add DB migration info to README
  README.md
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#1533 MM-47980, MM-47981 Improve team limits
  server/api_playbooks_test.go
  server/api_runs_test.go
  server/app/permissions_service.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_run.go
  server/sqlstore/playbook_test.go
Labels: 4: Reviews Complete
