Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2022-09, with the labels that each got.

#1453 PBE: remove negative letter spacing and set wider min-width for context menu
  webapp/src/components/backstage/playbook_editor/controls.tsx
  webapp/src/components/backstage/playbook_editor/playbook_editor.tsx
Labels: 2: Dev Review

#1459 datetime selector: set custom error text
  webapp/i18n/en.json
  webapp/src/components/datetime_parsing.test.ts
  webapp/src/components/datetime_selector.tsx
  webapp/src/components/formatted_duration.test.tsx
Labels: 4: Reviews Complete

#1462 migrate fa icons to compass + fix pb assign owner clear
  server/api/graphql_root.go
  webapp/src/components/backstage/playbook_edit/automation/auto_assign_owner.tsx
  webapp/src/components/widgets/show_more.tsx
Labels: 2: Dev Review

#1438 Align OpenAPI spec to OpenAPI schema
  server/api/api.yaml
Labels: 4: Reviews Complete

#1460 migrate md icons to compass
  webapp/i18n/en.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/actions_modal.tsx
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/playbook_editor/controls.tsx
  webapp/src/components/backstage/playbook_editor/outline/section_actions.tsx
  webapp/src/components/backstage/playbook_list_row.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/finish_run.tsx
  webapp/src/components/backstage/runs_list/row.tsx
  webapp/src/components/modals/run_playbook_modal.tsx
  webapp/src/components/rhs/rhs_about_buttons.tsx
  webapp/src/components/rhs/rhs_home.tsx
  webapp/src/components/rhs/rhs_home_item.tsx
  webapp/src/components/rhs/rhs_post_update.tsx
  webapp/src/components/update_post.tsx
Labels: 4: Reviews Complete

#1461 Tsprune
  .ts-prunerc
  webapp/package-lock.json
  webapp/package.json
Labels: 4: Reviews Complete

#1440 Separate run participants base
  assets/i18n/en.json
  client/playbook_runs.go
  server/api/graphql_playbook.go
  server/api/graphql_root.go
  server/api/graphql_root_playbook.go
  server/api/graphql_root_run.go
  server/api/graphql_run.go
  server/api/playbook_runs.go
  server/api/schema.graphqls
  server/api_graphql_runs_test.go
  server/api_runs_test.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook_run.go
  server/sqlstore/playbook_run_test.go
  server/sqlstore/stats.go
  server/sqlstore/stats_test.go
  server/sqlstore/store_test.go
  server/sqlstore/support_for_test.go
  tests-e2e/cypress/integration/lhs_spec.js
  tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
  webapp/i18n/en.json
  webapp/src/client.ts
  webapp/src/components/backstage/lhs_run_dot_menu.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
  webapp/src/components/sidebar/playbooks_sidebar.tsx
  webapp/src/graphql/generated_types.ts
  webapp/src/graphql/hooks.ts
  webapp/src/graphql/playbook.graphql
  webapp/src/graphql/runs.graphql
Labels: 4: Reviews Complete

#1463 limit size for all incoming requests and migrate postgres text column
  .gitignore
  server/api/api.go
  server/api/graphql.go
  server/api_graphql_playbooks_test.go
  server/api_playbooks_test.go
  server/api_runs_test.go
  server/e2etest.config.json.sample
  server/main_test.go
  server/sqlstore/actions.go
  server/sqlstore/migrations.go
  server/sqlstore/migrations/future/mysql/0.59.down.sql
  server/sqlstore/migrations/future/mysql/0.59.up.sql
  server/sqlstore/migrations/future/postgres/0.59.down.sql
  server/sqlstore/migrations/future/postgres/0.59.up.sql
  server/sqlstore/migrations_utils.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_run.go
  server/sqlstore/store.go
  server/sqlstore/user_info.go
Labels: 2: Dev Review

#1341 cleanup after RDP release
  package-lock.json
  tests-e2e/cypress/integration/runs/actions_ignore.js
  tests-e2e/cypress/integration/runs/details_spec_ignore.js
  tests-e2e/cypress/integration/runs/metrics_ignore.js
  tests-e2e/cypress/integration/runs/retrospective_ignore.js
  tests-e2e/cypress/integration/runs/timeline_ignore.js
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_edit/metrics/metric_edit.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/following.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/header_button.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/index.ts
  webapp/src/components/backstage/playbook_runs/playbook_run/metrics/metric_input.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/metrics/metrics_data.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/retrospective.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/retrospective/report.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/retrospective/report_text_area.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/retrospective/timeline.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/retrospective/timeline_event_item.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_activity.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_styles.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_timeline.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/about.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/description.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/overview.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/participants.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/profile_w_position.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/updates.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/profile_vertical.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/retrospective.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/timeline_retro.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_details/export_link.tsx
  webapp/src/components/backstage/playbook_runs/shared.tsx
Labels: 4: Reviews Complete

#1456 Use new Start Run Dialog in Playbook List
  webapp/src/components/backstage/playbook_list_row.tsx
Labels: 2: Dev Review

#1469 MM-46829: Cherry-pick limit size incoming requests (v1.32/v7.3)
  server/api/api.go
  server/api/graphql.go
  server/api_graphql_playbooks_test.go
  server/api_playbooks_test.go
  server/api_runs_test.go
  server/sqlstore/actions.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_run.go
  server/sqlstore/store.go
  server/sqlstore/user_info.go
  tests-e2e/cypress/integration/lhs_spec.js
Labels: 2: Dev Review, 3: QA Review

#1271 Improved logging
  README.md
  build/custom.mk
  go.mod
  go.sum
  server/api/actions.go
  server/api/api.go
  server/api/bot.go
  server/api/categories.go
  server/api/context.go
  server/api/error_handler.go
  server/api/graphql.go
  server/api/graphql_root_playbook.go
  server/api/graphql_root_run.go
  server/api/logger.go
  server/api/playbook_runs.go
  server/api/playbooks.go
  server/api/settings.go
  server/api/signal.go
  server/api/stats.go
  server/api/telemetry.go
  server/api/urls.go
  server/api_graphql_runs_test.go
  server/app/actions_service.go
  server/app/permissions_service.go
  server/app/playbook_run_service.go
  server/app/reminder.go
  server/bot/bot.go
  server/bot/logger.go
  server/bot/mocks/mock_logger.go
  server/bot/poster.go
  server/command/command.go
  server/main_test.go
  server/metrics/service.go
  server/plugin.go
  server/sqlstore/actions.go
  server/sqlstore/actions_test.go
  server/sqlstore/category.go
  server/sqlstore/category_test.go
  server/sqlstore/migrations.go
  server/sqlstore/migrations_test.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_run.go
  server/sqlstore/playbook_run_test.go
  server/sqlstore/playbook_test.go
  server/sqlstore/stats.go
  server/sqlstore/stats_test.go
  server/sqlstore/store.go
  server/sqlstore/store_test.go
  server/sqlstore/support_for_test.go
  server/sqlstore/timeline_event_test.go
  server/sqlstore/user_info_test.go
  tests-e2e/package-lock.json
  tests-e2e/package.json
Labels: 4: Reviews Complete

#1471 MM-46829: Cherry-pick limit size incoming requests (v1.29, v7.1 & v7.2)
  .circleci/config.yml
  server/api/api.go
  server/api/graphql.go
  server/api_graphql_playbooks_test.go
  server/api_playbooks_test.go
  server/api_runs_test.go
  server/sqlstore/actions.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_run.go
  server/sqlstore/store.go
  server/sqlstore/user_info.go
Labels: 2: Dev Review, 3: QA Review

#1474 migrate missing icons from mdi to compass
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/backstage/playbook_editor/controls.tsx
  webapp/src/components/backstage/playbook_editor/outline/scroll_nav.tsx
  webapp/src/components/backstage/playbook_editor/outline/section_actions.tsx
  webapp/src/components/backstage/playbook_list_row.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/retrospective/timeline_event_item.tsx
  webapp/src/components/rhs/rhs_about_buttons.tsx
  webapp/src/components/rhs/rhs_home_item.tsx
  webapp/src/components/sidebar/create_playbook_dropdown.tsx
Labels: 4: Reviews Complete

#1476 more nesting allowed for pull requests
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 2: Dev Review

#1489 MM-47028 Use version of React DOM provided by web app
  webapp/webpack.config.js
Labels: 2: Dev Review, 3: QA Review

#1481 Private channel/playbook in run overview at RDP
  assets/i18n/en.json
  server/api/playbook_runs.go
  server/app/permissions_service.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  tests-e2e/cypress/integration/runs/rdp_rhs_runinfo_spec.js
  webapp/i18n/en.json
  webapp/src/client.ts
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
Labels: 4: Reviews Complete

#1470 Telemetry: new approach draft + PostUpdate viewed
  client/client.go
  client/telemetry.go
  server/api/telemetry.go
  server/api_telemetry_test.go
  server/app/telemetry.go
  server/plugin.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
  tests-e2e/cypress/integration/lhs_spec.js
  tests-e2e/cypress/integration/runs/rdp_general_spec.js
  tests-e2e/cypress/integration/runs/rdp_main_statusupdate_spec.js
  webapp/rudder_transform.js
  webapp/src/client.ts
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
  webapp/src/components/backstage/runs_list/row.tsx
  webapp/src/components/modals/run_playbook_modal.tsx
  webapp/src/components/modals/update_run_status_modal.tsx
  webapp/src/components/rhs/rhs_about.tsx
  webapp/src/components/rhs/rhs_about_buttons.tsx
  webapp/src/components/rhs/rhs_title.tsx
  webapp/src/components/sidebar/playbooks_sidebar.tsx
  webapp/src/components/update_post.tsx
  webapp/src/hooks/telemetry.ts
  webapp/src/types/telemetry.ts
Labels: 4: Reviews Complete

#1492 Remove fetch type checking
  webapp/src/client.ts
  webapp/src/types/playbook.ts
  webapp/src/types/playbook_run.ts
  webapp/src/websocket_events.ts
Labels: 2: Dev Review

#1493 Fix a setState after unmount
  webapp/src/components/widgets/text_with_tooltip_when_ellipsis.tsx
Labels: 2: Dev Review

#1491 Fix styled component errors
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
Labels: 2: Dev Review
