Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2022-02, with the labels that each got.

#1005 MM-37167 - Fix for: System admin prompt prompts system admin
  server/bot/poster.go
Labels: 4: Reviews Complete

#1012 [MM-37705] Remove h1-h6 styling
  webapp/src/components/rhs/rhs_shared.tsx
Labels: 4: Reviews Complete

#1018 Remove unused components: RHSListView and RHSListPlaybookRun
  webapp/i18n/en.json
  webapp/src/components/rhs/rhs_list_playbook_run.tsx
  webapp/src/components/rhs/rhs_list_view.tsx
Labels: 4: Reviews Complete

#1020 MM-41515 - Fix for: Cannot paginate playbooks
  webapp/src/components/assets/right_dots.tsx
  webapp/src/components/assets/right_fade.tsx
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/playbook_list.tsx
Labels: 4: Reviews Complete

#1019 e2e: Revert #951, patch `mocha-junit-reporter` instead
  .circleci/config.yml
  tests-e2e/cypress.json
  tests-e2e/cypress/plugins/index.js
  tests-e2e/package-lock.json
  tests-e2e/package.json
  tests-e2e/reporter-config.json
  tests-e2e/utils/file.js
Labels: 2: Dev Review, dependencies

#1015 MM-41053: Add Tutorial Tour Tip component
  webapp/i18n/en.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/rhs/rhs_run_details.tsx
  webapp/src/components/tutorial/tours.ts
  webapp/src/components/tutorial/tutorial_tour_tip/backdrop.tsx
  webapp/src/components/tutorial/tutorial_tour_tip/dot.scss
  webapp/src/components/tutorial/tutorial_tour_tip/dot.tsx
  webapp/src/components/tutorial/tutorial_tour_tip/hooks.ts
  webapp/src/components/tutorial/tutorial_tour_tip/index.ts
  webapp/src/components/tutorial/tutorial_tour_tip/manager.ts
  webapp/src/components/tutorial/tutorial_tour_tip/tutorial_tour_tip.scss
  webapp/src/components/tutorial/tutorial_tour_tip/tutorial_tour_tip.tsx
  webapp/src/components/tutorial/tutorial_tour_tip/utils.ts
  webapp/webpack.config.js
Labels: 4: Reviews Complete

#1009 MM-40926 - Playbook delete metric
  tests-e2e/cypress/integration/playbooks/edit_metrics_spec.js
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_edit/metrics/metric_edit.tsx
  webapp/src/components/backstage/playbook_edit/metrics/metric_view.tsx
  webapp/src/components/backstage/playbook_edit/metrics/metrics.tsx
  webapp/src/components/backstage/playbook_edit/metrics/shared.ts
  webapp/src/components/widgets/conditional_tooltip.tsx
  webapp/src/components/widgets/confirmation_modal_light.tsx
Labels: 1: UX Review

#1017 MM-41513: Restrict private playbooks
  server/api_playbooks_test.go
  server/app/permissions_service.go
  server/main_test.go
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_access_modal.tsx
  webapp/src/components/backstage/public_private_selector.tsx
  webapp/src/hooks/general.ts
Labels: 4: Reviews Complete

#1011 Prefer native `href` links where possible
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
  webapp/src/components/rhs/rhs_title.tsx
Labels: 4: Reviews Complete

#998 MM-40446: Adopt a mixed license
  LICENSE
  LICENSE.enterprise
  README.md
  build/custom.mk
  client/playbook.go
  client/playbooks.go
  server/api/playbook_runs.go
  server/api/stats.go
  server/api_playbooks_test.go
  server/app/mocks/mock_license_checker.go
  server/app/mocks/mock_playbook_run_service.go
  server/app/mocks/mock_playbook_store.go
  server/app/permissions_service.go
  server/app/playbook_run_service.go
  server/app/playbook_run_service_test.go
  server/config/config.go
  server/config/mocks/mock_service.go
  server/config/service.go
  server/enterprise/LICENSE
  server/enterprise/license.go
  server/main_test.go
  server/plugin.go
Labels: 4: Reviews Complete

#1025 MM-41615 - Fix for backstage height needs to be reverted
  webapp/src/components/backstage/backstage.tsx
Labels: 2: Dev Review

#1021 MM-41054 Add tour points for playbook preview.
  webapp/i18n/en.json
  webapp/src/components/backstage/playbooks/playbook.tsx
  webapp/src/components/backstage/playbooks/playbook_preview_navbar.tsx
  webapp/src/components/tutorial/tours.ts
  webapp/src/components/tutorial/tutorial_tour_tip/tutorial_tour_tip.scss
Labels: 1: UX Review, 1. Editor Review

#1029 MM-41684 - Support null targets and values
  go.mod
  go.sum
  server/app/export_test.go
  server/app/playbook.go
  server/app/playbook_run.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook_run_test.go
  server/sqlstore/playbook_test.go
  tests-e2e/cypress/integration/playbooks/edit_metrics_spec.js
  webapp/src/components/backstage/playbook_edit/metrics/metric_edit.tsx
  webapp/src/components/backstage/playbook_edit/metrics/metric_view.tsx
  webapp/src/components/backstage/playbook_edit/metrics/metrics.tsx
  webapp/src/components/backstage/playbook_edit/metrics/shared.ts
  webapp/src/types/playbook.ts
Labels: 4: Reviews Complete

#1014 MM-40841, MM-40916: Templates Selector, FTUE flow
  tests-e2e/cypress/integration/channels/rhs/home_spec.js
  tests-e2e/cypress/integration/playbooks/creation_button_spec.js
  webapp/i18n/en.json
  webapp/src/components/assets/error_svg.tsx
  webapp/src/components/assets/icons/clipboards_checkmark.tsx
  webapp/src/components/assets/icons/clipboards_play.tsx
  webapp/src/components/assets/icons/clock.tsx
  webapp/src/components/assets/icons/exclamation.tsx
  webapp/src/components/assets/icons/external_link.tsx
  webapp/src/components/assets/icons/playbook_icon.tsx
  webapp/src/components/assets/icons/profiles.tsx
  webapp/src/components/assets/illustrations/bug_search_svg.tsx
  webapp/src/components/assets/illustrations/clipboard_checklist_svg.tsx
  webapp/src/components/assets/illustrations/dumpster_fire_svg.tsx
  webapp/src/components/assets/illustrations/gears_svg.tsx
  webapp/src/components/assets/illustrations/handshake_svg.tsx
  webapp/src/components/assets/illustrations/light_bulb_svg.tsx
  webapp/src/components/assets/illustrations/rocket_man_svg.tsx
  webapp/src/components/assets/illustrations/rocket_svg.tsx
  webapp/src/components/assets/illustrations/smiley_sunglasses_svg.tsx
  webapp/src/components/assets/mattermost_logo_svg.tsx
  webapp/src/components/assets/success_svg.tsx
  webapp/src/components/assets/svg.tsx
  webapp/src/components/assets/upgrade_playbook_background_svg.tsx
  webapp/src/components/assets/upgrade_retrospective_svg.tsx
  webapp/src/components/assets/upgrade_timeline_background_svg.tsx
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/new_playbook.tsx
  webapp/src/components/backstage/playbook_edit/playbook_edit.tsx
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/backstage/playbook_list_getting_started.tsx
  webapp/src/components/backstage/runs_page.tsx
  webapp/src/components/backstage/styles.tsx
  webapp/src/components/create_playbook_modal.tsx
  webapp/src/components/rhs/rhs_home.tsx
  webapp/src/components/templates/template_data.tsx
  webapp/src/components/templates/template_item.tsx
  webapp/src/components/templates/template_selector.tsx
  webapp/src/components/tutorial/tutorial_tour_tip/manager.ts
  webapp/src/components/tutorial/tutorial_tour_tip/utils.ts
  webapp/src/utils.ts
Labels: 1: UX Review, 2: Dev Review

#1023 MM-41055: RHS Run Details Tutorial
  webapp/i18n/en.json
  webapp/src/actions.ts
  webapp/src/components/rhs/rhs_checklist_list.tsx
  webapp/src/components/rhs/rhs_post_update.tsx
  webapp/src/components/rhs/rhs_run_details.tsx
  webapp/src/components/rhs/rhs_run_details_tour_dialog.tsx
  webapp/src/components/tutorial/tours.ts
  webapp/src/components/tutorial/tutorial_tour_tip/hooks.ts
  webapp/src/components/tutorial/tutorial_tour_tip/manager.ts
  webapp/src/components/tutorial/tutorial_tour_tip/tutorial_tour_tip.tsx
Labels: 4: Reviews Complete

#1027 [MM-41150] Add playbook edit tour
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_edit/playbook_edit.tsx
  webapp/src/components/tabs.tsx
  webapp/src/components/tutorial/tours.ts
Labels: 4: Reviews Complete

#1030 MM-41667 - Playbook metrics telemetry
  server/telemetry/rudder.go
  server/telemetry/rudder_test.go
Labels: 2: Dev Review

#1028 MM-41100 - Enterprise Gate Playbook Metrics
  webapp/i18n/en.json
  webapp/src/components/assets/upgrade_illustration_svg.tsx
  webapp/src/components/backstage/playbook_edit/metrics/metrics.tsx
  webapp/src/components/backstage/upgrade_modal_data.tsx
  webapp/src/constants.ts
  webapp/src/hooks/general.ts
Labels: 1: UX Review, 2: Dev Review, 1. Editor Review

#1031 MM-41101 - Enterprise Gate Playbook Key Metrics tab
  server/telemetry/rudder_test.go
  webapp/src/components/assets/upgrade_illustration_svg.tsx
  webapp/src/components/assets/upgrade_key_metrics_background_svg.tsx
  webapp/src/components/backstage/playbooks/playbook.tsx
  webapp/src/components/backstage/playbooks/playbook_key_metrics.tsx
  webapp/src/components/backstage/playbooks/playbook_preview.tsx
  webapp/src/components/backstage/playbooks/playbook_usage.tsx
  webapp/src/components/backstage/playbooks/upgrade_key_metrics_placeholder.tsx
  webapp/src/components/backstage/playbooks/upgrade_playbook_placeholder.tsx
  webapp/src/components/upgrade_banner.tsx
Labels: 1: UX Review, 2: Dev Review

#1035 [MM-41725] Toast dark theme
  webapp/src/components/backstage/toast_banner.tsx
Labels: 1: UX Review, 2: Dev Review

#1039 Translations update from Mattermost Weblate
  webapp/i18n/de.json
  webapp/i18n/en_AU.json
  webapp/i18n/hu.json
  webapp/i18n/nl.json
Labels: Docs/Not Needed

#1034 MM-41059 Automaticly create a playbook from template in single team enviroments.
  tests-e2e/cypress/integration/playbooks/creation_button_spec.js
  tests-e2e/cypress/integration/playbooks/edit_spec.js
  webapp/src/components/backstage/playbook_edit/playbook_edit.tsx
  webapp/src/components/create_playbook_modal.tsx
  webapp/src/components/templates/template_selector.tsx
  webapp/src/selectors.ts
  webapp/src/types/playbook.ts
Labels: 1: UX Review, 2: Dev Review

#1033 [MM-41057] Wire up tutorial flow
  tests-e2e/cypress/support/api/preference.js
  tests-e2e/cypress/support/api/user.js
  tests-e2e/cypress/support/index.js
  webapp/i18n/en.json
  webapp/src/client.ts
  webapp/src/components/backstage/playbook_edit/playbook_edit.tsx
  webapp/src/components/backstage/playbooks/playbook.tsx
  webapp/src/components/backstage/playbooks/playbook_preview_navbar.tsx
  webapp/src/components/rhs/rhs_run_details.tsx
  webapp/src/components/templates/template_selector.tsx
Labels: 4: Reviews Complete

#1045 [MM-41675] Telemetry for tutorials
  webapp/src/components/backstage/playbook_edit/playbook_edit.tsx
  webapp/src/components/backstage/playbooks/playbook.tsx
  webapp/src/components/backstage/playbooks/playbook_preview_navbar.tsx
  webapp/src/components/rhs/rhs_checklist_list.tsx
  webapp/src/components/rhs/rhs_post_update.tsx
  webapp/src/components/rhs/rhs_run_details.tsx
Labels: 4: Reviews Complete

#1041 MM-41060: redir to regular playbooks list if playbooks exist
  tests-e2e/cypress/integration/playbooks/edit_spec.js
  webapp/src/components/backstage/playbook_list.tsx
Labels: 4: Reviews Complete

#1043 MM-41724: skip on close tour tip
  webapp/src/components/tutorial/tutorial_tour_tip/manager.ts
  webapp/src/components/tutorial/tutorial_tour_tip/tutorial_tour_tip.tsx
Labels: 4: Reviews Complete

#1046 Mm 41664 playbook key metrics tab backend
  server/api/stats.go
  server/sqlstore/playbook_test.go
  server/sqlstore/stats.go
  server/sqlstore/stats_test.go
Labels: 2: Dev Review

#1052 MM-41948 Refactor playbook validation.
  client/playbook.go
  server/api/playbooks.go
  server/api_playbooks_test.go
Labels: 4: Reviews Complete

#1050 MM-41878 Update text for inital playbook preview tour tip.
  webapp/i18n/en.json
  webapp/src/components/backstage/playbooks/playbook_preview_navbar.tsx
Labels: 2: Dev Review

#1048 [MM-41676] Add telemetry for import, export, duplicate
  server/api/playbooks.go
  server/app/mocks/mock_playbook_service.go
  server/app/playbook.go
  server/app/playbook_service.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
  webapp/src/components/backstage/playbook_list_row.tsx
  webapp/src/components/backstage/playbooks/playbook.tsx
Labels: 2: Dev Review

#1055 fix nps link
  webapp/i18n/en.json
  webapp/src/components/backstage/backstage.tsx
Labels: 4: Reviews Complete

#1042 MM-40934 - Playbook metrics dashboard view - frontend
  server/api/stats.go
  server/app/playbook_run.go
  server/app/sort.go
  server/sqlstore/playbook_run.go
  server/sqlstore/stats.go
  server/sqlstore/stats_test.go
  webapp/i18n/en.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/backstage/playbook_edit/automation/channel_access.tsx
  webapp/src/components/backstage/playbook_edit/metrics/metric_edit.tsx
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/metrics/metrics_data.tsx
  webapp/src/components/backstage/playbook_runs/shared.tsx
  webapp/src/components/backstage/playbooks/bar_graph.tsx
  webapp/src/components/backstage/playbooks/line_graph.tsx
  webapp/src/components/backstage/playbooks/metrics/metrics_card.tsx
  webapp/src/components/backstage/playbooks/metrics/metrics_row.tsx
  webapp/src/components/backstage/playbooks/metrics/metrics_run_list.tsx
  webapp/src/components/backstage/playbooks/metrics/metrics_run_list_header.tsx
  webapp/src/components/backstage/playbooks/metrics/metrics_stats_view.tsx
  webapp/src/components/backstage/playbooks/metrics/playbook_key_metrics.tsx
  webapp/src/components/backstage/playbooks/metrics/upgrade_key_metrics_placeholder.tsx
  webapp/src/components/backstage/playbooks/playbook.tsx
  webapp/src/components/backstage/playbooks/playbook_key_metrics.tsx
  webapp/src/components/backstage/runs_list/filters.tsx
  webapp/src/components/backstage/search_input.tsx
  webapp/src/components/backstage/styles.tsx
  webapp/src/components/modals/update_run_status_modal.tsx
  webapp/src/components/sortable_col_header.tsx
  webapp/src/types/stats.ts
Labels: 4: Reviews Complete

#1059 MM-42084 - No metrics blank state
  webapp/i18n/en.json
  webapp/src/components/assets/no_metrics_svg.tsx
  webapp/src/components/backstage/playbooks/metrics/no_metrics_placeholder.tsx
  webapp/src/components/backstage/playbooks/metrics/playbook_key_metrics.tsx
Labels: 4: Reviews Complete, AutoMerge

#1022 MM-40881 Confirmation dialogs are removed when cancelling/restoring a task
  tests-e2e/cypress/integration/channels/rhs/checklist_spec.js
  webapp/i18n/en.json
  webapp/src/components/checklist_item.tsx
Labels: 1: UX Review, 2: Dev Review

#1060 e2e: enable retries on flaky viewport test
  tests-e2e/cypress/integration/channels/rhs/checklist_spec.js
Labels: 4: Reviews Complete

#1053 MM-40504 - Send ephemeral post to user on channel when `/playbooks todo` command is called
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/command/command.go
  tests-e2e/cypress/integration/channels/slash_command/todo_spec.js
Labels: 2: Dev Review
