Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2022-12, with the labels that each got.

#1628 chore: add testing-library typings
  tests-e2e/cypress/tsconfig.json
Labels: 2: Dev Review

#1615 Refactor code to move out fav/unfav from UpdateRun
  server/api/graphql_root_run.go
  server/api/schema.graphqls
  server/api_graphql_runs_test.go
  server/app/playbook_run_service.go
  webapp/src/components/backstage/lhs_run_dot_menu.tsx
  webapp/src/graphql/generated_types.ts
  webapp/src/graphql/hooks.ts
  webapp/src/graphql/runs.graphql
  webapp/src/hooks/run.tsx
Labels: 4: Reviews Complete

#1597 [MM-48592] Make my insights available in free tier
  server/app/playbook_service.go
Labels: 3: QA Review

#1627 Modify RHS header for runs list
  webapp/src/components/rhs/rhs_run_list.tsx
  webapp/src/components/rhs/rhs_title_common.tsx
Labels: 1: UX Review, 2: Dev Review

#1635 's/--center-channel-text/--center-channel-color/g'
  webapp/src/components/assets/no_content_playbooks_rhs_svg.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_participants.tsx
  webapp/src/components/rhs/rhs_run_list.tsx
Labels: 4: Reviews Complete

#1634 Make playbook retrieval optional for case where user has no permissions.
  server/api/graphql_root_playbook.go
  server/api/graphql_run.go
  server/api/schema.graphqls
  webapp/src/components/rhs/rhs_run_list.tsx
  webapp/src/graphql/generated_types.ts
Labels: 2: Dev Review

#1636 MM-48783: Ensure run summary updates in RHS.
  tests-e2e/cypress/integration/channels/rhs/header_spec.js
  webapp/src/client.ts
  webapp/src/components/rhs/rhs_about.tsx
Labels: 2: Dev Review

#1630 force all non-same-folder imports to be non-relative
  webapp/.eslintrc.json
  webapp/src/components/assets/illustrations/bug_search_svg.tsx
  webapp/src/components/assets/illustrations/clipboard_checklist_svg.tsx
  webapp/src/components/assets/illustrations/dumpster_fire_svg.tsx
  webapp/src/components/assets/illustrations/gears_svg.tsx
  webapp/src/components/assets/illustrations/handshake_svg.tsx
  webapp/src/components/assets/illustrations/light_bulb_svg.tsx
  webapp/src/components/assets/illustrations/rocket_man_svg.tsx
  webapp/src/components/assets/illustrations/rocket_svg.tsx
  webapp/src/components/assets/illustrations/smiley_sunglasses_svg.tsx
  webapp/src/components/backstage/archive_playbook_modal.tsx
  webapp/src/components/backstage/lhs_navigation.tsx
  webapp/src/components/backstage/playbook_editor/controls.tsx
  webapp/src/components/backstage/playbook_editor/outline/inputs/update_timer_selector.tsx
  webapp/src/components/backstage/playbook_editor/outline/section_actions.tsx
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/backstage/playbook_list_row.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/add_participant_modal.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/become_participant_modal.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/controls.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/finish_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/metrics/metric_input.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/restore_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_participants.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_timeline.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx
  webapp/src/components/backstage/restore_playbook_modal.tsx
  webapp/src/components/backstage/runs_list/playbook_selector.tsx
  webapp/src/components/backstage/runs_list/row.tsx
  webapp/src/components/backstage/runs_page.tsx
  webapp/src/components/backstage/select_users_below.tsx
  webapp/src/components/backstage/shared.tsx
  webapp/src/components/checklist_item/checklist_item.tsx
  webapp/src/components/checklist_item/description.tsx
  webapp/src/components/checklist_item/duedate.tsx
  webapp/src/components/modals/run_playbook_modal.tsx
  webapp/src/components/modals/update_run_status_modal.tsx
  webapp/src/components/profile/profile_selector.tsx
  webapp/src/components/rhs/rhs_checklist_list.tsx
  webapp/src/components/rhs/rhs_main.tsx
  webapp/src/components/rhs/rhs_run_details.tsx
  webapp/src/components/rhs/rhs_run_participants.tsx
  webapp/src/components/rhs/rhs_timeline_placeholder.tsx
  webapp/src/components/sidebar/create_playbook_dropdown.tsx
  webapp/src/components/sidebar/item.tsx
  webapp/src/components/sidebar/playbooks_sidebar.tsx
  webapp/src/components/sidebar/sidebar.tsx
  webapp/src/components/templates/template_item.tsx
  webapp/src/components/templates/template_selector.tsx
  webapp/src/components/tutorial/tutorial_tour_tip/manager.ts
  webapp/src/components/widgets/confirmation_modal.tsx
  webapp/src/hooks/general.ts
  webapp/src/hooks/license.ts
Labels: 4: Reviews Complete

#1629 MM-45738: ensure give feedback button
  tests-e2e/cypress/integration/playbooks/feedback_spec.js
  tests-e2e/cypress/integration/runs/taskinbox_spec.js
  webapp/src/components/global_header_right.tsx
Labels: 2: Dev Review

#1611 MM-47749: Task Actions
  Makefile
  client/playbook.go
  server/api/graphql_playbook.go
  server/api/graphql_root_playbook.go
  server/api/graphql_root_run.go
  server/api/playbooks.go
  server/api/schema.graphqls
  server/api_graphql_runs_test.go
  server/app/playbook.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/app/task_actions.go
  server/app/task_actions_test.go
  server/app/telemetry.go
  server/plugin.go
  tests-e2e/cypress/integration/playbooks/edit/task_actions_spec.js
  tests-e2e/cypress/integration/runs/rdp_main_taskactions_spec.js
  webapp/i18n/en.json
  webapp/src/actions.ts
  webapp/src/components/actions_modal.tsx
  webapp/src/components/actions_modal_action.tsx
  webapp/src/components/actions_modal_trigger.tsx
  webapp/src/components/backstage/profile_autocomplete.tsx
  webapp/src/components/backstage/rhs/task_inbox/task_inbox.tsx
  webapp/src/components/checklist/checklist_list.tsx
  webapp/src/components/checklist/generic_checklist.tsx
  webapp/src/components/checklist_item/checklist_item.tsx
  webapp/src/components/checklist_item/checklist_item_draggable.tsx
  webapp/src/components/checklist_item/task_actions.tsx
  webapp/src/components/checklist_item/task_actions_modal.tsx
  webapp/src/components/keywords_selector.tsx
  webapp/src/graphql/generated_types.ts
  webapp/src/graphql/hooks.ts
  webapp/src/graphql/playbook.graphql
  webapp/src/graphql/runs.graphql
  webapp/src/types/actions.ts
  webapp/src/types/playbook.ts
  webapp/src/types/telemetry.ts
Labels: 3: QA Review

#1640 MM-48584: unify checklist header text
  tests-e2e/cypress/integration/channels/rhs/checklist_spec.js
  tests-e2e/cypress/integration/channels/rhs/list_spec.js
  tests-e2e/cypress/integration/playbooks/overview_spec.js
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_editor/outline/outline.tsx
  webapp/src/components/rhs/rhs_checklist_list.tsx
Labels: 1: UX Review

#1626 1547 v1 start a run modal
  server/api/graphql_playbook.go
  server/api/playbook_runs.go
  server/api/schema.graphqls
  server/app/playbook_run.go
  webapp/i18n/en.json
  webapp/src/actions.ts
  webapp/src/components/assets/illustrations/search_svg.tsx
  webapp/src/components/backstage/playbook_editor/controls.tsx
  webapp/src/components/backstage/playbook_list_row.tsx
  webapp/src/components/backstage/search_input.tsx
  webapp/src/components/modals/new_run_playbook_modal.tsx
  webapp/src/components/playbooks_selector.tsx
  webapp/src/components/rhs/rhs_home_item.tsx
  webapp/src/components/rhs/rhs_run_list.tsx
  webapp/src/components/widgets/generic_modal.tsx
  webapp/src/graphql/generated_types.ts
  webapp/src/graphql/playbook.graphql
Labels: 1: UX Review, 2: Dev Review

#1651 Avoid instantiating styled components inside a render
  webapp/src/components/backstage/follow_button.tsx
Labels: 2: Dev Review

#1652 MM-48866: avoid assuming current channel
  webapp/src/components/rhs/rhs_main.tsx
  webapp/src/components/rhs/rhs_run_list.tsx
Labels: 4: Reviews Complete

#1657 Force enable link run feature flag
  server/api/settings.go
  server/api_settings_test.go
  tests-e2e/cypress/integration/api/settings_spec.js
Labels: 4: Reviews Complete

#1638 progress bar for cards
  server/api/graphql_run.go
  server/api/schema.graphqls
  webapp/src/components/rhs/rhs_run_list.tsx
  webapp/src/graphql/generated_types.ts
  webapp/src/graphql/runs.graphql
Labels: 4: Reviews Complete

#1653 Avoid redirect to RDP when run is created from channels RHS
  server/api/playbook_runs.go
  server/api_runs_test.go
  server/app/playbook_run_service.go
  tests-e2e/cypress/integration/channels/rhs/start_run_rhs_spec.js
  tests-e2e/cypress/integration/playbooks/edit_spec.js
  tests-e2e/cypress/integration/playbooks/start_run_spec.js
  tests-e2e/cypress/support/plugin/api_commands.js
  webapp/src/actions.ts
  webapp/src/browser_routing.ts
  webapp/src/components/backstage/playbook_editor/controls.tsx
  webapp/src/components/backstage/playbook_list_row.tsx
  webapp/src/components/modals/new_run_playbook_modal.tsx
  webapp/src/components/rhs/rhs_home.tsx
  webapp/src/components/rhs/rhs_home_item.tsx
  webapp/src/components/rhs/rhs_main.tsx
  webapp/src/components/rhs/rhs_run_list.tsx
Labels: 2: Dev Review

#1655 1654 Include run name in finish run modal
  server/app/playbook_run_service.go
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_runs/playbook_run/finish_run.tsx
  webapp/src/components/modals/update_run_status_modal.tsx
Labels: 4: Reviews Complete

#1662 1646 Add link to runs for posts related to runs
  assets/i18n/en.json
  server/app/playbook_run_service.go
  server/app/reminder.go
  tests-e2e/cypress/integration/channels/app_bar_spec.js
  tests-e2e/cypress/integration/channels/channel_header_spec.js
  tests-e2e/cypress/integration/channels/playbook_run_actions.js
  tests-e2e/cypress/integration/channels/retrospective_spec.js
  tests-e2e/cypress/integration/channels/rhs/status_update_spec.js
  tests-e2e/cypress/integration/channels/update_request_post_spec.js
  tests-e2e/cypress/integration/runs/rdp_main_statusupdate_spec.js
  webapp/i18n/en.json
  webapp/src/components/channel_header.tsx
  webapp/src/components/modals/update_run_status_modal.tsx
  webapp/src/components/update_post.tsx
  webapp/src/components/update_request_post.tsx
  webapp/src/selectors.ts
Labels: 4: Reviews Complete

#1663 MM-48888: Infinite loop on fetching roles when logging out
  tests-e2e/cypress/integration/playbooks/overview_spec.js
  webapp/src/components/login_hook.tsx
  webapp/src/index.tsx
Labels: 4: Reviews Complete

#1664 Fix empty default owner issue
  tests-e2e/cypress/integration/playbooks/start_run_spec.js
  webapp/src/components/modals/new_run_playbook_modal.tsx
Labels: 4: Reviews Complete

#1631 [MM-47846] Publish templates to redux - worktemplates
  webapp/src/actions.ts
  webapp/src/index.tsx
  webapp/src/types/actions.ts
Labels: 2: Dev Review

#1637 1601 dotmenu run rhs card
  tests-e2e/cypress/integration/channels/rhs/list_spec.js
  webapp/src/components/rhs/rhs_run_list.tsx
  webapp/src/graphql/generated_types.ts
  webapp/src/graphql/runs.graphql
Labels: 4: Reviews Complete

#1675 update channel run name does not imply changing channel name
  tests-e2e/cypress/integration/channels/rhs/about_spec.js
  webapp/src/components/rhs/rhs_about.tsx
  webapp/src/components/rhs/rhs_about_title.tsx
Labels: 2: Dev Review

#1666 add give feedback to run rhs list
  tests-e2e/cypress/integration/channels/rhs/list_spec.js
  webapp/src/components/give_feedback_button.tsx
  webapp/src/components/rhs/rhs_run_list.tsx
Labels: 2: Dev Review

#1668 1667 Make run configuration labels clickable
  webapp/src/components/backstage/playbook_edit/automation/auto_assign_owner.tsx
  webapp/src/components/backstage/playbook_edit/automation/categorize_playbook_run.tsx
  webapp/src/components/backstage/playbook_edit/automation/channel_access.tsx
  webapp/src/components/backstage/playbook_edit/automation/invite_users.tsx
  webapp/src/components/backstage/playbook_edit/automation/styles.tsx
  webapp/src/components/backstage/playbook_edit/automation/toggle.tsx
  webapp/src/components/backstage/playbook_edit/automation/webhook_setting.tsx
  webapp/src/components/backstage/playbook_editor/outline/section_actions.tsx
  webapp/src/components/modals/new_run_playbook_modal.tsx
  webapp/src/components/modals/run_playbook_modal.tsx
Labels: 4: Reviews Complete

#1683 1681 Add loading indicator to new playbook run modal
  webapp/src/components/playbooks_selector.tsx
Labels: 1: UX Review, 2: Dev Review

#1685 GH-1676: only open rhs when in a channel
  tests-e2e/cypress/integration/channels/rhs_spec.js
  webapp/src/components/rhs/rhs_home_item.tsx
  webapp/src/rhs_opener.ts
Labels: 4: Reviews Complete

#1677 1622 Replace spinner uses
  webapp/src/components/assets/icons/spinner.tsx
  webapp/src/components/backstage/metrics/metrics_run_list.tsx
  webapp/src/components/backstage/runs_list/runs_list.tsx
  webapp/src/components/backstage/upgrade_modal_data.tsx
  webapp/src/components/checklist_item/command.tsx
  webapp/src/components/upgrade_banner.tsx
Labels: 4: Reviews Complete

#1682 MM-48917 Make interactive playbook run dialogs translatable
  assets/i18n/en.json
  server/api/playbook_runs.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/command/command.go
Labels: 2: Dev Review

#1691 Upgrade to Cypress v12
  tests-e2e/cypress.config.js
  tests-e2e/cypress/integration/channels/general_actions_spec.js
  tests-e2e/cypress/integration/channels/post_type_components_spec.js
  tests-e2e/cypress/integration/channels/rhs/start_run_rhs_spec.js
  tests-e2e/cypress/integration/channels/rhs/status_update_spec.js
  tests-e2e/cypress/integration/channels/slash_command/commands_spec.js
  tests-e2e/cypress/integration/playbooks/edit_metrics_spec.js
  tests-e2e/cypress/integration/playbooks/edit_spec.js
  tests-e2e/cypress/integration/playbooks/overview_spec.js
  tests-e2e/cypress/integration/playbooks/start_run_spec.js
  tests-e2e/cypress/integration/runs/rdp_main_retrospective_spec.js
  tests-e2e/cypress/support/e2e.js
  tests-e2e/cypress/support/plugin/ui_commands.js
  tests-e2e/cypress/support/task_commands.js
  tests-e2e/package-lock.json
  tests-e2e/package.json
Labels: 4: Reviews Complete

#1678 1617 change linked channel
  server/api/graphql_root_run.go
  server/api/schema.graphqls
  tests-e2e/cypress/integration/channels/rhs/home_spec.js
  tests-e2e/cypress/integration/channels/rhs/list_spec.js
  tests-e2e/cypress/integration/channels/rhs/start_run_rhs_spec.js
  tests-e2e/cypress/integration/channels/rhs/template_spec.js
  tests-e2e/cypress/integration/channels/rhs_spec.js
  webapp/i18n/en.json
  webapp/package-lock.json
  webapp/src/actions.ts
  webapp/src/components/backstage/channel_selector.tsx
  webapp/src/components/modals/new_run_playbook_modal.tsx
  webapp/src/components/modals/run_update_channel.tsx
  webapp/src/components/modals/run_update_name.tsx
  webapp/src/components/playbooks_selector.tsx
  webapp/src/components/rhs/rhs_home.tsx
  webapp/src/components/rhs/rhs_main.tsx
  webapp/src/components/rhs/rhs_run_details.tsx
  webapp/src/components/rhs/rhs_run_list.tsx
  webapp/src/graphql/generated_types.ts
  webapp/src/graphql/hooks.ts
  webapp/src/graphql/playbook.graphql
Labels: 1: UX Review

#1694 1618 telemetry multiple runs
  server/app/telemetry.go
  tests-e2e/cypress/integration/channels/rhs/list_spec.js
  tests-e2e/cypress/integration/channels/rhs/start_run_rhs_spec.js
  tests-e2e/cypress/integration/playbooks/start_run_spec.js
  tests-e2e/cypress/support/plugin/ui_commands.js
  webapp/src/actions.ts
  webapp/src/components/backstage/playbook_editor/controls.tsx
  webapp/src/components/backstage/playbook_list_row.tsx
  webapp/src/components/modals/new_run_playbook_modal.tsx
  webapp/src/components/rhs/rhs_home_item.tsx
  webapp/src/components/rhs/rhs_main.tsx
  webapp/src/components/rhs/rhs_run_list.tsx
  webapp/src/types/telemetry.ts
Labels: 4: Reviews Complete

#1639 MM-46961 Implement pre-assigning of users to tasks in playbooks
  client/playbook.go
  server/api/graphql_playbook.go
  server/api/graphql_root_playbook.go
  server/api/playbooks.go
  server/api_graphql_playbooks_test.go
  server/api_playbooks_test.go
  server/app/playbook.go
  tests-e2e/cypress/integration/playbooks/edit_spec.js
  tests-e2e/cypress/support/plugin/api_commands.js
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_edit/automation/invite_users.tsx
  webapp/src/components/backstage/playbook_edit/automation/invite_users_selector.tsx
  webapp/src/components/backstage/playbook_editor/outline/section_actions.tsx
  webapp/src/components/checklist/checklist_list.tsx
  webapp/src/components/checklist_item/checklist_item.tsx
  webapp/src/components/checklist_item/hover_menu.tsx
  webapp/src/utils.ts
Labels: 4: Reviews Complete

#1696 Fix update command
  server/api/playbook_runs.go
  server/command/command.go
  tests-e2e/cypress/integration/channels/slash_command/commands_spec.js
  webapp/src/client.ts
  webapp/src/slash_command.ts
Labels: 2: Dev Review

#1698 Use new playbook run modal when no runs
  webapp/i18n/en.json
  webapp/src/components/backstage/runs_page_no_content.tsx
  webapp/src/components/playbooks_selector.tsx
  webapp/src/components/rhs/rhs_welcome_view.tsx
Labels: 4: Reviews Complete

#1701 deflake and deskip various tests
  tests-e2e/cypress/fixtures/timeouts.js
  tests-e2e/cypress/integration/channels/rhs/start_run_rhs_spec.js
  tests-e2e/cypress/integration/digest_spec.js
  tests-e2e/cypress/integration/lhs_spec.js
  tests-e2e/cypress/integration/playbooks/edit/task_actions_spec.js
  tests-e2e/cypress/integration/playbooks/start_run_spec.js
  tests-e2e/cypress/integration/runs/rdp_main_taskactions_spec.js
  tests-e2e/cypress/support/plugin/ui_commands.js
Labels: 2: Dev Review
