Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2022-01, with the labels that each got.

#933 MM-40304: Move items between checklists
  client/playbook_runs.go
  server/api/playbook_runs.go
  server/api_runs_test.go
  server/app/mocks/mock_playbook_run_service.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/command/command.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
  webapp/i18n/en.json
  webapp/src/actions.ts
  webapp/src/client.ts
  webapp/src/components/collapsible_checklist.tsx
  webapp/src/components/collapsible_checklist_hover_menu.tsx
  webapp/src/components/rhs/rhs_checklist.tsx
  webapp/src/components/rhs/rhs_checklist_list.tsx
  webapp/src/reducer.ts
  webapp/src/types/actions.ts
Labels: 4: Reviews Complete

#958 MM-39124: Run Overview timestamp format
  webapp/src/components/rhs/post_card.tsx
Labels: 2: Dev Review

#953 [MM-40658] Convert to relative URLs
  server/app/playbook_run_service.go
  server/app/playbook_run_service_test.go
  server/app/playbook_service.go
  server/app/service_test.go
  server/app/urls.go
Labels: 4: Reviews Complete

#959 MM-38732: retrospective tests
  tests-e2e/cypress/integration/runs/retrospective_spec.js
Labels: 2: Dev Review

#954 [MM-38732] Disallow publishing retro repeatedly
  tests-e2e/cypress/integration/runs/retrospective_spec.js
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/report.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/report_text_area.tsx
  webapp/src/components/widgets/confirmation_modal_light.tsx
Labels: 4: Reviews Complete

#960 MM-40659: Skipped tasks incorrectly marked as unfinished
  server/app/playbook.go
  server/app/playbook_run_service.go
  webapp/src/components/modals/update_run_status_modal.tsx
  webapp/src/components/rhs/rhs_checklist_list.tsx
Labels: 4: Reviews Complete

#962 MM-40833: fix /playbooks height
  webapp/src/components/backstage/backstage.tsx
Labels: 4: Reviews Complete

#936 MM-40155: Remove Dismiss Prompt
  .circleci/config.yml
  server/api/playbook_runs.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/app/reminder.go
  server/sqlstore/migrations.go
  webapp/i18n/en.json
  webapp/src/components/update_request_post.tsx
Labels: 1: UX Review, 2: Dev Review

#963 Fix dropdowns.
  tests-e2e/cypress/integration/runs/list_spec.js
  webapp/i18n/en.json
  webapp/src/components/backstage/runs_list/playbook_selector.tsx
  webapp/src/components/dropdown.tsx
  webapp/src/components/profile/dropdown_selector_style.tsx
  webapp/src/components/profile/profile_selector.tsx
  webapp/src/components/team/create_playbook_team_selector.tsx
  webapp/src/components/team/team_selector.tsx
Labels: 4: Reviews Complete

#965 Fix autoselection of team in playbook creation modal.
  webapp/src/components/create_playbook_modal.tsx
  webapp/src/components/team/team_selector.tsx
Labels: 2: Dev Review

#966 MM-40845 Fix the menu button opening too far right.
  webapp/src/components/dot_menu.tsx
Labels: 4: Reviews Complete

#968 Client v0.7.0
  client/go.sum
  go.mod
  go.tools.mod
  go.tools.sum
Labels: 4: Reviews Complete

#970 Client dependency updates
  webapp/.eslintrc.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/widgets/confirmation_modal.tsx
  webapp/src/components/widgets/generic_modal.tsx
  webapp/src/selectors.ts
Labels: 2: Dev Review

#969 Server dependency updates
  go.mod
  go.sum
Labels: 2: Dev Review

#973 e2e: fix config plumbing for EnableOnboardingFlow
  tests-e2e/cypress.json
  tests-e2e/cypress/support/api/cloud_default_config.json
  tests-e2e/cypress/support/api/on_prem_default_config.json
  tests-e2e/cypress/support/api/system.js
Labels: 4: Reviews Complete

#972 Mm 40674 simplify new run starded root post
  server/app/playbook_run_service.go
  tests-e2e/cypress/integration/channels/broadcast_spec.js
Labels: 4: Reviews Complete

#967 Mm 40660 enable retros and status updates for test data
  server/command/command.go
Labels: 4: Reviews Complete

#974 MM-40944: Lift playbook limits
  server/api/playbooks.go
  server/api_playbooks_test.go
  server/app/permissions_service.go
  server/app/playbook.go
  server/app/playbook_service.go
  server/bot/poster.go
  server/sqlstore/playbook.go
  webapp/i18n/en.json
  webapp/src/actions.ts
  webapp/src/client.ts
  webapp/src/components/backstage/new_playbook.tsx
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/backstage/runs_page_no_content.tsx
  webapp/src/components/backstage/template_selector.tsx
  webapp/src/components/backstage/upgrade_modal_data.tsx
  webapp/src/components/rhs/rhs_home.tsx
  webapp/src/components/rhs/rhs_home_item.tsx
  webapp/src/constants.ts
  webapp/src/hooks/general.ts
  webapp/src/hooks/routing.ts
  webapp/src/reducer.ts
  webapp/src/selectors.ts
  webapp/src/types/actions.ts
Labels: 2: Dev Review

#704 MM-37776 Use query for filtering in run lists.
  tests-e2e/cypress/integration/runs/list_spec.js
  webapp/i18n/en.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
  webapp/src/components/backstage/runs_list/runs_list.tsx
  webapp/src/hooks/general.ts
  webapp/webpack.config.js
Labels: 2: Dev Review

#951 MM-40731: Split Cypress by timings
  .circleci/config.yml
  tests-e2e/cypress/plugins/index.js
  tests-e2e/reporter-config.json
Labels: 2: Dev Review

#977 Stop notifying others' overdue runs
  assets/i18n/en.json
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/sqlstore/playbook_run.go
  server/sqlstore/playbook_run_test.go
  tests-e2e/cypress/integration/channels/slash_command/todo_spec.js
  tests-e2e/cypress/support/api/user.js
  tests-e2e/cypress/support/index.js
Labels: 3: QA Review

#956 [MM-40432] Add telemetry for follower notifications
  server/app/playbook_run_service.go
Labels: 2: Dev Review

#981 MM-37229 Remove support for scss
  webapp/package-lock.json
  webapp/package.json
  webapp/webpack.config.js
Labels: 4: Reviews Complete

#988 Fixing typo 20210119
  tests-e2e/cypress/integration/runs/retrospective_spec.js
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/report.tsx
Labels: 4: Reviews Complete

#980 MM-40842 Server side of import functionality.
  client/playbooks.go
  server/api/playbooks.go
  server/api_playbooks_test.go
Labels: 2: Dev Review

#990 e2e: package update
  tests-e2e/cypress.json
  tests-e2e/package-lock.json
  tests-e2e/package.json
Labels: 2: Dev Review

#989 fix mmjstool integrity check
  webapp/package-lock.json
  webapp/package.json
Labels: 4: Reviews Complete

#985 MM-40965 - Fix for: Missing spacing between task and slash command
  webapp/src/components/checklist_item_input.tsx
Labels: 4: Reviews Complete

#992 [MM-40964] Fix category selector theme
  webapp/src/components/backstage/playbook_edit/automation/categorize_playbook_run.tsx
Labels: 1: UX Review, 2: Dev Review

#987 [MM-40844] playbook duplication
  client/playbooks.go
  server/api/playbooks.go
  server/api_playbooks_test.go
  server/app/mocks/mock_playbook_service.go
  server/app/playbook.go
  server/app/playbook_service.go
  tests-e2e/cypress/integration/playbooks/list_spec.js
  tests-e2e/cypress/integration/playbooks/overview_spec.js
  webapp/i18n/en.json
  webapp/src/client.ts
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/backstage/playbook_list_row.tsx
  webapp/src/components/backstage/playbooks/playbook.tsx
  webapp/src/hooks/crud.ts
Labels: 4: Reviews Complete

#986 MM-40861 - Fix for: Untranslatable strings (Playbooks RHS)
  tests-e2e/cypress/integration/channels/rhs/home_spec.js
  webapp/i18n/en.json
  webapp/src/components/rhs/rhs_home.tsx
  webapp/src/components/rhs/rhs_home_item.tsx
Labels: 4: Reviews Complete

#997 MM-40131 Fix broadcast creator.
  server/app/playbook_run_service.go
  server/app/playbook_run_service_test.go
Labels: 4: Reviews Complete

#996 MM-39571 - Fix for: Longer-worded languages cause text to wrap in markdown_textarea
  webapp/src/components/markdown_textbox.tsx
Labels: 4: Reviews Complete

#1004 MM-40153: Fix wrapping in run overview
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/updates.tsx
  webapp/src/components/backstage/playbook_runs/shared.tsx
  webapp/src/components/rhs/post_card.tsx
Labels: 4: Reviews Complete

#1000 MM-41212 Fix run list filters not persisting.
  webapp/src/hooks/general.ts
Labels: 2: Dev Review

#908 [MM-38832] Update Run overview automatically
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/description.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/updates.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
Labels: Lifecycle/frozen

#995 MM-40868 Prevent hover for DisabledPrimaryButtonSmaller
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/retrospective/report.tsx
Labels: 4: Reviews Complete

#991 Mm 40931 playbook edit update playbook metrics backend
  server/api/playbooks.go
  server/app/export.go
  server/app/export_test.go
  server/app/playbook.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_run.go
  server/sqlstore/playbook_test.go
Labels: 2: Dev Review

#1001 MM-40838: new & reworked templates
  tests-e2e/cypress/integration/channels/rhs/home_spec.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/backstage/template_selector.tsx
  webapp/src/types/js-trim-multiline-string.d.ts
  webapp/src/types/playbook.ts
Labels: 4: Reviews Complete
