Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2022-03, with the labels that each got.

#1061 MM-42079: update playbook preview tour copy
  webapp/i18n/en.json
  webapp/src/components/backstage/playbooks/playbook.tsx
  webapp/src/components/rhs/rhs_run_details_tour_dialog.tsx
  webapp/src/components/tutorial/tutorial_tour_tip/tutorial_tour_tip.scss
Labels: 1: UX Review, 2: Dev Review, 1. Editor Review

#1036 MM-41265: Welcome message action backend
  build/custom.mk
  client/action.go
  client/actions.go
  client/client.go
  go.mod
  go.sum
  server/api/actions.go
  server/api/playbook_runs.go
  server/api_actions_test.go
  server/app/action.go
  server/app/actions_service.go
  server/app/mocks/mock_channel_action_service.go
  server/app/mocks/mock_playbook_run_service.go
  server/app/mocks/mock_playbook_run_store.go
  server/app/permissions_service.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/app/playbook_run_service_test.go
  server/bot/bot.go
  server/bot/mocks/mock_poster.go
  server/bot/poster.go
  server/plugin.go
  server/sqlstore/actions.go
  server/sqlstore/actions_test.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook_run.go
  server/sqlstore/playbook_run_test.go
Labels: 4: Reviews Complete

#1037 MM-41266: Welcome message action frontend
  webapp/i18n/en.json
  webapp/src/actions.ts
  webapp/src/client.ts
  webapp/src/components/actions_modal.tsx
  webapp/src/components/actions_modal_action.tsx
  webapp/src/components/actions_modal_action_children.tsx
  webapp/src/components/actions_modal_trigger.tsx
  webapp/src/components/backstage/playbook_edit/automation/styles.tsx
  webapp/src/components/backstage/playbook_edit/automation/toggle.tsx
  webapp/src/components/backstage/playbook_edit/styles.tsx
  webapp/src/components/markdown_textbox.tsx
  webapp/src/components/post_menu_modal.tsx
  webapp/src/components/widgets/generic_modal.tsx
  webapp/src/index.tsx
  webapp/src/reducer.ts
  webapp/src/selectors.ts
  webapp/src/types/actions.ts
  webapp/src/types/channel_actions.ts
  webapp/src/websocket_events.ts
Labels: 4: Reviews Complete

#1008 MM-41036: Render update request post in threads
  tests-e2e/cypress/integration/channels/update_request_post_spec.js
  tests-e2e/cypress/support/api/cloud_default_config.json
  tests-e2e/cypress/support/api/on_prem_default_config.json
  tests-e2e/cypress/support/api/preference.js
  webapp/src/components/update_request_post.tsx
  webapp/src/selectors.ts
Labels: 4: Reviews Complete

#1066 MM-42246: fix compass icons
  webapp/src/components/backstage/playbook_edit/automation/assign_owner_selector.tsx
  webapp/src/components/backstage/playbook_edit/automation/broadcast.tsx
  webapp/src/components/backstage/playbook_edit/automation/categorize_playbook_run.tsx
  webapp/src/components/backstage/playbook_edit/automation/invite_users_selector.tsx
  webapp/src/components/backstage/profile_autocomplete.tsx
  webapp/src/components/backstage/runs_list/checkbox_input.tsx
  webapp/src/components/backstage/search_input.tsx
  webapp/src/components/checklist_item.tsx
Labels: 4: Reviews Complete

#1007 MM-41244: Simplify run status post
  server/app/playbook_run_service.go
  tests-e2e/cypress/integration/channels/actions_spec.js
Labels: 4: Reviews Complete

#1068 MM-42210 Fix import of private playbooks.
  server/api/playbooks.go
  server/api_playbooks_test.go
  server/main_test.go
Labels: 4: Reviews Complete

#1074 [MM-41581] Fix dropdown z-order
  webapp/src/components/backstage/playbooks/playbook_preview.tsx
Labels: 4: Reviews Complete

#1070 Gh 19168 List autofollowers in playbook preview
  client/playbooks.go
  server/api/api.yaml
  server/api/playbooks.go
  server/api_playbooks_test.go
  server/app/mocks/mock_playbook_service.go
  server/app/mocks/mock_playbook_store.go
  server/app/playbook.go
  server/app/playbook_service.go
  server/sqlstore/playbook.go
  tests-e2e/cypress/integration/playbooks/overview_spec.js
  webapp/i18n/en.json
  webapp/src/client.ts
  webapp/src/components/backstage/playbooks/playbook.tsx
  webapp/src/components/backstage/playbooks/playbook_preview.tsx
  webapp/src/components/backstage/playbooks/playbook_preview_actions.tsx
  webapp/src/components/backstage/playbooks/playbook_preview_navbar.tsx
Labels: 4: Reviews Complete

#1071 MM-41950 New playbooks permissions
  go.mod
  go.sum
  server/api_playbooks_test.go
  server/app/permissions_service.go
  server/main_test.go
  webapp/src/components/backstage/select_users_below.tsx
  webapp/src/types/permissions.ts
Labels: 4: Reviews Complete

#1065 Confirm changes when leaving without saving name or description
  tests-e2e/cypress/integration/playbooks/edit_spec.js
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_edit/playbook_edit.tsx
  webapp/src/components/backstage/playbook_edit_title_description_modal.tsx
  webapp/src/components/backstage/route_leaving_guard.tsx
  webapp/src/components/widgets/confirmation_modal_light.tsx
  webapp/src/components/widgets/generic_modal.tsx
  webapp/src/components/widgets/unsaved_changes_modal.tsx
Labels: 2: Dev Review

#1078 MM-41801: Track execution of channel actions
  server/app/action.go
  server/app/actions_service.go
  server/plugin.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
Labels: 4: Reviews Complete

#1081 MM-41267: Keywords prompt playbook action
  build/custom.mk
  server/api/actions.go
  server/api/signal.go
  server/app/action.go
  server/app/actions_service.go
  server/app/keywords_cache.go
  server/app/mocks/mock_channel_action_service.go
  server/app/mocks/mock_channel_action_store.go
  server/app/mocks/mock_playbook_run_service.go
  server/app/mocks/mock_playbook_service.go
  server/app/playbook.go
  server/app/playbook_run_service.go
  server/app/playbook_service.go
  server/app/service_test.go
  server/app/urls.go
  server/app/urls_test.go
  server/bot/bot.go
  server/bot/mocks/mock_poster.go
  server/bot/poster.go
  server/plugin.go
  server/sqlstore/actions.go
  webapp/i18n/en.json
  webapp/src/client.ts
  webapp/src/components/actions_modal.tsx
  webapp/src/components/actions_modal_action.tsx
  webapp/src/components/actions_modal_action_children.tsx
  webapp/src/components/actions_modal_trigger.tsx
  webapp/src/components/backstage/playbook_edit/actions_edit.tsx
  webapp/src/components/backstage/playbooks/playbook_preview_actions.tsx
  webapp/src/components/keywords_selector.tsx
  webapp/src/components/widgets/generic_modal.tsx
  webapp/src/types/channel_actions.ts
  webapp/src/websocket_events.ts
Labels: 1: UX Review

#1089 MM-42441: Fix newlines in summary from run overview screen
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/description.tsx
Labels: 2: Dev Review

#1086 MM-42394: Sidebar categorization action
  server/api/playbook_runs.go
  server/app/action.go
  server/app/actions_service.go
  server/app/mocks/mock_channel_action_service.go
  server/app/mocks/mock_playbook_run_store.go
  server/app/mocks/mock_playbook_store.go
  server/app/playbook_run_service.go
  server/plugin.go
  server/sqlstore/actions.go
  server/sqlstore/migrations.go
  webapp/i18n/en.json
  webapp/src/components/actions_modal.tsx
  webapp/src/components/actions_modal_action.tsx
  webapp/src/components/actions_modal_action_children.tsx
  webapp/src/components/actions_modal_trigger.tsx
  webapp/src/components/backstage/category_selector.tsx
  webapp/src/components/backstage/playbook_edit/automation/categorize_playbook_run.tsx
  webapp/src/components/backstage/playbook_edit/automation/toggle.tsx
  webapp/src/components/backstage/styles.tsx
  webapp/src/types/channel_actions.ts
Labels: 4: Reviews Complete

#1072 [I18N] playbook.tsx: Small grammatical typo correction
  webapp/i18n/en.json
  webapp/src/components/backstage/playbooks/playbook.tsx
Labels: 4: Reviews Complete

#1085 MM-42550: Edit prompt post once the run is actually created
  server/api/playbook_runs.go
  server/api/signal.go
  server/app/actions_service.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/app/playbook_run_service_test.go
  server/app/urls.go
  server/app/urls_test.go
  server/command/command.go
Labels: 4: Reviews Complete

#1079 [MM-40860] Fix long translations in status update modal
  webapp/src/components/assets/buttons.tsx
  webapp/src/components/modals/update_run_status_modal.tsx
Labels: 4: Reviews Complete

#1091 MM-42422: Remove unused string
  webapp/i18n/en.json
  webapp/src/components/backstage/playbooks/playbook_preview_actions.tsx
Labels: 4: Reviews Complete

#1097 E2E: fix (2) flaky tests—new post actions menu
  tests-e2e/cypress/support/plugin/ui_commands.js
  tests-e2e/cypress/support/ui_commands.js
Labels: 2: Dev Review

#1088 MM-42437: Do not broadcast creation if broadcast is disabled
  server/app/playbook_run_service.go
  tests-e2e/cypress/integration/channels/broadcast_spec.js
Labels: 2: Dev Review

#1092 Mm 42436 playbooks edit onboarding should return to checklists
  webapp/src/components/backstage/playbook_edit/playbook_edit.tsx
  webapp/src/components/tutorial/tutorial_tour_tip/manager.ts
  webapp/src/components/tutorial/tutorial_tour_tip/tutorial_tour_tip.tsx
Labels: 2: Dev Review

#1101 MM-42437: Create a new channel for the do-not-broadcast test
  tests-e2e/cypress/integration/channels/broadcast_spec.js
Labels: 2: Dev Review

#1102 e2e: update and add more action tests
  tests-e2e/cypress/integration/channels/general_actions_spec.js
Labels: 2: Dev Review

#1098 MM-42700: Fix duplicated actions
  client/action.go
  server/api_actions_test.go
  server/app/actions_service.go
  webapp/src/components/actions_modal.tsx
Labels: 4: Reviews Complete

#1104 MM-42845: Move the bar from the header to the modal body
  webapp/src/components/actions_modal.tsx
Labels: 4: Reviews Complete

#1106 MM-42854: Use div instead of span to fix a bug in Safari
  webapp/src/components/actions_modal_trigger.tsx
Labels: 2: Dev Review

#1090 MM-42146-rhs-set-tasks-due-date
  server/api/playbook_runs.go
  server/app/playbook.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  webapp/i18n/en.json
  webapp/src/client.ts
  webapp/src/components/checklist_item.tsx
  webapp/src/components/checklist_item/duedate.tsx
  webapp/src/components/datetime_input.tsx
  webapp/src/components/datetime_selector.tsx
  webapp/src/types/playbook.ts
Labels: 4: Reviews Complete

#1111 MM-38534: Remove message button on run overview
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/participants.tsx
Labels: 4: Reviews Complete

#1094 [GH-19313] Update snooze options text to be "for" duration
  webapp/src/components/update_request_post.tsx
Labels: 4: Reviews Complete
