Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2022-11, with the labels that each got.

#1527 Mm 47677 morph v0.21.0 v0.25.0
  server/sqlstore/migrations/mysql/000049_add_last_status_update_at_to_ir_incident.down.sql
  server/sqlstore/migrations/mysql/000049_add_last_status_update_at_to_ir_incident.up.sql
  server/sqlstore/migrations/mysql/000050_add_export_channel_on_archive_enabled_to_ir_playbook.down.sql
  server/sqlstore/migrations/mysql/000050_add_export_channel_on_archive_enabled_to_ir_playbook.up.sql
  server/sqlstore/migrations/mysql/000051_add_export_channel_on_archive_enabled_to_ir_incident.down.sql
  server/sqlstore/migrations/mysql/000051_add_export_channel_on_archive_enabled_to_ir_incident.up.sql
  server/sqlstore/migrations/mysql/000052_add_categoriz_echannel_enabled_to_ir_playbook.down.sql
  server/sqlstore/migrations/mysql/000052_add_categoriz_echannel_enabled_to_ir_playbook.up.sql
  server/sqlstore/migrations/mysql/000053_add_categoriz_echannel_enabled_to_ir_incident.down.sql
  server/sqlstore/migrations/mysql/000053_add_categoriz_echannel_enabled_to_ir_incident.up.sql
  server/sqlstore/migrations/mysql/000054_rename_export_channel_on_archive_enabled_ir_playbook.down.sql
  server/sqlstore/migrations/mysql/000054_rename_export_channel_on_archive_enabled_ir_playbook.up.sql
  server/sqlstore/migrations/mysql/000055_rename_export_channel_on_archive_enabled_ir_incident.down.sql
  server/sqlstore/migrations/mysql/000055_rename_export_channel_on_archive_enabled_ir_incident.up.sql
  server/sqlstore/migrations/mysql/000056_drop_status_from_ir_status_posts.down.sql
  server/sqlstore/migrations/mysql/000056_drop_status_from_ir_status_posts.up.sql
  server/sqlstore/migrations/mysql/000057_update_current_status_in_ir_incident.down.sql
  server/sqlstore/migrations/mysql/000057_update_current_status_in_ir_incident.up.sql
  server/sqlstore/migrations/postgres/000049_add_last_status_update_at_to_ir_incident.down.sql
  server/sqlstore/migrations/postgres/000049_add_last_status_update_at_to_ir_incident.up.sql
  server/sqlstore/migrations/postgres/000050_add_export_channel_on_archive_enabled_to_ir_playbook.down.sql
  server/sqlstore/migrations/postgres/000050_add_export_channel_on_archive_enabled_to_ir_playbook.up.sql
  server/sqlstore/migrations/postgres/000051_add_export_channel_on_archive_enabled_to_ir_incident.down.sql
  server/sqlstore/migrations/postgres/000051_add_export_channel_on_archive_enabled_to_ir_incident.up.sql
  server/sqlstore/migrations/postgres/000052_add_categoriz_echannel_enabled_to_ir_playbook.down.sql
  server/sqlstore/migrations/postgres/000052_add_categoriz_echannel_enabled_to_ir_playbook.up.sql
  server/sqlstore/migrations/postgres/000053_add_categoriz_echannel_enabled_to_ir_incident.down.sql
  server/sqlstore/migrations/postgres/000053_add_categoriz_echannel_enabled_to_ir_incident.up.sql
  server/sqlstore/migrations/postgres/000054_rename_export_channel_on_archive_enabled_ir_playbook.down.sql
  server/sqlstore/migrations/postgres/000054_rename_export_channel_on_archive_enabled_ir_playbook.up.sql
  server/sqlstore/migrations/postgres/000055_rename_export_channel_on_archive_enabled_ir_incident.down.sql
  server/sqlstore/migrations/postgres/000055_rename_export_channel_on_archive_enabled_ir_incident.up.sql
  server/sqlstore/migrations/postgres/000056_drop_status_from_ir_status_posts.down.sql
  server/sqlstore/migrations/postgres/000056_drop_status_from_ir_status_posts.up.sql
  server/sqlstore/migrations/postgres/000057_update_current_status_in_ir_incident.down.sql
  server/sqlstore/migrations/postgres/000057_update_current_status_in_ir_incident.up.sql
  server/sqlstore/migrations_test.go
  server/sqlstore/migrations_tests_utils.go
Labels: 2: Dev Review

#1534 1417 add participants automatically
  server/api/graphql_root_run.go
  server/api/schema.graphqls
  server/api_graphql_runs_test.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  tests-e2e/cypress/integration/runs/rdp_rhs_participants_spec.js
  tests-e2e/cypress/support/plugin/api_commands.js
  webapp/src/components/backstage/playbook_runs/playbook_run/add_participant_modal.tsx
  webapp/src/graphql/generated_types.ts
  webapp/src/graphql/hooks.ts
  webapp/src/graphql/runs.graphql
Labels: 1: UX Review, 2: Dev Review

#1532 Gh 1524 timeline events participants
  server/api/graphql_root_run.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_runs/playbook_run/retrospective/timeline_event_item.tsx
  webapp/src/types/rhs.ts
Labels: 4: Reviews Complete

#1435 [MM-40300] Add plugin tooltips to some markdown components
  webapp/src/components/backstage/playbook_runs/playbook_run/retrospective/timeline_event_item.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/update_card.tsx
  webapp/src/components/formatted_markdown.tsx
  webapp/src/components/post_text.tsx
  webapp/src/components/retrospective_post.tsx
  webapp/src/components/rhs/rhs_about.tsx
  webapp/src/components/update_post.tsx
Labels: 4: Reviews Complete

#1502 Task Inbox
  Makefile
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/app/reminder.go
  server/app/telemetry.go
  server/sqlstore/playbook_run.go
  server/sqlstore/playbook_run_test.go
  server/sqlstore/stats_test.go
  tests-e2e/cypress/integration/channels/app_bar_spec.js
  tests-e2e/cypress/integration/runs/taskinbox_spec.js
  tests-e2e/cypress/support/api/preference.js
  webapp/i18n/en.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/actions.ts
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/rhs/rhs.tsx
  webapp/src/components/backstage/rhs/task_inbox/task.tsx
  webapp/src/components/backstage/rhs/task_inbox/task_inbox.tsx
  webapp/src/components/checklist_item/checklist_item.tsx
  webapp/src/components/global_header_right.tsx
  webapp/src/reducer.ts
  webapp/src/selectors.ts
  webapp/src/types/actions.ts
  webapp/src/types/backstage_rhs.ts
  webapp/src/types/playbook.ts
  webapp/src/types/playbook_run.ts
  webapp/src/types/telemetry.ts
  webapp/src/webapp_globals.ts
Labels: 1: UX Review, 2: Dev Review

#1557 e2e: Flake fixes
  tests-e2e/cypress/integration/channels/rhs/home_spec.js
  tests-e2e/cypress/integration/channels/rhs/template_spec.js
  tests-e2e/cypress/integration/playbooks/edit_metrics_spec.js
  tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
  tests-e2e/cypress/integration/runs/taskinbox_spec.js
  tests-e2e/cypress/support/e2e.js
  tests-e2e/cypress/support/plugin/ui_commands.js
Labels: 2: Dev Review

#1555 1553 read only rhs toast on checklist
  tests-e2e/cypress/integration/runs/rdp_main_checklist_spec.js
  webapp/src/components/backstage/rhs/task_inbox/task.tsx
  webapp/src/components/checklist/checklist_list.tsx
  webapp/src/components/checklist/generic_checklist.tsx
  webapp/src/components/checklist_item/checklist_item.tsx
  webapp/src/components/checklist_item/checklist_item_draggable.tsx
  webapp/src/components/checklist_item/inputs.tsx
  webapp/src/components/rhs/rhs_checklist_list.tsx
  webapp/src/components/rhs/rhs_run_details.tsx
Labels: 2: Dev Review

#1559 Remove reminants of channel permissions.
  server/api_runs_test.go
  server/app/playbook_run_service.go
Labels: 2: Dev Review

#1561 Adding channel filtering support to runs listing graphql API
  server/api/graphql_root_run.go
  server/api/schema.graphqls
  server/api_graphql_runs_test.go
  server/app/playbook_run.go
  server/sqlstore/playbook_run.go
  webapp/src/graphql/generated_types.ts
Labels: 2: Dev Review

#1550 Add missing telemetry for adding and removing participants.
  server/app/playbook_run_service.go
  server/plugin.go
  tests-e2e/cypress/integration/runs/rdp_rhs_participants_spec.js
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_runs/playbook_run/add_participant_modal.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_participants.tsx
  webapp/src/components/rhs/rhs_participants.tsx
  webapp/src/graphql/hooks.ts
  webapp/src/hooks/run.tsx
Labels: 2: Dev Review

#1569 MM-48366: duplicate without members
  server/app/playbook_service.go
  tests-e2e/cypress/integration/playbooks/list_spec.js
  tests-e2e/cypress/integration/playbooks/overview_spec.js
  webapp/src/components/backstage/playbook_list_row.tsx
Labels: 4: Reviews Complete

#1538 remove channel coupling in ProfileSelector/AssignTo
  client/playbook_runs.go
  server/api_runs_test.go
  server/app/playbook_run_service.go
  tests-e2e/cypress/integration/channels/rhs/checklist_spec.js
  tests-e2e/cypress/integration/lhs_spec.js
  tests-e2e/cypress/integration/playbooks/status_update_spec.js
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_editor/outline/inputs/broadcast_channels_selector.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
  webapp/src/components/backstage/rhs/task_inbox/task.tsx
  webapp/src/components/backstage/rhs/task_inbox/task_inbox.tsx
  webapp/src/components/backstage/runs_list/filters.tsx
  webapp/src/components/backstage/runs_list/playbook_selector.tsx
  webapp/src/components/backstage/styles.tsx
  webapp/src/components/checklist_item/assign_to.tsx
  webapp/src/components/checklist_item/checklist_item.tsx
  webapp/src/components/checklist_item/checklist_item_draggable.tsx
  webapp/src/components/checklist_item/hover_menu.tsx
  webapp/src/components/datetime_selector.tsx
  webapp/src/components/dropdown.tsx
  webapp/src/components/profile/profile_selector.tsx
  webapp/src/components/rhs/rhs_about.tsx
  webapp/src/selectors.ts
  webapp/src/types/playbook_run.ts
Labels: 4: Reviews Complete

#1565 1551 channel rhs show participants
  webapp/i18n/en.json
  webapp/src/actions.ts
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs.tsx
  webapp/src/components/rhs/rhs_about.tsx
  webapp/src/components/rhs/rhs_main.tsx
  webapp/src/components/rhs/rhs_participants.tsx
  webapp/src/components/rhs/rhs_run_participants.tsx
  webapp/src/components/rhs/rhs_title.tsx
  webapp/src/types/rhs.ts
Labels: 1: UX Review, 2: Dev Review

#1540 1415 join run when you become participant
  assets/i18n/en.json
  server/api_graphql_runs_test.go
  server/app/playbook_run_service.go
  tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
  tests-e2e/cypress/integration/runs/rdp_rhs_participants_spec.js
  tests-e2e/cypress/integration/runs/rdp_rhs_runinfo_spec.js
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_runs/playbook_run/become_participant_modal.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
  webapp/src/components/rhs/rhs_about.tsx
  webapp/src/components/rhs/rhs_run_details.tsx
  webapp/src/hooks/run.tsx
Labels: 1: UX Review, 2: Dev Review

#1558 MM-48313: Use the term Cost for easier l18n
  tests-e2e/cypress/integration/playbooks/edit_metrics_spec.js
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_edit/metrics/metric_edit.tsx
  webapp/src/components/backstage/playbook_edit/metrics/metrics.tsx
Labels: 2: Dev Review

#1572 MM-47235: Fix styling of hr in status updates
  webapp/src/components/update_post.tsx
Labels: 4: Reviews Complete

#1576 respect fullname setting at getOwners
  client/playbook_run.go
  client/playbook_runs.go
  server/api_runs_test.go
  server/app/playbook_run_service.go
  server/main_test.go
  webapp/src/components/backstage/runs_list/filters.tsx
Labels: 2: Dev Review

#1556 avoid checklistitem reset while editing
  webapp/src/components/checklist_item/checklist_item.tsx
Labels: 4: Reviews Complete

#1578 WS updates run for non channel members
  server/app/playbook_run_service.go
Labels: 4: Reviews Complete

#1580 Cherry pick: MM-47980, MM-47981 Improve team limits (#1533)
  server/api_playbooks_test.go
  server/api_runs_test.go
  server/app/permissions_service.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_run.go
  server/sqlstore/playbook_test.go
Labels: 2: Dev Review

#1581 Cherry pick: MM-47980, MM-47981 Improve team limits (#1533)
  server/api_playbooks_test.go
  server/api_runs_test.go
  server/app/permissions_service.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_run.go
  server/sqlstore/playbook_test.go
Labels: 2: Dev Review

#1549 PBE run link to existing channel
  client/settings.go
  server/api/graphql_playbook.go
  server/api/graphql_root_playbook.go
  server/api/schema.graphqls
  server/api/settings.go
  server/app/playbook.go
  server/app/playbook_run_service.go
  server/config/configuration.go
  server/sqlstore/migrations.go
  server/sqlstore/migrations/future/mysql/0.61.down.sql
  server/sqlstore/migrations/future/mysql/0.61.up.sql
  server/sqlstore/migrations/future/postgres/0.61.down.sql
  server/sqlstore/migrations/future/postgres/0.61.up.sql
  server/sqlstore/playbook.go
  server/sqlstore/playbook_run.go
  tests-e2e/cypress/integration/playbooks/edit_spec.js
  tests-e2e/cypress/integration/runs/rdp_main_retrospective_spec.js
  tests-e2e/cypress/support/api/system.js
  webapp/i18n/en.json
  webapp/src/components/backstage/channel_selector.tsx
  webapp/src/components/backstage/playbook_edit/automation/channel_access.tsx
  webapp/src/components/backstage/playbook_edit/automation/patterned_input.tsx
  webapp/src/components/backstage/playbook_editor/outline/section_actions.tsx
  webapp/src/components/broadcast_channel_selector.tsx
  webapp/src/graphql/generated_types.ts
  webapp/src/graphql/playbook.graphql
  webapp/src/hooks/general.ts
  webapp/src/selectors.ts
  webapp/src/types/playbook.ts
  webapp/src/types/settings.ts
Labels: 2: Dev Review, 3: QA Review

#1577 MM-42882 Allow playbook import for first-time users
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_list.tsx
Labels: 4: Reviews Complete

#1583 enable empty checklist as droppable are for tasks
  webapp/src/components/checklist/generic_checklist.tsx
Labels: 4: Reviews Complete

#1590 cherry-pick getowners into 1.32
  client/playbook_run.go
  client/playbook_runs.go
  server/api_runs_test.go
  server/app/playbook_run_service.go
  server/main_test.go
  tests-e2e/cypress/integration/channels/app_bar_spec.js
  tests-e2e/cypress/integration/channels/rhs/home_spec.js
  tests-e2e/cypress/integration/channels/rhs/template_spec.js
  tests-e2e/cypress/support/api/preference.js
  webapp/src/components/assets/buttons.tsx
  webapp/src/components/backstage/runs_list/filters.tsx
Labels: 2: Dev Review

#1588 cherry-pick getOwners into 1.29
  client/playbook_run.go
  client/playbook_runs.go
  server/api_runs_test.go
  server/app/playbook_run_service.go
  server/main_test.go
Labels: 2: Dev Review

#1589 cherry-pick getOwners into 1.31
  client/playbook_run.go
  client/playbook_runs.go
  server/api_runs_test.go
  server/app/playbook_run_service.go
  server/main_test.go
  tests-e2e/cypress/integration/channels/app_bar_spec.js
  tests-e2e/cypress/integration/channels/rhs/template_spec.js
  tests-e2e/cypress/integration/channels/rhs_spec.js
  tests-e2e/cypress/support/api/preference.js
  webapp/src/components/backstage/runs_list/filters.tsx
Labels: 2: Dev Review

#1575 MM-48449: avoid race with /playbook
  server/app/playbook_run_service.go
  tests-e2e/cypress/integration/channels/rhs/checklist_spec.js
Labels: 2: Dev Review

#1566 Translations update from Mattermost Weblate
  assets/i18n/de.json
  assets/i18n/hr.json
  assets/i18n/hu.json
  assets/i18n/pl.json
  assets/i18n/sv.json
  assets/i18n/tr.json
  webapp/i18n/de.json
  webapp/i18n/en_AU.json
  webapp/i18n/fr.json
  webapp/i18n/hr.json
  webapp/i18n/hu.json
  webapp/i18n/ja.json
  webapp/i18n/nl.json
  webapp/i18n/pl.json
  webapp/i18n/sv.json
  webapp/i18n/tr.json
  webapp/i18n/zh_Hans.json
Labels: Do Not Merge/Mattermod

#1594 Fix request update e2e test issue
  webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx
Labels: 2: Dev Review

#1593 Remove en.json from CODEOWNERS
  CODEOWNERS
Labels: 4: Reviews Complete

#1599 Fix sv translation file syntax issues
  assets/i18n/sv.json
Labels: 2: Dev Review

#1587 Gh 1586 rename run graphql
  client/playbook_run.go
  server/api/graphql_root_run.go
  server/api/playbook_runs.go
  server/api/schema.graphqls
  server/api_graphql_runs_test.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
  tests-e2e/cypress/integration/runs/rdp_main_summary_spec.js
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/controls.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/summary.tsx
  webapp/src/graphql/generated_types.ts
Labels: 1: UX Review, 2: Dev Review

#1564 Morph v0.25.0 v0.30.0
  server/sqlstore/migrations/mysql/000058_add_category_name_to_ir_playbook.down.sql
  server/sqlstore/migrations/mysql/000058_add_category_name_to_ir_playbook.up.sql
  server/sqlstore/migrations/mysql/000059_add_category_name_to_ir_incident.down.sql
  server/sqlstore/migrations/mysql/000059_add_category_name_to_ir_incident.up.sql
  server/sqlstore/migrations/mysql/000060_add_concatenated_broadcast_channel_ids_to_ir_incident.down.sql
  server/sqlstore/migrations/mysql/000060_add_concatenated_broadcast_channel_ids_to_ir_incident.up.sql
  server/sqlstore/migrations/mysql/000061_add_concatenated_broadcast_channel_ids_to_ir_playbook.down.sql
  server/sqlstore/migrations/mysql/000061_add_concatenated_broadcast_channel_ids_to_ir_playbook.up.sql
  server/sqlstore/migrations/mysql/000062_add_channel_id_to_root_id_to_ir_incident.down.sql
  server/sqlstore/migrations/mysql/000062_add_channel_id_to_root_id_to_ir_incident.up.sql
  server/sqlstore/migrations/mysql/000063_convert_charset_of_ir_system.down.sql
  server/sqlstore/migrations/mysql/000063_convert_charset_of_ir_system.up.sql
  server/sqlstore/migrations/mysql/000064_add_pr_key_ir_playbook_member.down.sql
  server/sqlstore/migrations/mysql/000064_add_pr_key_ir_playbook_member.up.sql
  server/sqlstore/migrations/mysql/000065_drop_index_posts_unique.down.sql
  server/sqlstore/migrations/mysql/000065_drop_index_posts_unique.up.sql
  server/sqlstore/migrations/mysql/000066_add_pr_key_ir_status_posts.down.sql
  server/sqlstore/migrations/mysql/000066_add_pr_key_ir_status_posts.up.sql
  server/sqlstore/migrations/mysql/000067_add_pr_key_ir_timeline_event.down.sql
  server/sqlstore/migrations/mysql/000067_add_pr_key_ir_timeline_event.up.sql
  server/sqlstore/migrations/mysql/000068_drop_index_ir_viewed_channel_channelid_userid.down.sql
  server/sqlstore/migrations/mysql/000068_drop_index_ir_viewed_channel_channelid_userid.up.sql
  server/sqlstore/migrations/mysql/000069_add_pr_key_ir_viewed_channel.down.sql
  server/sqlstore/migrations/mysql/000069_add_pr_key_ir_viewed_channel.up.sql
  server/sqlstore/migrations/postgres/000058_add_category_name_to_ir_playbook.down.sql
  server/sqlstore/migrations/postgres/000058_add_category_name_to_ir_playbook.up.sql
  server/sqlstore/migrations/postgres/000059_add_category_name_to_ir_incident.down.sql
  server/sqlstore/migrations/postgres/000059_add_category_name_to_ir_incident.up.sql
  server/sqlstore/migrations/postgres/000060_add_concatenated_broadcast_channel_ids_to_ir_incident.down.sql
  server/sqlstore/migrations/postgres/000060_add_concatenated_broadcast_channel_ids_to_ir_incident.up.sql
  server/sqlstore/migrations/postgres/000061_add_concatenated_broadcast_channel_ids_to_ir_playbook.down.sql
  server/sqlstore/migrations/postgres/000061_add_concatenated_broadcast_channel_ids_to_ir_playbook.up.sql
  server/sqlstore/migrations/postgres/000062_add_channel_id_to_root_id_to_ir_incident.down.sql
  server/sqlstore/migrations/postgres/000062_add_channel_id_to_root_id_to_ir_incident.up.sql
  server/sqlstore/migrations/postgres/000063_convert_charset_of_ir_system.down.sql
  server/sqlstore/migrations/postgres/000063_convert_charset_of_ir_system.up.sql
  server/sqlstore/migrations/postgres/000064_add_pr_key_ir_playbook_member.down.sql
  server/sqlstore/migrations/postgres/000064_add_pr_key_ir_playbook_member.up.sql
  server/sqlstore/migrations/postgres/000065_drop_index_posts_unique.down.sql
  server/sqlstore/migrations/postgres/000065_drop_index_posts_unique.up.sql
  server/sqlstore/migrations/postgres/000066_add_pr_key_ir_status_posts.down.sql
  server/sqlstore/migrations/postgres/000066_add_pr_key_ir_status_posts.up.sql
  server/sqlstore/migrations/postgres/000067_add_pr_key_ir_timeline_event.down.sql
  server/sqlstore/migrations/postgres/000067_add_pr_key_ir_timeline_event.up.sql
  server/sqlstore/migrations/postgres/000068_drop_index_ir_viewed_channel_channelid_userid.down.sql
  server/sqlstore/migrations/postgres/000068_drop_index_ir_viewed_channel_channelid_userid.up.sql
  server/sqlstore/migrations/postgres/000069_add_pr_key_ir_viewed_channel.down.sql
  server/sqlstore/migrations/postgres/000069_add_pr_key_ir_viewed_channel.up.sql
  server/sqlstore/migrations_test.go
  server/sqlstore/migrations_tests_utils.go
Labels: 2: Dev Review

#1585 MM-42517 Make UX of skipped tasks more consistent
  webapp/src/components/checklist_item/assign_to.tsx
  webapp/src/components/checklist_item/checklist_item.tsx
  webapp/src/components/checklist_item/command.tsx
  webapp/src/components/checklist_item/hover_menu.tsx
  webapp/src/components/profile/profile_selector.tsx
Labels: 1: UX Review, 2: Dev Review

#1574 migrate digest related methods to avoid using channel names
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/sqlstore/playbook_run.go
  server/sqlstore/playbook_run_test.go
  tests-e2e/cypress/integration/channels/rhs_spec.js
  tests-e2e/cypress/integration/digest_spec.js
  tests-e2e/cypress/support/plugin/ui_commands.js
Labels: 2: Dev Review

#1584 1543 start a run modal upgrade
  client/playbook.go
  client/playbook_run.go
  server/api/playbook_runs.go
  server/api_runs_test.go
  server/app/playbook.go
  server/app/playbook_run_service.go
  tests-e2e/cypress/integration/playbooks/overview_spec.js
  tests-e2e/cypress/integration/runs/rdp_main_retrospective_spec.js
  webapp/i18n/en.json
  webapp/src/client.ts
  webapp/src/components/backstage/playbook_edit/automation/channel_access.tsx
  webapp/src/components/modals/run_playbook_modal.tsx
Labels: 1: UX Review, 2: Dev Review

#1570 MM 44807 Adjust outline hover effects
  webapp/src/components/backstage/playbook_editor/outline/outline.tsx
  webapp/src/components/backstage/playbook_editor/outline/section.tsx
  webapp/src/components/backstage/playbook_editor/outline/section_retrospective.tsx
  webapp/src/components/backstage/playbook_editor/outline/section_status_updates.tsx
  webapp/src/components/widgets/copy_link.tsx
Labels: 1: UX Review, 2: Dev Review

#1598 Multiple runs in a channel: Channel RHS runs list
  server/api/graphql.go
  server/api/graphql_root_playbook.go
  server/api/graphql_root_run.go
  server/api/graphql_run.go
  server/api/schema.graphqls
  server/api_graphql_runs_test.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/sqlstore/playbook_run.go
  tests-e2e/cypress/integration/channels/rhs/list_spec.js
  tests-e2e/cypress/integration/channels/rhs_spec.js
  tests-e2e/cypress/integration/lhs_spec.js
  tests-e2e/cypress/integration/runs/rdp_main_statusupdate_spec.js
  webapp/.eslintrc.json
  webapp/i18n/en.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/assets/buttons.tsx
  webapp/src/components/assets/illustrations/clipboard_checklist_svg.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
  webapp/src/components/checklist_item/assign_to.tsx
  webapp/src/components/dot_menu.tsx
  webapp/src/components/rhs/rhs_about.tsx
  webapp/src/components/rhs/rhs_home.tsx
  webapp/src/components/rhs/rhs_main.tsx
  webapp/src/components/rhs/rhs_participants.tsx
  webapp/src/components/rhs/rhs_run_details.tsx
  webapp/src/components/rhs/rhs_run_details_title.tsx
  webapp/src/components/rhs/rhs_run_list.tsx
  webapp/src/components/rhs/rhs_run_participants.tsx
  webapp/src/components/rhs/rhs_run_participants_title.tsx
  webapp/src/components/rhs/rhs_title.tsx
  webapp/src/components/rhs/rhs_title_common.tsx
  webapp/src/components/sidebar/playbooks_sidebar.tsx
  webapp/src/graphql/apollo.tsx
  webapp/src/graphql/generated_types.ts
  webapp/src/graphql/playbook.graphql
  webapp/src/graphql/runs.graphql
  webapp/src/index.tsx
  webapp/src/rhs_title_remote_render.tsx
  webapp/src/selectors.ts
  webapp/src/slash_command.ts
Labels: 1: UX Review, 2: Dev Review

#1582 MM-48471-remove-help-link
  webapp/i18n/en.json
  webapp/src/components/markdown_textbox.tsx
Labels: 4: Reviews Complete

#1609 RHS runs sort list visual improvements.
  webapp/i18n/en.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/rhs/rhs_run_list.tsx
Labels: 1: UX Review

#1612 Loading states for runs RHS
  webapp/src/components/assets/loading_spinner.tsx
  webapp/src/components/rhs/rhs_main.tsx
  webapp/src/components/rhs/rhs_run_list.tsx
Labels: 1: UX Review

#1623 Owner display and update on finish
  webapp/src/components/rhs/rhs_main.tsx
  webapp/src/components/rhs/rhs_run_list.tsx
Labels: 2: Dev Review

#1624 [Proposal] add eslint warning for relative imports
  webapp/.eslintrc.json
  webapp/package-lock.json
  webapp/package.json
Labels: 2: Dev Review
