Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2022-08, with the labels that each got.

#1377 hide key metrics in rhs if retro is disabled
  tests-e2e/cypress/integration/runs/rdp_rhs_runinfo_spec.js
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info.tsx
Labels: 2: Dev Review

#1380 prevent users from saving invalid webhooks
  tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
  webapp/src/components/actions_modal.tsx
  webapp/src/components/channel_actions_modal.tsx
  webapp/src/components/patterned_text_area.tsx
  webapp/src/components/run_actions_modal.tsx
Labels: 2: Dev Review

#1375 prevent request-update from execute when run is finished
  tests-e2e/cypress/integration/runs/rdp_main_statusupdate_spec.js
  webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx
Labels: 2: Dev Review

#1382 fix import playbook failures when json is invalid
  webapp/i18n/en.json
  webapp/src/components/backstage/import_playbook.tsx
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/sidebar/create_playbook_dropdown.tsx
Labels: 2: Dev Review

#1383 recover channel and all timeline by default
  tests-e2e/cypress/integration/runs/rdp_rhs_runinfo_spec.js
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_activity.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
  webapp/src/types/rhs.ts
Labels: 2: Dev Review

#1331 fetchstate in useThing
  webapp/i18n/en.json
  webapp/src/components/actions_modal_action_children.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/overview/updates.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
  webapp/src/components/backstage/playbooks/playbook_preview_badges.tsx
  webapp/src/components/modals/update_run_status_modal.tsx
  webapp/src/hooks/crud.ts
  webapp/src/hooks/general.ts
  webapp/src/hooks/permissions.ts
  webapp/src/selectors.ts
Labels: 2: Dev Review

#1379 Improved LHS styling & use of icons
  webapp/src/components/assets/icons/playbook_icon.tsx
  webapp/src/components/assets/icons/playbook_run_icon.tsx
  webapp/src/components/assets/icons/private_playbook_icon.tsx
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
  webapp/src/components/sidebar/group.tsx
  webapp/src/components/sidebar/item.tsx
  webapp/src/components/sidebar/playbooks_sidebar.tsx
  webapp/src/components/sidebar/sidebar.tsx
Labels: 4: Reviews Complete

#1376 Mm 46070 lhs not updated
  tests-e2e/cypress/integration/playbooks/creation_button_spec.js
  tests-e2e/cypress/integration/runs/rdp_main_finish_spec.js
  tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
  webapp/src/components/backstage/archive_playbook_modal.tsx
  webapp/src/components/backstage/lhs_navigation.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/finish_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
  webapp/src/components/backstage/restore_playbook_modal.tsx
  webapp/src/components/templates/template_selector.tsx
Labels: 2: Dev Review

#1384 Add sort by name
  server/api/graphql_root.go
  server/api/schema.graphqls
  tests-e2e/cypress/integration/runs/list_spec.js
  webapp/src/graphql/generated_types.ts
  webapp/src/graphql/playbook.graphql
Labels: 2: Dev Review

#1392 Skip create playbook modal
  tests-e2e/cypress/integration/playbooks/creation_button_spec.js
  webapp/src/components/templates/template_selector.tsx
Labels: 2: Dev Review

#1387 RDP RHS info: remove onclick events and keep regular a elements
  tests-e2e/cypress/integration/runs/rdp_main_retrospective_spec.js
  tests-e2e/cypress/integration/runs/rdp_rhs_runinfo_spec.js
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
Labels: 4: Reviews Complete

#1391 Show due date on finished tasks without late warning style
  webapp/src/components/checklist_item/checklist_item.tsx
  webapp/src/components/checklist_item/duedate.tsx
Labels: 2: Dev Review

#1393 Translations update from Mattermost Weblate
  assets/i18n/de.json
  assets/i18n/hu.json
  assets/i18n/pl.json
  assets/i18n/sv.json
  assets/i18n/tr.json
  webapp/i18n/de.json
  webapp/i18n/en_AU.json
  webapp/i18n/hr.json
  webapp/i18n/hu.json
  webapp/i18n/nl.json
  webapp/i18n/pl.json
  webapp/i18n/tr.json
Labels: 4: Reviews Complete

#1395 Fix RHS post update button.
  webapp/src/components/rhs/rhs_post_update.tsx
  webapp/src/components/rhs/rhs_post_update_button.tsx
Labels: 2: Dev Review

#1403 Mm 44247 morph migrations
  server/sqlstore/migrations/mysql/000006_create_ir_status_posts.down.sql
  server/sqlstore/migrations/mysql/000006_create_ir_status_posts.up.sql
  server/sqlstore/migrations/mysql/000007_add_reminder_post_id_to_ir_incident.down.sql
  server/sqlstore/migrations/mysql/000007_add_reminder_post_id_to_ir_incident.up.sql
  server/sqlstore/migrations/mysql/000008_add_broadcast_channel_id_to_ir_incident.down.sql
  server/sqlstore/migrations/mysql/000008_add_broadcast_channel_id_to_ir_incident.up.sql
  server/sqlstore/migrations/mysql/000009_add_broadcast_channel_id_to_ir_playbook.down.sql
  server/sqlstore/migrations/mysql/000009_add_broadcast_channel_id_to_ir_playbook.up.sql
  server/sqlstore/migrations/postgres/000003_create_ir_playbook.up.sql
  server/sqlstore/migrations/postgres/000006_create_ir_status_posts.down.sql
  server/sqlstore/migrations/postgres/000006_create_ir_status_posts.up.sql
  server/sqlstore/migrations/postgres/000007_add_reminder_post_id_to_ir_incident.down.sql
  server/sqlstore/migrations/postgres/000007_add_reminder_post_id_to_ir_incident.up.sql
  server/sqlstore/migrations/postgres/000008_add_broadcast_channel_id_to_ir_incident.down.sql
  server/sqlstore/migrations/postgres/000008_add_broadcast_channel_id_to_ir_incident.up.sql
  server/sqlstore/migrations/postgres/000009_add_broadcast_channel_id_to_ir_playbook.down.sql
  server/sqlstore/migrations/postgres/000009_add_broadcast_channel_id_to_ir_playbook.up.sql
  server/sqlstore/migrations_test.go
  server/sqlstore/migrations_utils.go
Labels: 2: Dev Review

#1216 [MM-43761] remove channel actions dm gm
  webapp/src/index.tsx
Labels: 4: Reviews Complete, Lifecycle/frozen

#1404 [MM-45761] - Telemetry: Track how many users end up in purchase/pricing modal/notify admin
  webapp/src/hooks/general.ts
Labels: 4: Reviews Complete

#1406 Fix margin
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_participants.tsx
Labels: 2: Dev Review

#1407 Explain why run is disabled
  webapp/src/components/backstage/playbook_list_row.tsx
Labels: 4: Reviews Complete

#1408 Add arrow forward icon to participants section
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
Labels: 2: Dev Review

#1411 Morph v0.7.0 v0.10.0
  server/sqlstore/migrations/mysql/000017_add_reporter_user_id_to_ir_incident.down.sql
  server/sqlstore/migrations/mysql/000017_add_reporter_user_id_to_ir_incident.up.sql
  server/sqlstore/migrations/mysql/000018_add_concatenated_invited_user_ids_to_ir_incident.down.sql
  server/sqlstore/migrations/mysql/000018_add_concatenated_invited_user_ids_to_ir_incident.up.sql
  server/sqlstore/migrations/mysql/000019_add_concatenated_invited_useri_ds_to_ir_playbook.down.sql
  server/sqlstore/migrations/mysql/000019_add_concatenated_invited_useri_ds_to_ir_playbook.up.sql
  server/sqlstore/migrations/mysql/000020_add_invite_users_enabled_to_ir_playbook.down.sql
  server/sqlstore/migrations/mysql/000020_add_invite_users_enabled_to_ir_playbook.up.sql
  server/sqlstore/migrations/mysql/000021_add_default_commander_id_to_ir_incident.down.sql
  server/sqlstore/migrations/mysql/000021_add_default_commander_id_to_ir_incident.up.sql
  server/sqlstore/migrations/mysql/000022_add_default_commander_id_to_ir_playbook.down.sql
  server/sqlstore/migrations/mysql/000022_add_default_commander_id_to_ir_playbook.up.sql
  server/sqlstore/migrations/mysql/000023_add_default_commander_enabled_to_ir_playbook.down.sql
  server/sqlstore/migrations/mysql/000023_add_default_commander_enabled_to_ir_playbook.up.sql
  server/sqlstore/migrations/postgres/000017_add_reporter_user_id_to_ir_incident.down.sql
  server/sqlstore/migrations/postgres/000017_add_reporter_user_id_to_ir_incident.up.sql
  server/sqlstore/migrations/postgres/000018_add_concatenated_invited_user_ids_to_ir_incident.down.sql
  server/sqlstore/migrations/postgres/000018_add_concatenated_invited_user_ids_to_ir_incident.up.sql
  server/sqlstore/migrations/postgres/000019_add_concatenated_invited_useri_ds_to_ir_playbook.down.sql
  server/sqlstore/migrations/postgres/000019_add_concatenated_invited_useri_ds_to_ir_playbook.up.sql
  server/sqlstore/migrations/postgres/000020_add_invite_users_enabled_to_ir_playbook.down.sql
  server/sqlstore/migrations/postgres/000020_add_invite_users_enabled_to_ir_playbook.up.sql
  server/sqlstore/migrations/postgres/000021_add_default_commander_id_to_ir_incident.down.sql
  server/sqlstore/migrations/postgres/000021_add_default_commander_id_to_ir_incident.up.sql
  server/sqlstore/migrations/postgres/000022_add_default_commander_id_to_ir_playbook.down.sql
  server/sqlstore/migrations/postgres/000022_add_default_commander_id_to_ir_playbook.up.sql
  server/sqlstore/migrations/postgres/000023_add_default_commander_enabled_to_ir_playbook.down.sql
  server/sqlstore/migrations/postgres/000023_add_default_commander_enabled_to_ir_playbook.up.sql
  server/sqlstore/migrations_test.go
Labels: 2: Dev Review

#1421 Mm 46094 long run name issue
  webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
Labels: 4: Reviews Complete

#1412 Update run participants table and related queries.
  server/api/playbook_runs.go
  server/api_runs_test.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook_run.go
  server/sqlstore/playbook_run_test.go
  server/sqlstore/stats.go
  server/sqlstore/stats_test.go
  server/sqlstore/support_for_test.go
Labels: 2: Dev Review

#1366 [MM-45116] Feature: playbooks insights
  go.mod
  go.sum
  server/api/playbooks.go
  server/app/playbook.go
  server/app/playbook_service.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_test.go
  webapp/package-lock.json
  webapp/package.json
  webapp/src/client.ts
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/playbook_access_modal.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/send_message_button.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/timeline_utils.ts
  webapp/src/components/checklist_item/inputs.tsx
  webapp/src/components/sidebar/sidebar.tsx
  webapp/src/components/team/team_selector.tsx
  webapp/src/hooks/general.ts
  webapp/src/index.tsx
  webapp/src/selectors.ts
  webapp/src/types/insights.ts
  webapp/src/websocket_events.ts
  webapp/tsconfig.json
  webapp/webpack.config.js
Labels: 4: Reviews Complete

#1426 Fix checklist dropdown z-index issue
  webapp/src/components/backstage/playbook_editor/playbook_editor.tsx
  webapp/src/components/checklist/checklist_list.tsx
  webapp/src/components/checklist/collapsible_checklist.tsx
Labels: 2: Dev Review

#1428 Fix view all updates button width
  webapp/src/components/backstage/playbook_runs/playbook_run/status_update.tsx
Labels: 2: Dev Review

#1418 MM-43277: fix channel actions modal dropdown cutoffs/overflows
  tests-e2e/cypress/integration/channels/general_actions_spec.js
  tests-e2e/cypress/integration/channels/retrospective_spec.js
  tests-e2e/cypress/integration/main_app_spec.js
  tests-e2e/cypress/integration/runs/rdp_main_retrospective_spec.js
  webapp/src/components/actions_modal.tsx
  webapp/src/components/actions_modal_action_children.tsx
  webapp/src/components/backstage/category_selector.tsx
  webapp/src/components/channel_actions_modal.tsx
  webapp/src/components/checklist/checklist_list.tsx
  webapp/src/components/checklist_item/checklist_item.tsx
  webapp/src/components/dot_menu.tsx
  webapp/src/components/portal.tsx
  webapp/src/components/run_actions_modal.tsx
  webapp/src/components/widgets/generic_modal.tsx
  webapp/src/hooks/general.ts
Labels: 2: Dev Review

#1424 Separate run participants graphql participants move
  server/api/graphql_playbook.go
  server/api/graphql_root.go
  server/api/graphql_root_playbook.go
  server/api/graphql_root_run.go
  server/api/graphql_run.go
  server/api/playbook_runs.go
  server/api/schema.graphqls
  server/api_graphql_runs_test.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  tests-e2e/cypress/integration/runs/rdp_main_header_spec.js
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_runs/playbook_run/context_menu.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/header.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/playbook_run.tsx
  webapp/src/graphql/generated_types.ts
  webapp/src/graphql/hooks.ts
  webapp/src/graphql/runs.graphql
Labels: 4: Reviews Complete

#1245 [MM-37996] create the new modal UI for the playbook run dialog
  server/sqlstore/playbook.go
  tests-e2e/cypress/integration/channels/rhs/home_spec.js
  tests-e2e/cypress/integration/playbooks/overview_spec.js
  webapp/i18n/en.json
  webapp/src/actions.ts
  webapp/src/components/backstage/playbook_editor/controls.tsx
  webapp/src/components/modals/run_playbook_modal.tsx
  webapp/src/components/rhs/rhs_home_item.tsx
  webapp/src/types/playbook.ts
Labels: 4: Reviews Complete

#1431 Add channel scheme role support
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/sqlstore/playbook_run.go
  server/sqlstore/playbook_run_test.go
  webapp/package-lock.json
Labels: 2: Dev Review

#1370 [MM-45741] Add following button to runs list
  webapp/i18n/en.json
  webapp/src/components/backstage/runs_list/row.tsx
  webapp/src/components/backstage/runs_list/run_list_header.tsx
Labels: 2: Dev Review

#1430 [MM-44815] Duplicate task as next task instead of the last task
  server/app/playbook_run_service.go
  webapp/src/components/checklist/generic_checklist.tsx
Labels: 2: Dev Review, 3: QA Review

#1425 Switch model for versioning golangci-lint
  Makefile
  server/telemetry/rudder_test.go
Labels: 4: Reviews Complete

#1451 add hover background color to pbe broadcast channel selector
  webapp/src/components/backstage/playbook_editor/outline/inputs/broadcast_channels_selector.tsx
Labels: 2: Dev Review

#1446 send message to channel when joined run has private channel
  assets/i18n/en.json
  client/playbook_runs.go
  server/api/playbook_runs.go
  server/api_graphql_runs_test.go
  server/api_runs_test.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  webapp/src/client.ts
Labels: 4: Reviews Complete

#1360 MM-45933: Playbook List Columns: Last used, Active runs, Runs in 30 days
  server/api/playbooks.go
  server/app/playbook.go
  server/app/sort.go
  server/sqlstore/playbook.go
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/backstage/playbook_list_row.tsx
  webapp/src/types/playbook.ts
Labels: 2: Dev Review

#1450 remove rounded edges in add-new-task button
  webapp/src/components/checklist/generic_checklist.tsx
Labels: 2: Dev Review

#1452 RHS: do not trigger inline edit if user is doing a text-selection
  webapp/src/components/rhs/rhs_about_description.tsx
  webapp/src/components/rhs/rhs_about_title.tsx
Labels: 4: Reviews Complete

#1436 Fix playbooks list refresh issue
  webapp/src/components/backstage/playbook_editor/controls.tsx
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/backstage/restore_playbook_modal.tsx
Labels: 4: Reviews Complete
