Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2022-05, with the labels that each got.

#1156 disable hover menu in checkist while dragging
  webapp/src/components/backstage/playbooks/playbook_preview_checklists.tsx
  webapp/src/components/checklist_item/checklist_item.tsx
  webapp/src/components/checklist_item/checklist_item_draggable.tsx
  webapp/src/components/rhs/rhs_checklist.tsx
  webapp/src/components/rhs/rhs_checklist_list.tsx
Labels: 4: Reviews Complete

#1148 update run status ask for confirmation if accidental cancel
  tests-e2e/cypress/integration/channels/rhs/status_update_spec.js
  tests-e2e/cypress/integration/channels/update_request_post_spec.js
  tests-e2e/cypress/integration/runs/details_spec.js
  tests-e2e/cypress/support/plugin/ui_commands.js
  webapp/src/components/modals/update_run_status_modal.tsx
Labels: 4: Reviews Complete

#1134 migrations: add create incident table migration
  server/sqlstore/migrations/mysql/000002_create_IR_incident.down.sql
  server/sqlstore/migrations/mysql/000002_create_IR_incident.up.sql
  server/sqlstore/migrations/postgres/000002_create_IR_incident.down.sql
  server/sqlstore/migrations/postgres/000002_create_IR_incident.up.sql
Labels: 4: Reviews Complete

#1154 [MM-42366] Add summary to the playbook editor
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_editor/outline/outline.tsx
  webapp/src/components/backstage/playbook_editor/outline/section_checklists.tsx
  webapp/src/components/backstage/playbook_editor/outline/section_summary.tsx
  webapp/src/components/text_edit.tsx
Labels: 2: Dev Review

#1161 add menuEnabled forced in outline section checklist
  webapp/src/components/backstage/playbook_editor/outline/section_checklists.tsx
Labels: 4: Reviews Complete

#1153 MM-43132: Prior work for Run Actions modal
  server/api_actions_test.go
  server/app/actions_service.go
  tests-e2e/cypress/integration/channels/general_actions_spec.js
  webapp/src/actions.ts
  webapp/src/components/actions_modal.tsx
  webapp/src/components/actions_modal_action.tsx
  webapp/src/components/actions_modal_action_children.tsx
  webapp/src/components/actions_modal_trigger.tsx
  webapp/src/components/backstage/playbook_edit/actions_edit.tsx
  webapp/src/components/backstage/playbook_edit/automation/webhook_setting.tsx
  webapp/src/components/backstage/playbook_edit/status_updates_edit.tsx
  webapp/src/components/channel_actions_modal.tsx
  webapp/src/components/patterned_text_area.tsx
  webapp/src/components/widgets/generic_modal.tsx
  webapp/src/index.tsx
  webapp/src/reducer.ts
  webapp/src/selectors.ts
  webapp/src/types/actions.ts
  webapp/src/types/channel_actions.ts
Labels: 4: Reviews Complete

#1160 MM-43132: Run actions
  server/app/playbook_run_service.go
  tests-e2e/cypress/integration/playbooks/edit_spec.js
  tests-e2e/cypress/integration/runs/actions_spec.js
  tests-e2e/cypress/support/plugin/ui_commands.js
  webapp/i18n/en.json
  webapp/src/client.ts
  webapp/src/components/backstage/channel_selector.tsx
  webapp/src/components/backstage/playbook_edit/automation/broadcast.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
  webapp/src/components/broadcast_channel_selector.tsx
  webapp/src/components/run_actions_modal.tsx
  webapp/src/reducer.ts
  webapp/src/types/playbook_run.ts
  webapp/src/types/run_actions.ts
Labels: 4: Reviews Complete

#1162 update run modal description with broadcast info
  tests-e2e/cypress/integration/channels/rhs/status_update_spec.js
  webapp/i18n/en.json
  webapp/src/client.ts
  webapp/src/components/backstage/playbook_runs/playbook_run_backstage/playbook_run_backstage.tsx
  webapp/src/components/backstage/route_leaving_guard.tsx
  webapp/src/components/modals/update_run_status_modal.tsx
  webapp/src/components/widgets/generic_modal.tsx
  webapp/src/hooks/general.ts
  webapp/src/types/playbook_run.ts
Labels: 1: UX Review, 2: Dev Review

#1157 Add telemetry for run actions
  server/api/playbook_runs.go
  server/app/mocks/mock_playbook_run_service.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
  server/telemetry/rudder_test.go
  webapp/src/types/playbook_run.ts
Labels: 4: Reviews Complete

#1163 Update client/playbook_run.go
  client/go.mod
  client/go.sum
  client/playbook_run.go
  client/playbook_runs.go
Labels: 4: Reviews Complete

#1171 MN-44032 avoid infinite loop in use ensure profiles
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/rhs/post_card.tsx
  webapp/src/hooks/general.test.ts
  webapp/src/hooks/general.ts
Labels: 4: Reviews Complete

#1180 mm-43425 add missing titles in RHS icons
  tests-e2e/cypress/integration/channels/rhs/checklist_spec.js
  webapp/i18n/en.json
  webapp/src/components/rhs/rhs_about_buttons.tsx
  webapp/src/components/rhs/rhs_checklist_list.tsx
Labels: 4: Reviews Complete

#1178 [MM-43880] Allow one-character playbook names
  server/app/playbook_run_service.go
  server/app/playbook_run_service_test.go
Labels: 4: Reviews Complete

#1181 Fix checklist item render issue
  tests-e2e/cypress/integration/channels/rhs/checklist_spec.js
  webapp/src/components/checklist/generic_checklist.tsx
Labels: 2: Dev Review

#1188 MM-44241: ensure application/json
  .circleci/config.yml
  webapp/src/client.ts
Labels: 4: Reviews Complete

#1186 MM-41875 Introducing graphql with playbooks
  Makefile
  client/client.go
  client/playbook.go
  go.mod
  go.sum
  server/api/api.go
  server/api/graphql.go
  server/api/graphql_playbook.go
  server/api/graphql_root.go
  server/api/graphqli.html
  server/api/playbooks.go
  server/api/schema.graphqls
  server/api_graphql_playbooks_test.go
  server/app/permissions_service.go
  server/app/playbook.go
  server/main.go
  server/main_test.go
  server/plugin.go
  server/sqlstore/playbook.go
  tests-e2e/package-lock.json
  webapp/graphql_gen.yml
  webapp/package-lock.json
  webapp/package.json
  webapp/src/client.ts
  webapp/src/components/backstage/archive_playbook_modal.tsx
  webapp/src/components/backstage/playbook_edit/metrics/shared.ts
  webapp/src/components/backstage/playbook_editor/controls.tsx
  webapp/src/components/backstage/playbook_editor/outline/outline.tsx
  webapp/src/components/backstage/playbook_editor/outline/section_actions.tsx
  webapp/src/components/backstage/playbook_editor/outline/section_retrospective.tsx
  webapp/src/components/backstage/playbook_editor/outline/section_status_updates.tsx
  webapp/src/components/backstage/playbook_editor/playbook_editor.tsx
  webapp/src/components/backstage/playbooks/metrics/metrics_card.tsx
  webapp/src/components/backstage/playbooks/metrics/metrics_run_list.tsx
  webapp/src/components/backstage/playbooks/metrics/metrics_stats_view.tsx
  webapp/src/components/backstage/playbooks/metrics/playbook_key_metrics.tsx
  webapp/src/components/backstage/playbooks/playbook.tsx
  webapp/src/components/backstage/playbooks/playbook_usage.tsx
  webapp/src/components/checklist/checklist_list.tsx
  webapp/src/graphql/generated_types.ts
  webapp/src/graphql/hooks.ts
  webapp/src/graphql/playbook.graphql
  webapp/src/hooks/permissions.ts
  webapp/src/index.tsx
  webapp/src/types/playbook.ts
Labels: 2: Dev Review

#1179 Mm 43423 inconsistent hover icons
  webapp/src/components/checklist/collapsible_checklist_hover_menu.tsx
  webapp/src/components/collapsible_checklist_hover_menu.tsx
  webapp/src/components/dot_menu.tsx
  webapp/src/components/multi_checkbox.tsx
  webapp/src/components/rhs/rhs_about_buttons.tsx
  webapp/src/components/rhs/rhs_checklist_list.tsx
Labels: 4: Reviews Complete

#1172 Upgrade server dep to have safe server e2e plugin initialisation
  .circleci/config.yml
  build/go.mod
  build/go.sum
  client/go.mod
  client/go.sum
  go.mod
  go.sum
Labels: 2: Dev Review

#1191 Fix console spam
  webapp/src/components/checklist/checklist_list.tsx
Labels: 2: Dev Review

#1185 Fix task due date functionality for playbooks
  client/playbook.go
  server/api/playbook_runs.go
  server/api_runs_test.go
  webapp/i18n/en.json
  webapp/src/components/checklist_item/duedate.tsx
  webapp/src/components/datetime_selector.tsx
Labels: 4: Reviews Complete

#1184 handle optimistic updates to checkbox in checklist item
  webapp/src/client.ts
  webapp/src/components/checklist_item/checklist_item.tsx
  webapp/src/components/checklist_item/checklist_item_draggable.tsx
  webapp/src/components/checklist_item/inputs.tsx
Labels: 4: Reviews Complete

#1177 MM-42206: avoid concurrent profile fetch
  webapp/src/hooks/general.test.ts
  webapp/src/hooks/general.ts
Labels: 4: Reviews Complete

#1194 do not log error if 0 actions in channel when a user joins
  server/api/playbook_runs.go
  server/app/actions_service.go
Labels: 4: Reviews Complete

#1201 do not ask for channel actions if the channel has been already visited
  webapp/src/websocket_events.ts
Labels: 2: Dev Review

#1199 force empty title in menuItem to prevent trigger title from propagating
  webapp/src/components/dot_menu.tsx
Labels: 2: Dev Review

#1197 modal manually centered
  webapp/src/components/actions_modal.tsx
  webapp/src/components/channel_actions_modal.tsx
  webapp/src/components/run_actions_modal.tsx
Labels: 2: Dev Review

#1198 RHS: keep full assignee pill when due date and not state-open
  tests-e2e/cypress/integration/channels/rhs/checklist_spec.js
  webapp/src/components/checklist_item/checklist_item.tsx
Labels: 2: Dev Review

#1211 [MM-44549] Fix checklist ui issues
  webapp/src/components/checklist/collapsible_checklist.tsx
  webapp/src/components/checklist_item/hover_menu.tsx
Labels: 2: Dev Review

#1206 Translations update from Mattermost Weblate
  webapp/i18n/de.json
  webapp/i18n/en_AU.json
  webapp/i18n/hu.json
  webapp/i18n/ja.json
  webapp/i18n/nl.json
  webapp/i18n/pl.json
  webapp/i18n/tr.json
Labels: Do Not Merge/Mattermod

#1203 MM-44410 Add subresource integrity to graphql html
  server/api/graphqli.html
Labels: 4: Reviews Complete

#1214 add computed schemeRoles to playbook query response - fix start run
  .circleci/config.yml
  Makefile
  server/api/schema.graphqls
  webapp/src/graphql/generated_types.ts
  webapp/src/graphql/playbook.graphql
Labels: 2: Dev Review

#1202 Add GraphQL metrics handing.
  server/api/graphql_root.go
  server/api/schema.graphqls
  server/api_graphql_playbooks_test.go
  server/app/playbook.go
  server/sqlstore/playbook.go
  webapp/src/graphql/generated_types.ts
Labels: 4: Reviews Complete

#1218 MM-44498: Fix typing UX on channel name input
  webapp/src/components/backstage/playbook_edit/automation/channel_access.tsx
  webapp/src/components/backstage/playbook_editor/outline/section_actions.tsx
  webapp/src/graphql/hooks.ts
  webapp/src/hooks/general.ts
Labels: 2: Dev Review

#1219 MM-44508 Add ESC and Enter handing to text inputs.
  webapp/src/components/markdown_edit.tsx
  webapp/src/components/text_edit.tsx
Labels: 2: Dev Review

#1224 Translations update from Mattermost Weblate
  webapp/i18n/en_AU.json
  webapp/i18n/hr.json
  webapp/i18n/hu.json
  webapp/i18n/nl.json
  webapp/i18n/pl.json
  webapp/i18n/tr.json
Labels: Do Not Merge/Mattermod

#1220 MM-44647 Fix inverted check for default owner.
  server/api/graphql_root.go
  server/api_graphql_playbooks_test.go
Labels: 4: Reviews Complete

#1223 Mm 44510 status update broadcast channel not enabled on run
  server/app/playbook.go
  tests-e2e/cypress/integration/playbooks/status_update_spec.js
  webapp/src/components/backstage/playbook_editor/outline/inputs/broadcast_channels_selector.tsx
  webapp/src/components/backstage/playbook_editor/outline/inputs/webhooks_input.tsx
  webapp/src/components/backstage/playbook_editor/outline/outline.tsx
  webapp/src/components/backstage/playbook_editor/outline/section_status_updates.tsx
  webapp/src/types/playbook.ts
Labels: 1: UX Review
