Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2022-04, with the labels that each got.

#1112 MM-42247: Remove template background
  webapp/src/components/assets/no_content_playbooks_svg.tsx
  webapp/src/components/backstage/playbook_list.tsx
Labels: 4: Reviews Complete

#1119 MM-43037: Fix prompt post deletion
  server/api/signal.go
  tests-e2e/cypress/integration/channels/general_actions_spec.js
Labels: 4: Reviews Complete

#1121 MM-41513: Restrict private playbooks (#1017)
  server/api_playbooks_test.go
  server/app/permissions_service.go
  server/main_test.go
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_access_modal.tsx
  webapp/src/components/backstage/public_private_selector.tsx
  webapp/src/hooks/general.ts
Labels: 4: Reviews Complete

#1126 Mm 42843 hide trash icon command
  webapp/src/components/command_input.tsx
Labels: 4: Reviews Complete

#1115 Mm 42149 rhs add due date info to checklist
  assets/i18n/en.json
  server/api/playbook_runs.go
  server/app/mocks/mock_license_checker.go
  server/app/permissions_service.go
  server/enterprise/license.go
  server/telemetry/rudder.go
  server/telemetry/rudder_test.go
  tests-e2e/cypress/integration/channels/rhs/checklist_spec.js
  webapp/i18n/en.json
  webapp/src/components/backstage/upgrade_modal_data.tsx
  webapp/src/components/checklist_item.tsx
  webapp/src/components/checklist_item/checklist_item.tsx
  webapp/src/components/checklist_item/command.tsx
  webapp/src/components/checklist_item/duedate.tsx
  webapp/src/components/checklist_item/hover_menu.tsx
  webapp/src/components/datetime_selector.tsx
  webapp/src/components/rhs/rhs_checklist_list.tsx
  webapp/src/components/rhs/rhs_shared.tsx
  webapp/src/constants.ts
  webapp/src/hooks/general.ts
Labels: 1: UX Review, 2: Dev Review

#1113 MM-42509: Change initial fetch to get only in progress runs
  tests-e2e/cypress/integration/channels/rhs_spec.js
  webapp/src/components/rhs/rhs_main.tsx
  webapp/src/rhs_opener.ts
Labels: 4: Reviews Complete

#1117 [GH-19356] MM-41063, MM-40565: Increase new task dialog description length
  server/app/playbook_run_service.go
Labels: 4: Reviews Complete

#1124 [MM-42080] Skip checklist
  server/api/playbook_runs.go
  server/app/mocks/mock_playbook_run_service.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/telemetry/noop.go
  server/telemetry/rudder.go
  webapp/i18n/en.json
  webapp/src/client.ts
  webapp/src/components/collapsible_checklist.tsx
  webapp/src/components/collapsible_checklist_hover_menu.tsx
Labels: 1: UX Review, 2: Dev Review

#1107 MM-40820, MM-40857: Translate datetime_input
  tests-e2e/cypress/integration/channels/retrospective_spec.js
  tests-e2e/cypress/integration/channels/rhs/status_update_spec.js
  tests-e2e/cypress/integration/playbooks/edit_metrics_spec.js
  webapp/i18n/en.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/__snapshots__/formatted_duration.test.tsx.snap
  webapp/src/components/backstage/default_update_timer.tsx
  webapp/src/components/backstage/public_private_selector.tsx
  webapp/src/components/backstage/runs_list/row.tsx
  webapp/src/components/datetime_input.tsx
  webapp/src/components/datetime_parsing.test.ts
  webapp/src/components/datetime_parsing.ts
  webapp/src/components/datetime_selector.tsx
  webapp/src/components/formatted_duration.test.tsx
  webapp/src/components/formatted_duration.tsx
  webapp/src/components/modals/update_run_status_modal.tsx
  webapp/src/components/update_request_post.tsx
Labels: 4: Reviews Complete

#1122 [MM-42080] Support item addition
  tests-e2e/cypress/support/plugin/ui_commands.js
  webapp/i18n/en.json
  webapp/src/client.ts
  webapp/src/components/backstage/playbooks/playbook_preview_checklists.tsx
  webapp/src/components/checklist_item/assign_to.tsx
  webapp/src/components/checklist_item/checklist_item.tsx
  webapp/src/components/checklist_item/checklist_item_draggable.tsx
  webapp/src/components/checklist_item/command.tsx
  webapp/src/components/checklist_item/description.tsx
  webapp/src/components/checklist_item/duedate.tsx
  webapp/src/components/checklist_item/hover_menu.tsx
  webapp/src/components/checklist_item/inputs.tsx
  webapp/src/components/checklist_item/title.tsx
  webapp/src/components/collapsible_checklist_hover_menu.tsx
  webapp/src/components/profile/profile.tsx
  webapp/src/components/profile/profile_button.tsx
  webapp/src/components/profile/profile_selector.tsx
  webapp/src/components/rhs/rhs_checklist.tsx
  webapp/src/components/rhs/rhs_checklist_list.tsx
  webapp/src/components/rhs/rhs_shared.tsx
Labels: 1: UX Review, 2: Dev Review

#1130 [MM-43417] Fix placeholder text
  webapp/i18n/en.json
  webapp/src/components/checklist_item/description.tsx
Labels: 4: Reviews Complete

#1125 sqlstore/migrations: add morph as schema migrations engine
  go.mod
  go.sum
  server/sqlstore/migrate.go
  server/sqlstore/migrations/mysql/000001_create_IR_system.down.sql
  server/sqlstore/migrations/mysql/000001_create_IR_system.up.sql
  server/sqlstore/migrations/postgres/000001_create_IR_system.down.sql
  server/sqlstore/migrations/postgres/000001_create_IR_system.up.sql
  server/sqlstore/support_for_test.go
  server/sqlstore/user_info_test.go
Labels: 4: Reviews Complete

#1135 Mm 43165 update run data model to include actions flags
  server/api/playbook_runs.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/app/playbook_run_service_test.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook_run.go
  tests-e2e/cypress/integration/channels/update_request_post_spec.js
Labels: 2: Dev Review

#1142 e2e: Add basic smoke tests for playbook tours
  tests-e2e/cypress/integration/tours_spec.js
Labels: 2: Dev Review

#1138 Fix private/public icon update issue
  webapp/src/actions.ts
  webapp/src/components/backstage/playbook_access_modal.tsx
  webapp/src/components/backstage/playbooks/playbook.tsx
Labels: 2: Dev Review

#1140 Add endpoint to modify status update broadcast settings
  client/playbook_run.go
  client/playbook_runs.go
  server/api/playbook_runs.go
  server/api_runs_test.go
  server/app/mocks/mock_playbook_run_service.go
  server/app/mocks/mock_playbook_run_store.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/sqlstore/playbook_run_test.go
Labels: 4: Reviews Complete

#1145 Remove followers run action flag
  server/api/playbook_runs.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/app/playbook_run_service_test.go
  server/sqlstore/migrations.go
  server/sqlstore/playbook_run.go
Labels: 2: Dev Review

#1147 DX, Deps: fix console warnings, npm use exact version, better displayName support
  webapp/.npmrc
  webapp/babel.config.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/actions_modal.tsx
  webapp/src/components/widgets/generic_modal.tsx
Labels: 4: Reviews Complete

#1159 Fix long string overflow in status update reminder
  webapp/src/components/update_request_post.tsx
Labels: 4: Reviews Complete

#1146 supporting e2e tests for webapp changes
  tests-e2e/cypress/integration/playbooks/overview_spec.js
Labels: 4: Reviews Complete
