Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2023-11, with the labels that each got.

#1877 Move RHS opener to GraphQL
  server/api/graphql.go
  server/api/graphql_loader_run.go
  server/api/graphql_root_run.go
  server/api/graphql_run.go
  server/api_graphql_runs_test.go
  server/app/playbook_run.go
  server/plugin.go
  server/sqlstore/playbook_run.go
  webapp/src/index.tsx
  webapp/src/rhs_opener.ts
Labels: 4: Reviews Complete, QA Review Done

#1878 MM-54989 Fix team run team interaction.
  server/api_runs_test.go
  server/app/permissions_service.go
Labels: 2: Dev Review

#1880 Prevent extra JSON from being stored in actions.
  server/api/actions.go
  server/api_actions_test.go
  server/app/action.go
  server/app/actions_service.go
  server/safemapstructure/safemapstructure.go
  server/safemapstructure/safemapstructure_test.go
Labels: 2: Dev Review

#1884 Translations update from Mattermost Weblate
  webapp/i18n/fr.json
Labels: Do Not Merge/Mattermod
