Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2023-01, with the labels that each got.

#1706 Fix e2e tests
  tests-e2e/cypress/integration/channels/rhs_spec.js
  tests-e2e/cypress/integration/playbooks/overview_spec.js
Labels: 2: Dev Review

#1688 MM-46983 Visual feedback for invalid run names
  tests-e2e/cypress/integration/playbooks/start_run_spec.js
  webapp/i18n/en.json
  webapp/src/components/assets/inputs.tsx
  webapp/src/components/modals/new_run_playbook_modal.tsx
  webapp/src/constants.ts
Labels: 4: Reviews Complete

#1704 Exclude tasks without a due date from daily digest
  server/app/playbook_run_service.go
Labels: 4: Reviews Complete

#1703 Safer json marshal
  server/app/playbook_run.go
  server/app/playbook_run_test.go
Labels: 2: Dev Review

#1707 MM-48600 Fix run actions modal not updating state when changing run
  webapp/src/components/run_actions_modal.tsx
Labels: 4: Reviews Complete

#1709 MM-48913 Fix jumpy participant list in RHS
  webapp/src/components/rhs/rhs_participants.tsx
Labels: 2: Dev Review

#1708 MM-48599 Improve toast for participating in a run and toasts in general
  webapp/src/components/backstage/toast.tsx
  webapp/src/components/backstage/toast_banner.tsx
  webapp/src/components/rhs/rhs_run_details.tsx
Labels: 1: UX Review, 2: Dev Review

#1714 [MM-49579] Add missing returns
  server/api/actions.go
  server/api/bot.go
  server/api/playbook_runs.go
Labels: 4: Reviews Complete

#1702 Drop linkruntoexistingchannelenabled
  client/settings.go
  server/api/settings.go
  server/api_settings_test.go
  server/config/configuration.go
  tests-e2e/cypress/integration/api/settings_spec.js
  tests-e2e/cypress/integration/channels/rhs/start_run_rhs_spec.js
  tests-e2e/cypress/integration/channels/slash_command/commands_spec.js
  tests-e2e/cypress/integration/playbooks/edit_spec.js
  tests-e2e/cypress/integration/playbooks/overview_spec.js
  tests-e2e/cypress/integration/playbooks/start_run_spec.js
  webapp/src/components/backstage/playbook_edit/automation/channel_access.tsx
  webapp/src/components/backstage/playbook_editor/controls.tsx
  webapp/src/components/backstage/playbook_list_row.tsx
  webapp/src/components/modals/run_playbook_modal.tsx
  webapp/src/components/rhs/rhs_home_item.tsx
  webapp/src/hooks/general.ts
  webapp/src/selectors.ts
Labels: 4: Reviews Complete

#1697 MM-49060: status update post for non-participants
  tests-e2e/cypress/integration/channels/update_request_post_spec.js
  webapp/src/components/update_request_post.tsx
Labels: 4: Reviews Complete

#1715 useMemo with debounce
  tests-e2e/cypress/integration/playbooks/edit_spec.js
  tests-e2e/cypress/integration/runs/rdp_main_retrospective_spec.js
  webapp/src/components/backstage/playbook_runs/playbook_run/retrospective.tsx
  webapp/src/components/backstage/profile_autocomplete.tsx
  webapp/src/components/backstage/runs_list/filters.tsx
  webapp/src/components/datetime_input.tsx
  webapp/src/components/datetime_selector.tsx
  webapp/src/components/rhs/rhs_run_list.tsx
  webapp/src/components/widgets/text_with_tooltip.tsx
  webapp/src/hooks/crud.ts
  webapp/src/hooks/general.ts
Labels: 4: Reviews Complete

#1730 simplify code and remove comment at getowners
  server/app/playbook_run_service.go
Labels: 2: Dev Review

#1733 force golangci to recent commit to solve macos issue
  .golangci.yml
  Makefile
  server/app/playbook_run_service.go
Labels: 2: Dev Review

#1737 set to true tutorial point for drafts in e2e
  tests-e2e/cypress/support/api/preference.js
Labels: 2: Dev Review

#1712 MM-48582 Playbook import via drag and drop
  tests-e2e/cypress/fixtures/playbook-export.json
  tests-e2e/cypress/integration/playbooks/list_spec.js
  webapp/i18n/en.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/assets/files_overlay.png
  webapp/src/components/assets/mattermost_logo_svg.tsx
  webapp/src/components/backstage/backstage.tsx
  webapp/src/components/backstage/file_drag_detection.tsx
  webapp/src/components/backstage/file_upload_overlay.tsx
  webapp/src/components/backstage/import_playbook.tsx
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/types/assets.d.ts
  webapp/webpack.config.js
Labels: 4: Reviews Complete

#1711 GraphQL improvements.
  .circleci/config.yml
  server/api/graphql_run.go
  server/api/schema.graphqls
  tests-e2e/cypress/integration/playbooks/list_spec.js
  webapp/graphql_gen.ts
  webapp/graphql_gen.yml
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/backstage/lhs_navigation.tsx
  webapp/src/components/backstage/metrics/metrics_card.tsx
  webapp/src/components/backstage/metrics/metrics_row.tsx
  webapp/src/components/backstage/metrics/metrics_run_list_header.tsx
  webapp/src/components/backstage/metrics/metrics_stats_view.tsx
  webapp/src/components/backstage/playbook_edit/metrics/metric_edit.tsx
  webapp/src/components/backstage/playbook_edit/metrics/metric_view.tsx
  webapp/src/components/backstage/playbook_edit/metrics/metrics.tsx
  webapp/src/components/backstage/playbook_edit/metrics/shared.ts
  webapp/src/components/backstage/playbook_runs/playbook_run/finish_run.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/metrics/metrics_data.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_metrics.tsx
  webapp/src/components/checklist/checklist_list.tsx
  webapp/src/components/checklist_item/checklist_item.tsx
  webapp/src/components/modals/update_run_status_modal.tsx
  webapp/src/components/playbooks_selector.tsx
  webapp/src/components/retrospective_post.tsx
  webapp/src/components/rhs/rhs_main.tsx
  webapp/src/components/sidebar/playbooks_sidebar.tsx
  webapp/src/graphql/generated/fragment-masking.ts
  webapp/src/graphql/generated/gql.ts
  webapp/src/graphql/generated/graphql.ts
  webapp/src/graphql/generated/index.ts
  webapp/src/graphql/generated_types.ts
  webapp/src/graphql/hooks.ts
  webapp/src/graphql/playbook.graphql
  webapp/src/graphql/runs.graphql
  webapp/src/hooks/routing.ts
  webapp/src/types/playbook.ts
Labels: 2: Dev Review

#1739 Fix drag and drop import e2e tests
  tests-e2e/cypress/integration/playbooks/list_spec.js
Labels: 4: Reviews Complete

#1749 Fix a minor typo in gql_gen config
  webapp/graphql_gen.ts
Labels: 2: Dev Review

#1716 Live reload for server code
  Makefile
  modd.conf
Labels: 2: Dev Review

#1754 update go to 1.19
  .circleci/config.yml
  client/go.mod
  go.mod
Labels: 4: Reviews Complete

#1758 Downgrade field missing errors to warnings for logging.
  server/api/graphql.go
  server/api_graphql_runs_test.go
Labels: 2: Dev Review

#1732 Clean unused code
  .ts-prunerc
  Makefile
  server/api/bot.go
  server/api/categories.go
  server/api/playbook_runs.go
  server/app/mocks/mock_job_once_scheduler.go
  server/bot/bot.go
  server/bot/mocks/mock_poster.go
  server/bot/poster.go
  server/sqlstore/mocks/mock_configurationapi.go
  server/sqlstore/mocks/mock_kvapi.go
  server/sqlstore/mocks/mock_storeapi.go
  webapp/graphql_gen.ts
  webapp/i18n/en.json
  webapp/rudder_transform.js
  webapp/src/actions.ts
  webapp/src/client.ts
  webapp/src/components/assets/box_open_svg.tsx
  webapp/src/components/assets/no_content_playbooks_rhs_svg.tsx
  webapp/src/components/assets/page_run_svg.tsx
  webapp/src/components/assets/upgrade_retrospective_svg.tsx
  webapp/src/components/assets/upgrade_timeline_background_svg.tsx
  webapp/src/components/backstage/playbook_edit/automation/categorize_playbook_run.tsx
  webapp/src/components/backstage/playbook_editor/controls.tsx
  webapp/src/components/backstage/playbook_editor/outline/section_retrospective.tsx
  webapp/src/components/backstage/playbook_list_row.tsx
  webapp/src/components/backstage/playbook_preview_cards.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/add_participant_modal.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/become_participant_modal.tsx
  webapp/src/components/backstage/runs_page_no_content.tsx
  webapp/src/components/datetime_input.tsx
  webapp/src/components/modals/run_playbook_modal.tsx
  webapp/src/components/multi_select.tsx
  webapp/src/components/rhs/rhs_home_item.tsx
  webapp/src/components/rhs/rhs_run_list.tsx
  webapp/src/components/rhs/rhs_timeline_placeholder.tsx
  webapp/src/constants.ts
  webapp/src/hooks/general.test.ts
  webapp/src/hooks/general.ts
  webapp/src/index.tsx
  webapp/src/reducer.ts
  webapp/src/types/actions.ts
  webapp/src/types/playbook.ts
  webapp/src/types/rhs.ts
  webapp/src/types/run_actions.ts
  webapp/src/types/stats.ts
Labels: 2: Dev Review

#1673 Translations update from Mattermost Weblate
  assets/i18n/de.json
  assets/i18n/hr.json
  assets/i18n/hu.json
  assets/i18n/nl.json
  assets/i18n/pl.json
  assets/i18n/sv.json
  assets/i18n/tr.json
  webapp/i18n/de.json
  webapp/i18n/en_AU.json
  webapp/i18n/hr.json
  webapp/i18n/hu.json
  webapp/i18n/ja.json
  webapp/i18n/nl.json
  webapp/i18n/pl.json
  webapp/i18n/sv.json
  webapp/i18n/tr.json
Labels: Do Not Merge/Mattermod

#1742 MM-48761: Update legacy documentation links
  README.md
  tests-e2e/cypress/fixtures/playbook-export.json
  webapp/src/types/playbook.ts
Labels: 4: Reviews Complete

#1761 Translations update from Mattermost Weblate
  assets/i18n/ja.json
  assets/i18n/sv.json
  webapp/i18n/hr.json
  webapp/i18n/ja.json
Labels: 4: Reviews Complete

#1759 Avoid spurious session errors
  server/api/signal.go
  server/app/action.go
  server/app/actions_service.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/app/urls.go
  server/command/command.go
  server/plugin.go
  tests-e2e/cypress/integration/channels/run_dialog_spec.js
Labels: 2: Dev Review

#1753 fix several styles at channel selector
  webapp/src/components/actions_modal.tsx
  webapp/src/components/backstage/channel_selector.tsx
  webapp/src/components/backstage/styles.tsx
  webapp/src/components/broadcast_channel_selector.tsx
  webapp/src/components/widgets/generic_modal.tsx
Labels: 4: Reviews Complete

#1751 revert #1554 - allow run participants to post update
  server/api/playbook_runs.go
  server/api_runs_test.go
  server/app/permissions_service.go
Labels: 2: Dev Review

#1762 MM-49791: Disable edit summary after run finished
  tests-e2e/cypress/integration/channels/rhs/header_spec.js
  tests-e2e/cypress/integration/runs/rdp_main_summary_spec.js
  webapp/src/components/backstage/playbook_runs/playbook_run/checklists.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/summary.tsx
  webapp/src/components/checklist/checklist_list.tsx
  webapp/src/components/checklist/generic_checklist.tsx
  webapp/src/components/checklist_item/checklist_item.tsx
  webapp/src/components/checklist_item/checklist_item_draggable.tsx
  webapp/src/components/checklist_item/inputs.tsx
  webapp/src/components/rhs/rhs_checklist_list.tsx
  webapp/src/components/rhs/rhs_run_details.tsx
Labels: 2: Dev Review

#1780 When focus is lost on LHS stop polling
  webapp/src/components/sidebar/playbooks_sidebar.tsx
Labels: 4: Reviews Complete

#1788 make get actions trigger just if modal is shown
  webapp/src/components/channel_actions_modal.tsx
Labels: 4: Reviews Complete
