Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2023-12, with the labels that each got.

#1881 MM-55175 Do not hide assigned user name
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_overview.tsx
  webapp/src/components/checklist_item/assign_to.tsx
  webapp/src/components/checklist_item/checklist_item.tsx
  webapp/src/components/profile/profile_button.tsx
  webapp/src/components/profile/profile_selector.tsx
Labels: 4: Reviews Complete, Lifecycle/1:stale, QA Review Done, Contributor

#1886 Translations update from Mattermost Weblate
  webapp/i18n/hu.json
Labels: Lifecycle/frozen, Do Not Merge/Mattermod

#1887 Sync with starter template
  .editorconfig
  .gitignore
  Makefile
  build/manifest/main.go
  build/sync/README.md
  build/sync/main.go
  build/sync/plan.yml
  build/sync/plan/actions.go
  build/sync/plan/actions_test.go
  build/sync/plan/checks.go
  build/sync/plan/checks_test.go
  build/sync/plan/git/file_history.go
  build/sync/plan/git/file_history_test.go
  build/sync/plan/git/testdata/testfile.txt
  build/sync/plan/plan.go
  build/sync/plan/plan_test.go
  build/sync/plan/setup.go
  build/sync/plan/testdata/a
  build/sync/plan/testdata/b/c
Labels: 4: Reviews Complete
