Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2024-07, with the labels that each got.

#1923 [MM-58234] Support negative duration
  webapp/src/components/backstage/metrics/metrics_row.tsx
  webapp/src/components/formatted_duration.test.tsx
  webapp/src/components/formatted_duration.tsx
Labels: 2: Dev Review, QA Deferred

#1927 [MM-58791] Restrict graphql errors
  e2e-tests/tests/integration/playbooks/api/graphql_errors_spec.js
  server/api/graphql.go
  server/api_graphql_runs_test.go
Labels: 4: Reviews Complete

#1924 Translations update from Mattermost Weblate
  webapp/i18n/hr.json
Labels: Lifecycle/1:stale, Do Not Merge/Mattermod

#1918 [MM-58377] Make sure we have an enterprise license when activating the plugin
  server/api_playbooks_test.go
  server/main_test.go
  server/plugin.go
Labels: 2: Dev Review

#1928 Translations update from Mattermost Weblate
  assets/i18n/nb_NO.json
  webapp/i18n/nb_NO.json
Labels: Do Not Merge/Mattermod

#1926 MM-48603 Fixed RHS hover styling on checklist area
  webapp/src/components/rhs/rhs_checklist_list.tsx
Labels: 2: Dev Review

#1925 MM-48411 Fixed truncation on long team names
  webapp/src/components/sidebar/sidebar.tsx
Labels: 2: Dev Review
