Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2024-11, with the labels that each got.

#1942 Support the MS Teams Tab App
  assets/msteams_icon.svg
  client/actions.go
  client/client.go
  client/playbook_runs.go
  client/playbooks.go
  client/reminders.go
  client/settings.go
  client/stats.go
  client/tabapp.go
  client/telemetry.go
  go.mod
  go.sum
  plugin.json
  server/api/api.go
  server/api/permutation_test.go
  server/api/tabapp.go
  server/api/tabapp_test.go
  server/api_tabapp_test.go
  server/config/configuration.go
  server/config/service.go
  server/main_test.go
  server/plugin.go
  server/tabapp.go
Labels: 4: Reviews Complete, QA Deferred

#1951 RHS header styling fixed
  webapp/src/components/rhs/rhs_run_list.tsx
Labels: 2: Dev Review, Lifecycle/1:stale, Setup Cloud Test Server, Hacktoberfest, Contributor, QA Deferred

#1955 Translations update from Mattermost Weblate
  assets/i18n/nb_NO.json
Labels: Do Not Merge/Mattermod

#1953 MM-61478: fix alignment for backstage RHS
  webapp/src/components/backstage/rhs/rhs.tsx
Labels: 2: Dev Review, QA Deferred
