Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2024-12, with the labels that each got.

#1969 Translations update from Mattermost Weblate
  webapp/i18n/cs.json
  webapp/i18n/nb_NO.json
  webapp/i18n/pl.json
Labels: Do Not Merge/Mattermod

#1962 Fixing keywords post
  server/api/playbook_runs.go
  server/api/signal.go
  server/api_runs_test.go
Labels: 2: Dev Review

#1957 [MM-61124] Add diagnostics data to the Support Packet
  go.mod
  go.sum
  server/api_runs_test.go
  server/app/playbook.go
  server/app/playbook_service.go
  server/command/command.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_test.go
  server/support_packet.go
  server/support_packet_test.go
Labels: 4: Reviews Complete

#1976 Translations update from Mattermost Weblate
  webapp/i18n/cs.json
Labels: Do Not Merge/Mattermod
