Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2024-08, with the labels that each got.

#1930 Translations update from Mattermost Weblate
  assets/i18n/nb_NO.json
Labels: Do Not Merge/Mattermod

#1933 Translations update from Mattermost Weblate
  webapp/i18n/en_AU.json
Labels: Do Not Merge/Mattermod

#1934 Cherry Pick of MM-58432 - #1911
  e2e-tests/tests/integration/playbooks/channels/general_actions_spec.js
  server/api/signal.go
  server/plugin.go
Labels: 4: Reviews Complete

#1936 Cherry pick of MM-58843 - #1920
  e2e-tests/tests/integration/playbooks/playbooks/overview_spec.js
  e2e-tests/tests/integration/playbooks/runs/rdp_general_spec.js
  webapp/src/components/backstage/main_body.tsx
  webapp/src/components/backstage/playbook_editor/playbook_editor.tsx
Labels: 2: Dev Review

#1929 MM-58173 fix overlapping UI and modals
  webapp/src/components/actions_modal.tsx
  webapp/src/components/backstage/playbook_edit/metrics/metrics.tsx
  webapp/src/components/backstage/public_private_selector.tsx
  webapp/src/components/backstage/search_input.tsx
  webapp/src/components/backstage/styles.tsx
  webapp/src/components/markdown_textbox.tsx
  webapp/src/components/modals/run_playbook_modal.tsx
  webapp/src/components/rhs/rhs_run_details_tour_dialog.tsx
  webapp/src/components/widgets/confirmation_modal_light.tsx
  webapp/src/components/widgets/generic_modal.tsx
Labels: 4: Reviews Complete, QA Deferred

#1937 Translations update from Mattermost Weblate
  webapp/i18n/sv.json
Labels: Do Not Merge/Mattermod
