Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2024-09, with the labels that each got.

#1941 fix DEFAULT_* handling
  Makefile
Labels: 4: Reviews Complete, QA Deferred

#1939 MM-60420: treat bots as participants
  server/sqlstore/playbook_run.go
  server/sqlstore/playbook_run_test.go
  server/sqlstore/stats.go
  server/sqlstore/stats_test.go
Labels: QA Deferred

#1945 Translations update from Mattermost Weblate
  webapp/i18n/hu.json
  webapp/i18n/nb_NO.json
Labels: Do Not Merge/Mattermod
