Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2024-06, with the labels that each got.

#1912 Translations update from Mattermost Weblate
  webapp/i18n/de.json
  webapp/i18n/nl.json
Labels: Do Not Merge/Mattermod

#1919 Translations update from Mattermost Weblate
  webapp/i18n/tr.json
Labels: 4: Reviews Complete

#1914 [MM-55473] Hide preview box if not in preview mode
  webapp/src/components/markdown_textbox.tsx
Labels: 4: Reviews Complete, QA Deferred

#1920 [MM-58843] Only accept valid MM ids in URLs
  e2e-tests/tests/integration/playbooks/playbooks/overview_spec.js
  e2e-tests/tests/integration/playbooks/runs/rdp_general_spec.js
  webapp/src/components/backstage/main_body.tsx
  webapp/src/components/backstage/playbook_editor/playbook_editor.tsx
Labels: 2: Dev Review
