Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2024-03, with the labels that each got.

#1895 MM-56402: Close the store on Deactivate
  server/plugin.go
Labels: 4: Reviews Complete

#1889 Fix task slash commands being run.
  server/api/playbook_runs.go
  webapp/src/client.ts
Labels: 2: Dev Review

#1892 MM-56461 fix guest user access to public runs.
  server/api/graphql_root_run.go
Labels: 2: Dev Review

#1897 Fix websocket events
  server/app/reminder.go
Labels: 2: Dev Review

#1899 Fixing moving channel links behaviour
  server/api/graphql_root_run.go
  server/api/playbook_runs.go
  server/api_graphql_runs_test.go
Labels: 2: Dev Review, 3: Security Review

#1898 Fixing behavour of /playbook add slash command.
  server/command/command.go
Labels: 2: Dev Review

#1900 Fixing slash commands on runs
  server/api/playbook_runs.go
  server/api_runs_test.go
Labels: 2: Dev Review, 3: Security Review

#1901 Fix run channel attachment promotion
  server/api_runs_test.go
  server/app/playbook_run_service.go
Labels: 2: Dev Review, 3: Security Review
