Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2025-04, with the labels that each got.

#2002 Translations update from Mattermost Weblate
  webapp/i18n/nb_NO.json
Labels: Do Not Merge/Mattermod

#1994 MM-62690: Channel Membership gating in Playbooks
  .github/actions/test-with-db/action.yaml
  e2e-tests/tests/integration/playbooks/channels/post_type_components_spec.js
  e2e-tests/tests/integration/playbooks/runs/rdp_main_header_spec.js
  e2e-tests/tests/support/api/role.js
  server/api/graphql_run.go
  server/api/playbook_runs.go
  server/api_graphql_runs_test.go
  server/api_runs_test.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
Labels: 2: Dev Review, QA Deferred

#1999 MM-63410- Check all requestor information for playbook retrieval
  e2e-tests/tests/support/ui/channel.js
  server/api/playbook_runs.go
  server/api_runs_test.go
Labels: 4: Reviews Complete, QA Deferred

#2009 MM-63708 updated illustrations and UI tweaks
  webapp/src/components/assets/illustrations/bug_bash_svg.tsx
  webapp/src/components/assets/illustrations/bug_search_svg.tsx
  webapp/src/components/assets/illustrations/clipboard_checklist_svg.tsx
  webapp/src/components/assets/illustrations/customer_onboarding_svg.tsx
  webapp/src/components/assets/illustrations/dumpster_fire_svg.tsx
  webapp/src/components/assets/illustrations/employee_onboarding_svg.tsx
  webapp/src/components/assets/illustrations/feature_lifecycle_svg.tsx
  webapp/src/components/assets/illustrations/gears_svg.tsx
  webapp/src/components/assets/illustrations/handshake_svg.tsx
  webapp/src/components/assets/illustrations/incident_resolution_svg.tsx
  webapp/src/components/assets/illustrations/learn_playbooks_svg.tsx
  webapp/src/components/assets/illustrations/light_bulb_svg.tsx
  webapp/src/components/assets/illustrations/playbook_list_svg.tsx
  webapp/src/components/assets/illustrations/product_release_svg.tsx
  webapp/src/components/assets/illustrations/rocket_man_svg.tsx
  webapp/src/components/assets/illustrations/rocket_release_svg.tsx
  webapp/src/components/assets/illustrations/rocket_svg.tsx
  webapp/src/components/assets/illustrations/search_svg.tsx
  webapp/src/components/assets/illustrations/smiley_sunglasses_svg.tsx
  webapp/src/components/assets/no_metrics_svg.tsx
  webapp/src/components/assets/page_run_collaboration_svg.tsx
  webapp/src/components/backstage/metrics/no_metrics_placeholder.tsx
  webapp/src/components/backstage/playbook_list.tsx
  webapp/src/components/backstage/playbook_list_getting_started.tsx
  webapp/src/components/backstage/runs_page_no_content.tsx
  webapp/src/components/retrospective_reminder_posts.tsx
  webapp/src/components/rhs/rhs_home.tsx
  webapp/src/components/rhs/rhs_home_item.tsx
  webapp/src/components/rhs/rhs_run_list.tsx
  webapp/src/components/templates/template_data.tsx
  webapp/src/components/templates/template_item.tsx
Labels: 4: Reviews Complete, QA Deferred

#2010 Translations update from Mattermost Weblate
  webapp/i18n/nb_NO.json
Labels: Do Not Merge/Mattermod

#2013 Translations update from Mattermost Weblate
  webapp/i18n/en_AU.json
Labels: Do Not Merge/Mattermod
