Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2025-09, with the labels that each got.

#2074 Fix websocket not returning properties
  server/app/playbook_run_service.go
Labels: QA Deferred

#2075 Upload artifacts to S3
  .github/workflows/ci.yaml
Labels: 4: Reviews Complete, Setup Cloud Test Server

#2081 MM-65748: License validation missing support for 'entry' SKU type
  webapp/src/license.test.ts
  webapp/src/license.ts
Labels: QA Deferred

#2084 bump minimum mattermost version to 11.0.0
  plugin.json
Labels: 4: Reviews Complete, QA Deferred
