Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2025-10, with the labels that each got.

#2092 [MM-65159] Add UI support for hiding checklist items with condition
  server/api/graphql_run.go
  server/api/graphql_run_test.go
  webapp/i18n/en.json
  webapp/src/components/checklist/collapsible_checklist.tsx
  webapp/src/components/checklist_item/checklist_item.tsx
  webapp/src/components/checklist_item/condition_indicator.test.tsx
  webapp/src/components/checklist_item/condition_indicator.tsx
  webapp/src/components/rhs/rhs_checklist_list.tsx
Labels: 2: Dev Review, hacktoberfest-accepted, QA Deferred

#2096 Add missing conditional docs to REST api
  server/api/api.yaml
Labels: 4: Reviews Complete, hacktoberfest-accepted, QA Deferred

#2094 Add e2e tests for playbook and run attributes
  e2e-tests/package-lock.json
  e2e-tests/package.json
  e2e-tests/tests/integration/playbooks/playbooks/playbook_attributes_spec.js
  e2e-tests/tests/integration/playbooks/runs/run_attributes_spec.js
  e2e-tests/tests/support/api/playbooks.js
  e2e-tests/tests/support/index.d.ts
  e2e-tests/tests/support/index.js
  e2e-tests/tests/support/network_commands.js
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_properties/playbook_properties.tsx
  webapp/src/components/backstage/playbook_properties/property_name_input.tsx
  webapp/src/components/backstage/playbook_properties/property_values_input.tsx
  webapp/src/components/rhs/properties/property_chip.tsx
  webapp/src/components/rhs/properties/property_multiselect.tsx
  webapp/src/components/rhs/properties/property_select.tsx
  webapp/src/components/rhs/properties/property_text.tsx
  webapp/src/components/rhs/rhs_property.tsx
Labels: 2: Dev Review, QA Review Done, hacktoberfest-accepted
