Repository mattermost/mattermost-plugin-playbooks, pull requests merged in 2025-08, with the labels that each got.

#2028 MM-64519: Change license requirement from Enterprise+ to Pro+
  server/plugin.go
Labels: 2: Dev Review

#2057 Remove deprecated ExperimentalViewArchivedChannels from e2e test configs
  e2e-tests/tests/integration/playbooks/runs/rdp_rhs_runinfo_spec.js
  e2e-tests/tests/support/api/cloud_default_config.json
  e2e-tests/tests/support/api/on_prem_default_config.json
Labels: 2: Dev Review

#2051 Properties RHS
  go.mod
  go.sum
  server/api/graphql_json_test.go
  server/api/graphql_root.go
  server/api/graphql_root_property.go
  server/api/schema.graphqls
  server/app/playbook_run.go
  server/app/playbook_run_service.go
  server/app/properties.go
  server/app/property_service.go
  server/app/property_service_test.go
  server/command/command.go
  server/httptools/client.go
  server/main_test.go
  server/plugin.go
  server/sqlstore/actions.go
  server/sqlstore/migrate.go
  server/sqlstore/migrations.go
  server/sqlstore/migrations_test.go
  server/sqlstore/migrations_utils.go
  server/sqlstore/mockmocks/mock_storeapi.go
  server/sqlstore/playbook.go
  server/sqlstore/playbook_run.go
  server/sqlstore/stats.go
  server/sqlstore/store.go
  server/sqlstore/store_test.go
  server/sqlstore/support_for_test.go
  server/sqlstore/system.go
  server/sqlstore/user_info.go
  webapp/i18n/en.json
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info.tsx
  webapp/src/components/backstage/playbook_runs/playbook_run/rhs_info_properties.tsx
  webapp/src/components/rhs/properties/empty_state.tsx
  webapp/src/components/rhs/properties/property_chip.tsx
  webapp/src/components/rhs/properties/property_multiselect.tsx
  webapp/src/components/rhs/properties/property_select.tsx
  webapp/src/components/rhs/properties/property_select_input.tsx
  webapp/src/components/rhs/properties/property_text.tsx
  webapp/src/components/rhs/properties/property_text_input.tsx
  webapp/src/components/rhs/properties_list.tsx
  webapp/src/components/rhs/rhs_about.tsx
  webapp/src/components/rhs/rhs_property.tsx
  webapp/src/graphql/generated/gql.ts
  webapp/src/graphql/generated/graphql.ts
  webapp/src/graphql/hooks.ts
  webapp/src/graphql/runs.graphql
  webapp/src/types/playbook_run.ts
  webapp/src/types/properties.ts
Labels: 2: Dev Review

#2062 Translations update from Mattermost Weblate
  webapp/i18n/nb_NO.json
Labels: Do Not Merge/Mattermod

#2059 MM-65008: migrate post menu to registerPostDropdownMenuAction
  e2e-tests/tests/support/ui/playbooks.js
  plugin.json
  webapp/src/components/post_menu.tsx
  webapp/src/index.tsx
Labels: 4: Reviews Complete, QA Review Done

#2063 Fix double websocket when changing owner or assignee
  server/api/graphql_root_run.go
  server/app/playbook_run.go
  server/app/playbook_run_service.go
Labels: 3: QA Review
